### ISSUE TITLE
Get a Key error when testing accuracy on UCF101

### ISSUE THREAD

**Issue by actionderkokon** [yjxiong/temporal-segment-networks#102]
after loading the model,I got a error:

Traceback (most recent call last):
File "tools/eval_net.py", line 119, in 
video_scores = map(eval_video, eval_video_list)
File "tools/eval_net.py", line 69, in eval_video
video_frame_path = f_info[0][vid]
KeyError: 'v_ApplyEyeMakeup_g01_c01'

in the dataset ,v_ApplyEyeMakeup_g01_c01 exists indeed. and i try some methods to solve the problem ,but it does not work.

https://github.com/yjxiong/temporal-segment-networks/issues/79

**Comment by yjxiong** [comment]
This is the first video of the validation set. Can you check your input path to the `eval_net.py` scripts?

**Comment by actionderkokon** [comment]
I am sorry for this,  it is the error as u say, and it is testing.  Thank u for your excellent reply, and i would report the accuracy when it ends.

**Comment by actionderkokon** [comment]
hi，the accuracy on ucf101 split1 is as follows：
 flow：87.7%
rgb：84.28%
combine：93.22%
It is a nice job！Thank u for your patience.

**Comment by yjxiong** [comment]
Good to know. 

Closing this. Please feel free to reopen it if you meet any further problem.
