### ISSUE TITLE
meet trouble when reproducing your proposed results.

### ISSUE THREAD

**Issue by qijiezhao** [yjxiong/temporal-segment-networks#104]
Hi, Yuanjun:

I recently downloaded your TSN codes. And tried to reproduce your proposed result in your paper, but I only get 75.9%, 71.2% in the split 1, 2 of UCF101 dataset respectively in the spatial CNN part. far lower from 84.5%, which is the official paper result.

I just follow your README.md,  command is :

`python tools/eval_net.py ucf101 1 rgb ../data/ucf101/frames/ models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel --rgb_prefix='' --num_worker=2 --save_score='../result_1'`

this is only the spatial part, thanks for your early reply.

**Comment by yjxiong** [comment]
Can you use denseflow to process several videos and see if the ffmpeg get the same number of frames? 

Also, please check whether your frames are named in the pattern of `<prefix>_00002.jpg`.

**Comment by qijiezhao** [comment]
@yjxiong thanks for your reply, I have checked several videos and find that FFMPEG always extracted 2 frames more than DenseFlow , maybe this could not cause such a gap(nearly 10 percent)?

my frames are named like: 000001.jpg,  000002.jpg so I add a --rgb_prefix='',   If there exists problem, frames can not be read, then error occurs which prevents from producing a result?

**Comment by yjxiong** [comment]
frame numbers and names look ok. I am sure where is the problem. Can you take a look at the extracted frames and see if any difference?

Also, the system requires the folder holding the frames to have the name of the video excluding the extension. 

Given many possibilities, my advice is to use DenseFlow to extract frames and see if you can get correct results.

**Comment by qijiezhao** [comment]
@yjxiong thanks, Yuanjun. your suggestion makes a contribution, I find frames extracted by FFMPEG has a much lower resolution compared with DenseFlow. the detailed processing theory about FFMPEG and DenseFlow needs to be understood, I now begin to extract frames using DenseFlow. 

thanks again for your solution!
