### ISSUE TITLE
the speed is very slow for extracting optical_flow

### ISSUE THREAD

**Issue by IvyGongoogle** [yjxiong/temporal-segment-networks#107]
hello, I have a titan X gpu. When I run `bash scripts/extract_optical_flow.sh SRC_FOLDER OUT_FOLDER NUM_WORKER`, the speed is very slow.  why so slow even though only one GPU.
So it can not be real-time for test a simple video?
can you give some advises?

**Comment by yjxiong** [comment]
Be patient, UCF101 has 13000 videos and lasts more than 27 hours. Since you only use one GPU, expect several seconds to run each video because the videos are usually around 10 seconds long.

**Comment by IvyGongoogle** [comment]
@yjxiong , I only test a 3 seconds mp4 video, but find it is very slow.

**Comment by yjxiong** [comment]
What's the runtime then?

**Comment by IvyGongoogle** [comment]
@yjxiong hello, do not why it is very slow in my first try. Now it only spend about 3 seconds to extract optical flow for several seconds mp4. thank you~

**Comment by IvyGongoogle** [comment]
@yjxiong another problem.  I create a `videos` folder containing only a several seconds mp4. So there is results folder containing another 1 folder where the optical flow images of the video exist after I run the `bash scripts/extract_optical_flow.sh './videos' './results' 1`. Now I run `python tools/eval_net.py ucf101 1 rgb ./results models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel --gpus=0`. It shows error:

```
I0621 20:20:44.673199 17841 net.cpp:301] Memory required for data: 74005652
Traceback (most recent call last):
  File "tools/eval_net.py", line 121, in <module>
    video_scores = map(eval_video, eval_video_list)
  File "tools/eval_net.py", line 71, in eval_video
    video_frame_path = f_info[0][vid]
KeyError: 'v_ApplyEyeMakeup_g01_c01'
```
what causes this error? how to fix it?
looking forward to your reply.

**Comment by IvyGongoogle** [comment]
@yjxiong 我用中文复述一下，我现在只是测试一个几秒的视频1.mp4。我在主目录下建立了一个videos文件夹，里面放着这个几秒的测试视频1.mp4，当执行完`bash scripts/extract_optical_flow.sh './videos' './results' 1`这个命令后，在results文件夹下有一个名字为`1`的文件夹，1文件夹下面就是抽取的一些optical flow图片了。然后我执行`python tools/eval_net.py ucf101 1 rgb ./results models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel --gpus=0`，但是报错：

```
I0621 20:20:44.673199 17841 net.cpp:301] Memory required for data: 74005652
Traceback (most recent call last):
  File "tools/eval_net.py", line 121, in <module>
    video_scores = map(eval_video, eval_video_list)
  File "tools/eval_net.py", line 71, in eval_video
    video_frame_path = f_info[0][vid]
KeyError: 'v_ApplyEyeMakeup_g01_c01'
```
这是什么原因呢？ 怎么修复呢？急需您的建议。

**Comment by liuruoze** [comment]
全部提取完再测试，因为eval_net.py会假定frames的文件夹内有全部提取的UCF的视频列表。所以当你只有1个视频时，会报找不到key的错误。如果只测一个视频，需要修改eval_net的代码，或者用另一个项目anet2016-cuhk中的examples/classify_video.py

**Comment by IvyGongoogle** [comment]
@yjxiong @liuruoze  thank you, I will try.

**Comment by wcj021312** [comment]
@liuruoze  @IvyGongoogle 你好，我在运行bash scripts/extract_optical_flow.sh UCF-101 result 2
result文件夹中出现了13000多个空文件夹，按照作者的代码，每个文件夹应该有提取的特征的，不知道我的为什么是这样？环境已经按照build_all.bash装好了。是不是还缺了什么？

**Comment by wangwen39** [comment]
How did you solve the speed of extracting frame and optical flows? I found it is so slow to extract frames for one video in my 1080Ti -11G , and i have no idea about why it is so slow ? And i have about 80000 videos need to extract frame and flows , please help......thanks so much!
