### ISSUE TITLE
Is it possible to run multiple eval_net.py process with multiple workers?

### ISSUE THREAD

**Issue by GBJim** [yjxiong/temporal-segment-networks#11]
Hi guys.

When running the eval_net.py on the UCF-101 split_1 with 4 workers, I noticed that all my GPUs are running, but the GPU usage doesn't reach to the maximum. So I tried to run another eval_net.py process to evaluate the UCF-101 split_2, but I encountered lots of error messages like the following:

```
Setting device 1517
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0908 02:12:50.717952  3673 common.cpp:187] Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal
*** Check failure stack trace: ***
Setting device 1518
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0908 02:12:51.023628  3675 common.cpp:187] Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal
*** Check failure stack trace: ***
```

I am not sure these errors are caused by my machine(maybe my command was wrong)
Or the design of TSN doesn't allow doing this?

**Comment by yjxiong** [comment]
This error means you might be requesting more workers than the number of available GPU. 

Also, you are running 4 workers using `eval_net.py`. I don't quite understand the title of this issue.

**Comment by GBJim** [comment]
@yjxiong 
Oh, I get it.
 I have 4 GPU cores and have an `eval_net.py` process running with 4 workers already.
When I run the second process of `eval_net.py` with 4 workers, the total 8 workers exceeds the amount of my GPU cores and promtps the error messages.

**Comment by yjxiong** [comment]
It is OK to run two eval_net.py with 4 workers each. There might be some other error.

**Comment by GBJim** [comment]
@yjxiong 
Thanks a lot! I will try it again.

**Comment by xlliuplus7** [comment]
Hi @GBJim
I used to meet this problem too. Try adding CUDA_VISIBLE_DEVICES=0,1,2,3 before the python command, It works fine for me.

**Comment by GBJim** [comment]
@xlliuplus7 
Thanks for the tip!

**Comment by KnightOfTheMoonlight** [comment]
It is strange. I did not add `CUDA_VISIBLE_DEVICES=0,1,2,3` or anything else. I can still run two `eval_net` with 4 workers perfectly.

**Comment by KnightOfTheMoonlight** [comment]
@xlliu7  http://stackoverflow.com/questions/34775522/tensorflow-mutiple-sessions-with-mutiple-gpus
you mean this ->`$ CUDA_VISIBLE_DEVICES=0 python my_script.py  # Uses GPU 0.` RIght?
But I tried, and get error:  `error = cudaSuccess: (10 vs 0) invalid device ordinal`.
Do you have any suggestions?

**Comment by xlliu7** [comment]
@KnightOfTheMoonlight  That's exactly what I mean.
I use a workstation with 4 GPUs + CUDA 7.5 + cuDNN v5. The toolbox was compiled with MPI support.
I found it neccessary to add the "CUDA_VISIBLE_DEVICES" environment to use multiple GPUs. Otherwise I will get the "invalid device ordinal" error. I guess the caffe toolbox fails to detect available GPUs on my workstation. Your problem seems to be opposite to mine.
In fact, you can also mannually specify the dev_id in "eval_net.py". See https://github.com/yjxiong/temporal-segment-networks/blob/master/tools/eval_net.py#L32
