### ISSUE TITLE
ERROR in training

### ISSUE THREAD

**Issue by beihaidao** [yjxiong/temporal-segment-networks#110]
i just have 1 gpu 
& 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
the problem ONE is : 
(1)i change the N_GPU in scripts/train_tsn.sh to be 1 ,and change the batch_size in models/ucf101/tsn_bn_inception_rgb_train_val.protoxt. to be 128
(2) run
bash scripts/train_tsn.sh ucf101 rgb
then i get the error:
logging to logs/ucf101_rgb_split1.log
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[sandy:30438] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
TRY AGAIN: i make the try as:
i change MPI_BIN_DIR=/home/lalala/.openmpi/bin/  in  scripts/train_tsn.sh ,the N_GPU=1 & batch_size=128, but i also get  error:
 行 10: /home/sandy/.openmpi/bin/: 是一个目录
logging to logs/ucf101_rgb_split1.log
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "(null)" (-43) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[sandy:30451] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
TRY THREE TIMES:because i just have one gpu so i guess maybe need'nt mpi to parallel training ,so i change ：
${MPI_BIN_DIR}mpirun -np $N_GPU \
$TOOLS/caffe train --solver=models/${DATASET}/tsn_bn_inception_${MODALITY}_solver.prototxt  \
   --weights=models/bn_inception_${MODALITY}_init.caffemodel 2>&1 | tee ${LOG_FILE}

to
$TOOLS/caffe train --solver=models/${DATASET}/tsn_bn_inception_${MODALITY}_solver.prototxt  \
   --weights=models/bn_inception_${MODALITY}_init.caffemodel 2>&1 | tee ${LOG_FILE}
in scripts/train_tsn.sh
but i get the error:
I0705 20:57:13.839275 29401 solver.cpp:490]     Test net output #1: loss = 4.61802 (* 1 = 4.61802 loss)
F0705 20:57:13.889241 29401 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7ff24f4c2daa  (unknown)
    @     0x7ff24f4c2ce4  (unknown)
    @     0x7ff24f4c26e6  (unknown)
    @     0x7ff24f4c5687  (unknown)
    @     0x7ff24f995978  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7ff24f978171  caffe::Blob<>::mutable_gpu_data()
    @     0x7ff24f9c4a4a  caffe::CuDNNConvolutionLayer<>::Forward_gpu()
    @     0x7ff24f82302c  caffe::Net<>::ForwardFromTo()
    @     0x7ff24f8232bf  caffe::Net<>::ForwardPrefilled()
    @     0x7ff24f84a637  caffe::Solver<>::Step()
    @     0x7ff24f84b84f  caffe::Solver<>::Solve()
    @           0x40b02c  train()
    @           0x408e3d  main
    @     0x7ff24e6f1f45  (unknown)
    @           0x409212  (unknown)
    @              (nil)  (unknown)
Setting device 0
do you know how to  fix it? what cause the error?
looking forward to your reply.
last but not least, all command before " bash scripts/train_tsn.sh ucf101 rgb" i had run and get no error.

**Comment by beihaidao** [comment]
it seems to solved the last problem by set the bach_size to be a small number,such as 8.
and i get the result as:
I0706 09:42:08.366730  4402 solver.cpp:433] Iteration 3500, Testing net (#0)
I0706 09:42:36.688565  4402 solver.cpp:490]     Test net output #0: accuracy = 0.691579
I0706 09:42:36.688733  4402 solver.cpp:490]     Test net output #1: loss = 1.08233 (* 1 = 1.08233 loss)
I0706 09:42:36.688741  4402 solver.cpp:420] Optimization Done.
I0706 09:42:36.688745  4402 caffe.cpp:203] Optimization Done.
Setting device 0

**Comment by yjxiong** [comment]
I would like to notice that by reducing batch_size, you will need to increase `iter_size` or number of iterations trained to compensate. Otherwise, you will get inferior performance.
