### ISSUE TITLE
No module named _caffe

### ISSUE THREAD

**Issue by alexkongy** [yjxiong/temporal-segment-networks#111]
Hello, I run the example command but receive ImportError: No module named _caffe.
The command I run is:
python tools/eval_net.py ucf101 1 rgb FRAME_PATH \
 models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel \
 --num_worker 4 --save_scores SCORE_FILE

It looks like the author build a specified caffe but did not build caffe for python. What shall I do now? Thanks.

**Comment by yjxiong** [comment]
Check your caffe build under `lib/caffe-action`. It should have compiled its Python interfaces once you have all the dependencies installed, especially libboost >= 1.55.

**Comment by alexkongy** [comment]
I ended up with uncomment WITH_PYTHON_LAYER := 1 in Makefile.config of the Caffe. Actually, you may want to make the following changes to your build_all.sh:
1. cp Makefile.config.example Makefile.config for Caffe
2. Uncomment WITH_PYTHON_LAYER := 1.
3. make pycaffe.

Hope this helpful.

**Comment by yjxiong** [comment]
We don't use `Makefile` in `build_all.sh`. CMake automatically detects Python environments and enables the interfaces. I would suggest you follow the steps in `build_all.sh` cuz we do not have thorough testing on the Makefile build toolchain.

Thanks all the same.
