### ISSUE TITLE
what's the difference between num_worker and num_gpu

### ISSUE THREAD

**Issue by propaganda12** [yjxiong/temporal-segment-networks#113]
in README, "bash scripts/extract_optical_flow.sh SRC_FOLDER OUT_FOLDER NUM_WORKER" is said to execute optical flow computing, so I open "extract_optical_flow.sh" and find "build_of.py" in tools folder, and there are two parameters named num_worker and num_gpu, in README, it is said that num_worker specifies the number of gpu to be used, but what does num_gpu mean?

**Comment by yjxiong** [comment]
`num_gpu` is used when one wants to overload one GPU with several concurrent tasks. This sometimes increases the evaluation throughput. The pattern is specifying a `num_worker` larger (2 to 3 times) than `num_gpu`,
