### ISSUE TITLE
Feature learning on datasets

### ISSUE THREAD

**Issue by lemartin19** [yjxiong/temporal-segment-networks#114]
How did you extract features from the video frames?

We are working on a project that needs frame-wise feature extraction. We think your software could potentially help our algorithm significantly and were hoping for guidance on the methods you used to process the datasets.

**Comment by yjxiong** [comment]
Sorry I didn't quite get your point. Would you mind stating your exact issue?

**Comment by lemartin19** [comment]
Sorry for the confusion. We are working on a project that needs features for each frame. We are thinking about using the intermediate layer of features from your network (which would be more discriminative for classification). We don't need your loss layer but instead we will use SVM for classification. 

Therefore, our question is how shall we obtain the intermediate layer of features as the features for each video frame.  What command shall we use? Thank you.

**Comment by yjxiong** [comment]
The models are common Caffe models. If you have got the frames of the videos, you can use Python/Matlab/C++ interfaces and extract features by treating the video frames as normal images. This can be found in most Caffe tutorials such as

http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/00-classification.ipynb
http://caffe.berkeleyvision.org/gathered/examples/feature_extraction.html

**Comment by yjxiong** [comment]
Closing this. Please feel free to reopen it if you meet any further problem.
