### ISSUE TITLE
Cannot get the initialization models

### ISSUE THREAD

**Issue by ks-mengxi** [yjxiong/temporal-segment-networks#115]
Hi, yjxiong,

I'm trying to reproduce the results of TSN.
But I failed to get the initialization models through "bash scripts/get_init_models.sh"
It showed the error message "404 Not Found".

Thanks.

**Comment by yjxiong** [comment]
Hi, the server is temporarily unavailable. The link should be back into service in a while.

Sorry for any inconvenience caused.

**Comment by yjxiong** [comment]
Hi @ks-mengxi ,

The server is back online. Please try again downloading the init models.

**Comment by ks-mengxi** [comment]
Hi yjxiong,
Thank you for your help.
I can download them now.
