### ISSUE TITLE
extract_gpu.dir/all' failed

### ISSUE THREAD

**Issue by guiyuliu** [yjxiong/temporal-segment-networks#116]
hello， when building dense-flow , I can generate libpydenseflow.so, but there are two errors:

```
CMakeFiles/extract_gpu.dir/build.make:122: recipe for target 'extract_gpu' failed
make[2]: *** [extract_gpu] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/extract_cpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_cpu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed

```

I installed openmpi in  /usr/local/openmpi
I use ` MPI_PREFIX=/usr/local/openmpi bash build_all.sh MPI_ON`  to build 
I have 8 GPUs in my lab's server 
I delete all the files about TSN and tried again, still these  two errors, 
could you please help me?

**Comment by guiyuliu** [comment]
problem solved

**Comment by wcj021312** [comment]
hello,i have a problem when I run bash build_all.sh.
Can you give me a contact way? I want to  Ask some questions. Thank you !

**Comment by guiyuliu** [comment]
I forget "--recursive" when run build_all.sh

**Comment by guiyuliu** [comment]
hello, I have this problem because when I run
 git clone --recursive https://github.com/yjxiong/temporal-segment-networks

I FORGET --recursive


--

刘桂玉
上海市北斗导航与位置服务重点实验室
电子信息与电气工程学院
上海交通大学
中国上海市东川路800号
电话：13262502539
邮箱：liuguiyuok@163.com
---------------------------
Guiyu Liu


Department of Information Engineering,SEIEE
Shanghai Jiao Tong University
No.800 Dong Chuan Rd, Shanghai, China
TEL：13262502539
Email：liuguiyuok@163.com

At 2017-07-24 17:04:44, "wcj021312" <notifications@github.com> wrote:


hello,i have a problem when I run bash build_all.sh.
Can you give me a contact way? I want to Ask some questions. Thank you !

**Comment by jackyCold** [comment]
@guiyuliu   how do you solve the problem? can you tell me?  my e-mail:592847035@qq.com
