### ISSUE TITLE
Building Dense Flow  Faild

### ISSUE THREAD

**Issue by wcj021312** [yjxiong/temporal-segment-networks#117]
Building Dense Flow
CMake Error: The source directory "/home/sugon/code/temporal-segment-networks-master/lib/dense_flow" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.
Failed to build Dense Flow. Please check the logs above.

**Comment by wcj021312** [comment]
All tools built. Happy experimenting!

**Comment by gwh0112** [comment]
Hi, wcj
How do you solve this build issue? Thanks.
