### ISSUE TITLE
not get the images when extract optical_flow

### ISSUE THREAD

**Issue by wcj021312** [yjxiong/temporal-segment-networks#118]
when run bash scripts/extraction_optical_flow.sh UCF101 result 2
I get 13320 empty folder in result  and  no provide me error
my opencv support videoIO
please give me some suggestion,thank you!

**Comment by wcj021312** [comment]
opencv 3.0.0

**Comment by yjxiong** [comment]
See #28

**Comment by wcj021312** [comment]
@yjxiong Thank you for your reply. When run bash scripts/extract_optical_flow.sh UCF-101 result 2, but I  got 13320 empty folders.
No error feedback，so I do not how to solve.

**Comment by yjxiong** [comment]
You can run `extract_flow_gpu` on one video and see what happens to know the problem.

**Comment by wcj021312** [comment]
This error has occurred：


sugon@sugon-W580-G20:~/TSNCode/temporal-segment-networks/lib/dense_flow/build$ ./extract_gpu 1.avi
2017-07-30 15:02:18,634 FATAL [default] Check failed: [video_stream.isOpened()] Cannot open video stream "ex2.avi" for optical flow extraction.
2017-07-30 15:02:18,634 WARN  [default] Aborting application. Reason: Fatal log at [/home/sugon/TSNCode/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu.cpp:15]







------------------ 原始邮件 ------------------
发件人: "yjxiong";<notifications@github.com>;
发送时间: 2017年7月30日(星期天) 下午2:43
收件人: "yjxiong/temporal-segment-networks"<temporal-segment-networks@noreply.github.com>; 
抄送: "C.J！！！"<2925428721@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yjxiong/temporal-segment-networks] not get the images whenextract optical_flow (#118)




You can run extract_flow_gpu on one video and see what happens to know the problem.

**Comment by wcj021312** [comment]
I have updated my Nvidia-drivers, now I get the image. I have solved this problem. Thank you very much.

**Comment by yjxiong** [comment]
Good to know. Happy experimenting.

**Comment by milkcat0904** [comment]
hello,I got the same issue,and i run extract_flow_gpu on one video still got one empty file and no error.
my opencv is 2.4.9
any suggestion?thx a lot

**Comment by ymxv** [comment]
> See #28

@yjxiong  i docker pull the image you provided, then i run build_all.sh and 'happy experimenting' appeared, but when i run scripts/extract_optical_flow.sh, i meet the same question as @milkcat0904
, i sure the path is right, i don't think the extract_gpu worked. any suggestion? thank u 

你好，我通过docker下载了你的镜像，并成功运行了build_all.sh,出现了 'happy experimenting' ，但是当我运行scripts/extract_optical_flow.sh的时候，出现了和@milkcat0904相同的问题，在提取UCF视频集的时候，在输出文件夹中出现了13000多个空的文件夹，我看了build_of.py的源码，感觉

cmd = os.path.join(df_path + 'build/extract_gpu')+' -f {} -x {} -y {} -i {} -b 20 -t 1 -d {} -s 1 -o {} -w {} -h {}'.format(quote(vid_path), quote(flow_x_path), quote(flow_y_path), quote(image_path), dev_id, out_format, new_size[0], new_size[1])
os.system(cmd)

这两句好像没起作用，因此想询问一下是什么原因，能给我一些建议吗？ 谢谢

**Comment by ymxv** [comment]
> See #28

@yjxiong i docker pull the image you provided, then i run build_all.sh and 'happy experimenting' appeared, but when i run scripts/extract_optical_flow.sh, i meet the same question as @wcj021312 
, i sure the path is right, i don't think the extract_gpu worked. any suggestion? thank u

你好，我通过docker下载了你的镜像，并成功运行了build_all.sh,出现了 'happy experimenting' ，但是当我运行scripts/extract_optical_flow.sh的时候，出现了和@wcj021312 相同的问题，在提取UCF视频集的时候，在输出文件夹中出现了13000多个空的文件夹，我看了build_of.py的源码，感觉

cmd = os.path.join(df_path + 'build/extract_gpu')+' -f {} -x {} -y {} -i {} -b 20 -t 1 -d {} -s 1 -o {} -w {} -h {}'.format(quote(vid_path), quote(flow_x_path), quote(flow_y_path), quote(image_path), dev_id, out_format, new_size[0], new_size[1])
os.system(cmd)

这两句好像没起作用，因此想询问一下是什么原因，能给我一些建议吗？ 谢谢

**Comment by jimmy-ng** [comment]
Try this command instead:  cmd = os.path.join(df_path + 'build/extract_gpu')+' -f={} -x={} -y={} -i={} -b=20 -t=1 -d={} -s=1 -o={} -w={} -h={}'.format(quote(vid_path), quote(flow_x_path), quote(flow_y_path), quote(image_path), dev_id, out_format, new_size[0], new_size[1])

**Comment by sousoul** [comment]
> > See #28
> 
> @yjxiong i docker pull the image you provided, then i run build_all.sh and 'happy experimenting' appeared, but when i run scripts/extract_optical_flow.sh, i meet the same question as @wcj021312
> , i sure the path is right, i don't think the extract_gpu worked. any suggestion? thank u
> 
> 你好，我通过docker下载了你的镜像，并成功运行了build_all.sh,出现了 'happy experimenting' ，但是当我运行scripts/extract_optical_flow.sh的时候，出现了和@wcj021312 相同的问题，在提取UCF视频集的时候，在输出文件夹中出现了13000多个空的文件夹，我看了build_of.py的源码，感觉
> 
> cmd = os.path.join(df_path + 'build/extract_gpu')+' -f {} -x {} -y {} -i {} -b 20 -t 1 -d {} -s 1 -o {} -w {} -h {}'.format(quote(vid_path), quote(flow_x_path), quote(flow_y_path), quote(image_path), dev_id, out_format, new_size[0], new_size[1])
> os.system(cmd)
> 
> 这两句好像没起作用，因此想询问一下是什么原因，能给我一些建议吗？ 谢谢

你好！我也出现了空文件夹的问题；而且在docker里我输入pkg-config --modversion opencv查看opencv版本发现是2.4.9.1不是2.4.13，请问你出现这种情况了吗？谢谢！

**Comment by TitaniumOne** [comment]
@ymxv @sousoul Hello, I met the same problem, have you solved it?
