### ISSUE TITLE
RGB difference

### ISSUE THREAD

**Issue by taoxunqiang** [yjxiong/temporal-segment-networks#120]
Hello, @yjxiong @wanglimin

From your paper, you have made experiment with adding stacked RGB difference as another input
modality and investigate its performance in action recognition.

After checking the source code, I can not found the scripts about RGB difference extraction. 
So would you please tell me how to stacked RGB difference or where is the extraction methods?

Thank you very much.
Best regards

Tao Xunqiang
--

**Comment by jackyCold** [comment]
I also have the problem. can you  tell me how to stacked RGB difference?

**Comment by Raazzta** [comment]
Hi @taoxunqiang @jackyCold ,
Can you tell me where the code to *calculate* or *extract* RGB difference is? Thank you.

**Comment by Raazzta** [comment]
Forget the question, I found it.
