### ISSUE TITLE
Errors when bash build_all.sh

### ISSUE THREAD

**Issue by tanjie860110** [yjxiong/temporal-segment-networks#122]
Hi, @yjxiong when i bash build_all.sh this error happened,can you help me? thank you
------------
------------
OpenCV 2.4.13 built.
Building Dense Flow
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/build
Scanning dependencies of target denseflow
[ 14%] Building CXX object CMakeFiles/denseflow.dir/src/dense_warp_flow_gpu.cpp.o
[ 14%] Building CXX object CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o
In file included from /usr/local/include/opencv2/nonfree/nonfree.hpp:46:0,
                 from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:12:
/usr/local/include/opencv2/nonfree/features2d.hpp:81:5: error: ‘AlgorithmInfo’ does not name a type
     AlgorithmInfo* info() const;
     ^
In file included from /usr/local/include/opencv2/nonfree/nonfree.hpp:46:0,
                 from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:12:
/usr/local/include/opencv2/nonfree/features2d.hpp:132:5: error: ‘AlgorithmInfo’ does not name a type
     AlgorithmInfo* info() const;
     ^
/home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu.cpp: In function ‘void calcDenseFlowGPU(std::__cxx11::string, int, int, int, int, std::vector<std::vector<unsigned char> >&, std::vector<std::vector<unsigned char> >&, std::vector<std::vector<unsigned char> >&, int, int)’:
/home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu.cpp:27:5: error: reference to ‘FarnebackOpticalFlow’ is ambiguous
     FarnebackOpticalFlow alg_farn;
     ^
In file included from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu.cpp:5:0:
/usr/local/include/opencv2/gpu/gpu.hpp:1844:18: note: candidates are: class cv::gpu::FarnebackOpticalFlow
 class CV_EXPORTS FarnebackOpticalFlow
                  ^
In file included from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/include/common.h:10:0,
                 from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/include/dense_flow.h:8,
                 from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu.cpp:4:
/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv2/video/tracking.hpp:549:20: note:                 class cv::FarnebackOpticalFlow
 class CV_EXPORTS_W FarnebackOpticalFlow : public DenseOpticalFlow
                    ^
/home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu.cpp:72:70: error: ‘alg_farn’ was not declared in this scope
                     alg_farn(d_frame_0, d_frame_1, d_flow_x, d_flow_y);
                                                                      ^
/home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu.cpp: In function ‘void calcDenseFlowPureGPU(std::__cxx11::string, int, int, int, int, std::vector<std::vector<unsigned char> >&, std::vector<std::vector<unsigned char> >&, std::vector<std::vector<unsigned char> >&)’:
/home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu.cpp:144:5: error: reference to ‘FarnebackOpticalFlow’ is ambiguous
     FarnebackOpticalFlow alg_farn;
     ^
In file included from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu.cpp:5:0:
/usr/local/include/opencv2/gpu/gpu.hpp:1844:18: note: candidates are: class cv::gpu::FarnebackOpticalFlow
 class CV_EXPORTS FarnebackOpticalFlow
                  ^
In file included from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/include/common.h:10:0,
                 from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/include/dense_flow.h:8,
                 from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu.cpp:4:
/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv2/video/tracking.hpp:549:20: note:                 class cv::FarnebackOpticalFlow
 class CV_EXPORTS_W FarnebackOpticalFlow : public DenseOpticalFlow
                    ^
/home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu.cpp:174:73: error: ‘alg_farn’ was not declared in this scope
                     alg_farn(prev_gray, capture_gray, d_flow_x, d_flow_y);
                                                                         ^
In file included from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:22:0:
/home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/include/warp_flow.h: In function ‘void ComputeMatch(const std::vector<cv::KeyPoint>&, const std::vector<cv::KeyPoint>&, const cv::Mat&, const cv::Mat&, std::vector<cv::Point_<float> >&, std::vector<cv::Point_<float> >&)’:
/home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/include/warp_flow.h:101:60: error: ‘windowedMatchingMask’ was not declared in this scope
     Mat mask = windowedMatchingMask(kpts, prev_kpts, 25, 25);
                                                            ^
/home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp: In function ‘void calcDenseWarpFlowGPU(std::__cxx11::string, int, int, int, int, std::vector<std::vector<unsigned char> >&, std::vector<std::vector<unsigned char> >&)’:
/home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:50:2: error: reference to ‘FarnebackOpticalFlow’ is ambiguous
  FarnebackOpticalFlow alg_farn;
  ^
In file included from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:13:0:
/usr/local/include/opencv2/gpu/gpu.hpp:1844:18: note: candidates are: class cv::gpu::FarnebackOpticalFlow
 class CV_EXPORTS FarnebackOpticalFlow
                  ^
In file included from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/include/common.h:10:0,
                 from /home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:1:
/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv2/video/tracking.hpp:549:20: note:                 class cv::FarnebackOpticalFlow
 class CV_EXPORTS_W FarnebackOpticalFlow : public DenseOpticalFlow
                    ^
/home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:86:55: error: ‘alg_farn’ was not declared in this scope
      alg_farn(d_frame_0, d_frame_1, d_flow_x, d_flow_y);
                                                       ^
/home/tanjie/Proj/HAR/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:134:55: error: ‘alg_farn’ was not declared in this scope
      alg_farn(d_frame_0, d_frame_1, d_flow_x, d_flow_y);
                                                       ^
CMakeFiles/denseflow.dir/build.make:110: recipe for target 'CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o' failed
make[2]: *** [CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/denseflow.dir/build.make:134: recipe for target 'CMakeFiles/denseflow.dir/src/dense_warp_flow_gpu.cpp.o' failed
make[2]: *** [CMakeFiles/denseflow.dir/src/dense_warp_flow_gpu.cpp.o] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/denseflow.dir/all' failed
make[1]: *** [CMakeFiles/denseflow.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Failed to build Dense Flow. Please check the logs above.

**Comment by yjxiong** [comment]
`/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv2/`

Seems your CMake finds another version OpenCV. This causes the problem.

**Comment by tanjie860110** [comment]
@yjxiong OK，thank you, i have solved this problem.

**Comment by Light--** [comment]
> `/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv2/`
> 
> Seems your CMake finds another version OpenCV. This causes the problem.

@yjxiong  In order to run ```bash build.sh```, must i only install one version of opencv on the system? i also got similar errors about ``` dense_warp_flow_gpu.cpp``` when building dense_flow


full error information: https://github.com/yjxiong/temporal-segment-networks/issues/276

```
$ bash build_all.sh 
Building Dense Flow
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/temporal-segment-networks/lib/dense_flow/build
[  7%] Building CXX object CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o
[ 14%] Building CXX object CMakeFiles/denseflow.dir/src/dense_warp_flow_gpu.cpp.o
[ 21%] Building CXX object CMakeFiles/denseflow.dir/src/dense_flow.cpp.o
In file included from /home/user/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:
/usr/local/include/opencv2/xfeatures2d.hpp:213:103: error: expected ';' at end of member declaration
     virtual void compute( InputArray image, std::vector<KeyPoint>& keypoints, OutputArray descriptors ) CV_OVERRIDE = 0;
                                                                                                       ^
/usr/local/include/opencv2/xfeatures2d.hpp:213:105: error: 'CV_OVERRIDE' does not name a type
     virtual void compute( InputArray image, std::vector<KeyPoint>& keypoints, OutputArray descriptors ) CV_OVERRIDE = 0;
                                                                                                         ^
/usr/local/include/opencv2/xfeatures2d.hpp:217:59: error: expected ';' at end of member declaration
                           OutputArrayOfArrays descriptors ) CV_OVERRIDE;
                                                           ^
/usr/local/include/opencv2/xfeatures2d.hpp:217:61: error: 'CV_OVERRIDE' does not name a type
                           OutputArrayOfArrays descriptors ) CV_OVERRIDE;
                                                             ^
/usr/local/include/opencv2/xfeatures2d.hpp:934:22: error: no members matching 'cv::Feature2D::detectAndCompute' in 'class cv::Feat
     using Feature2D::detectAndCompute; // overload, don't hide
                      ^
In file included from /usr/local/include/opencv2/cudaarithm.hpp:50:0,
                 from /home/user/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:
/usr/local/include/opencv2/core/cuda.hpp:178:33: error: 'Stream' has not been declared
     void upload(InputArray arr, Stream& stream);
                                 ^
/usr/local/include/opencv2/core/cuda.hpp:195:36: error: 'Stream' has not been declared
     void download(OutputArray dst, Stream& stream) const;
                                    ^
/usr/local/include/opencv2/core/cuda.hpp:204:34: error: 'Stream' has not been declared
     void copyTo(OutputArray dst, Stream& stream) const;
                                  ^
/usr/local/include/opencv2/core/cuda.hpp:210:51: error: 'Stream' has not been declared
     void copyTo(OutputArray dst, InputArray mask, Stream& stream) const;
                                                   ^
/usr/local/include/opencv2/core/cuda.hpp:216:29: error: 'Stream' has not been declared
     GpuMat& setTo(Scalar s, Stream& stream);
                             ^
/usr/local/include/opencv2/core/cuda.hpp:222:46: error: 'Stream' has not been declared
     GpuMat& setTo(Scalar s, InputArray mask, Stream& stream);
                                              ^
/usr/local/include/opencv2/core/cuda.hpp:228:48: error: 'Stream' has not been declared
     void convertTo(OutputArray dst, int rtype, Stream& stream) const;
                                                ^
/usr/local/include/opencv2/core/cuda.hpp:234:62: error: 'Stream' has not been declared
     void convertTo(OutputArray dst, int rtype, double alpha, Stream& stream) const;
                                                              ^
/usr/local/include/opencv2/core/cuda.hpp:237:75: error: 'Stream' has not been declared
     void convertTo(OutputArray dst, int rtype, double alpha, double beta, Stream& stream) const;
                                                                           ^
In file included from /usr/local/include/opencv2/cudaarithm.hpp:50:0,
                 from /home/user/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:
/usr/local/include/opencv2/core/cuda.hpp:486:31: error: expected ')' before '&' token
     explicit BufferPool(Stream& stream);
                               ^
/usr/local/include/opencv2/core/cuda.hpp:666:26: error: 'Event' does not name a type
     void waitEvent(const Event& event);
                          ^
In file included from /usr/local/include/opencv2/core/cuda.hpp:1047:0,
                 from /usr/local/include/opencv2/cudaarithm.hpp:50,
                 from /home/user/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:
/usr/local/include/opencv2/core/cuda.inl.hpp: In member function 'cv::cuda::GpuMat cv::cuda::GpuMat::clone() const':
/usr/local/include/opencv2/core/cuda.inl.hpp:157:13: error: no matching function for call to 'cv::cuda::GpuMat::copyTo(cv::cuda::G
     copyTo(m);
             ^
In file included from /usr/local/include/opencv2/cudaarithm.hpp:50:0,
                 from /home/user/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:
/usr/local/include/opencv2/core/cuda.hpp:201:10: note: candidate: void cv::cuda::GpuMat::copyTo(cv::OutputArray) const
     void copyTo(OutputArray dst) const;
          ^
/usr/local/include/opencv2/core/cuda.hpp:201:10: note:   no known conversion for argument 1 from 'cv::cuda::GpuMat' to 'cv::Output
/usr/local/include/opencv2/core/cuda.hpp:204:10: note: candidate: void cv::cuda::GpuMat::copyTo(cv::OutputArray, int&) const
     void copyTo(OutputArray dst, Stream& stream) const;
          ^
/usr/local/include/opencv2/core/cuda.hpp:204:10: note:   candidate expects 2 arguments, 1 provided
/usr/local/include/opencv2/core/cuda.hpp:207:10: note: candidate: void cv::cuda::GpuMat::copyTo(cv::OutputArray, cv::InputArray) c
     void copyTo(OutputArray dst, InputArray mask) const;
          ^
/usr/local/include/opencv2/core/cuda.hpp:207:10: note:   candidate expects 2 arguments, 1 provided
/usr/local/include/opencv2/core/cuda.hpp:210:10: note: candidate: void cv::cuda::GpuMat::copyTo(cv::OutputArray, cv::InputArray, i
     void copyTo(OutputArray dst, InputArray mask, Stream& stream) const;
          ^
/usr/local/include/opencv2/core/cuda.hpp:210:10: note:   candidate expects 3 arguments, 1 provided
In file included from /usr/local/include/opencv2/core/cuda.hpp:1047:0,
                 from /usr/local/include/opencv2/cudaarithm.hpp:50,
                 from /home/user/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:
/usr/local/include/opencv2/core/cuda.inl.hpp: In member function 'void cv::cuda::GpuMat::copyTo(cv::OutputArray, cv::InputArray) c
/usr/local/include/opencv2/core/cuda.inl.hpp:164:37: error: no matching function for call to 'cv::cuda::GpuMat::copyTo(const cv::_
     copyTo(dst, mask, Stream::Null());
                                     ^
In file included from /usr/local/include/opencv2/cudaarithm.hpp:50:0,
                 from /home/user/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:
/usr/local/include/opencv2/core/cuda.hpp:201:10: note: candidate: void cv::cuda::GpuMat::copyTo(cv::OutputArray) const
     void copyTo(OutputArray dst) const;
          ^
/usr/local/include/opencv2/core/cuda.hpp:201:10: note:   candidate expects 1 argument, 3 provided
/usr/local/include/opencv2/core/cuda.hpp:204:10: note: candidate: void cv::cuda::GpuMat::copyTo(cv::OutputArray, int&) const
     void copyTo(OutputArray dst, Stream& stream) const;
          ^
/usr/local/include/opencv2/core/cuda.hpp:204:10: note:   candidate expects 2 arguments, 3 provided
In file included from /usr/local/include/opencv2/core/cuda.hpp:1047:0,
                 from /usr/local/include/opencv2/cudaarithm.hpp:50,
                 from /home/user/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:
/usr/local/include/opencv2/core/cuda.inl.hpp:162:6: note: candidate: void cv::cuda::GpuMat::copyTo(cv::OutputArray, cv::InputArray
 void GpuMat::copyTo(OutputArray dst, InputArray mask) const
      ^
/usr/local/include/opencv2/core/cuda.inl.hpp:162:6: note:   candidate expects 2 arguments, 3 provided
In file included from /usr/local/include/opencv2/cudaarithm.hpp:50:0,
                 from /home/user/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:
/usr/local/include/opencv2/core/cuda.hpp:210:10: note: candidate: void cv::cuda::GpuMat::copyTo(cv::OutputArray, cv::InputArray, i
     void copyTo(OutputArray dst, InputArray mask, Stream& stream) const;
          ^
/usr/local/include/opencv2/core/cuda.hpp:210:10: note:   no known conversion for argument 3 from 'cv::cuda::Stream' to 'int&'
In file included from /usr/local/include/opencv2/core/cuda.hpp:1047:0,
                 from /usr/local/include/opencv2/cudaarithm.hpp:50,
                 from /home/user/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:
/usr/local/include/opencv2/core/cuda.inl.hpp: In member function 'cv::cuda::GpuMat& cv::cuda::GpuMat::setTo(cv::Scalar)':
/usr/local/include/opencv2/core/cuda.inl.hpp:170:35: error: no matching function for call to 'cv::cuda::GpuMat::setTo(cv::Scalar&,
     return setTo(s, Stream::Null());

```
