### ISSUE TITLE
error run with one gpu

### ISSUE THREAD

**Issue by tanjie860110** [yjxiong/temporal-segment-networks#123]
hi, @yjxiong i want to know could this project running on a machine with one gpu, when i run the script python tools/eval_net.py ucf101 1 rgb FRAME_PATH \
 models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel \
 --num_worker 4 --save_scores SCORE_FILE

this error happened,is the reason of the number of gpu?

ucf101
parse frames under folder /home/tanjie/ws/ImageData/HAR/UCF-101-data-1
0 videos parsed
200 videos parsed
400 videos parsed
frame folder analysis done
Setting device 0
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0810 19:46:00.397214 14156 net.cpp:46] Initializing net from parameters: 
name: "BN-Inception"
input: "data"
input_dim: 1
input_dim: 3
input_dim: 224
input_dim: 224
state {
  phase: TEST
}
layer {
  name: "conv1/7x7_s2"
  type: "Convolution"
  bottom: "data"
.
.
.
.
I0810 19:46:02.198587 14156 net.cpp:244] conv1/7x7_s2 does not need backward computation.
I0810 19:46:02.198591 14156 net.cpp:285] This network produces output fc-action
I0810 19:46:02.198774 14156 net.cpp:551] Collecting Learning Rate and Weight Decay.
I0810 19:46:02.198812 14156 net.cpp:300] Network initialization done.
I0810 19:46:02.198815 14156 net.cpp:301] Memory required for data: 74005652
Traceback (most recent call last):
  File "tools/eval_net.py", line 120, in <module>
    video_scores = map(eval_video, eval_video_list)
  File "tools/eval_net.py", line 70, in eval_video
    video_frame_path = f_info[0][vid]
KeyError: 'v_ApplyEyeMakeup_g08_c01'

**Comment by yjxiong** [comment]
parse frames under folder /home/tanjie/ws/ImageData/HAR/UCF-101-data-1
0 videos parsed
200 videos parsed
400 videos parsed
frame folder analysis done

In my understanding, the validation sets of UCF101 all have more than 3000 videos. Did you miss some videos here? The evaluation could run perfectly on any number of GPU(s).

**Comment by tanjie860110** [comment]
@yjxiong thank you,i will try again after the extracted of videos finished.

**Comment by yjxiong** [comment]
Any progress? @tanjie860110
