### ISSUE TITLE
Use all GPU memory to extract optical_flow

### ISSUE THREAD

**Issue by MohammadMoradi** [yjxiong/temporal-segment-networks#124]
Hi, is it possible to use all gpu memory to extract optical_flow? I mean something like batch processing in caffe. My gpu has 6G ram but only 400M is used to extract optical_flow. So it takes lots of time to extract all of them.

**Comment by yjxiong** [comment]
The speed of flow extraction does not depend on the memory usage.  

However, it is possible to run several extract_gpu at the same time which could accelerate the process a little bit.

**Comment by yjxiong** [comment]
Any further comments? @MohammadMoradi

**Comment by MohammadMoradi** [comment]
Thanks for your response.
