### ISSUE TITLE
FATAL [default] Check failed: [video_stream.isOpened()] Cannot open video stream "ex2.avi" for optical flow extraction.

### ISSUE THREAD

**Issue by wlgcqh** [yjxiong/temporal-segment-networks#125]
how to deal with that problem? @yjxiong

**Comment by yjxiong** [comment]
What command did you issue?

**Comment by wlgcqh** [comment]
just type ./build/extract_gpu

**Comment by yjxiong** [comment]
Please follow the instructions on how to do flow extraction here
https://github.com/yjxiong/temporal-segment-networks#extract-frames-and-optical-flow-images

**Comment by niveditarahurkar** [comment]
I followed the same method as https://github.com/yjxiong/temporal-segment-networks#extract-frames-and-optical-flow-images but still see the error. Only thing different is I am running on GCP and just have 1 GPU. So my num_worker is 1.

**Comment by yjxiong** [comment]
@niveditarahurkar Please make sure your GCP instance has OpenCV installed and it is compiled with Video IO support (needs FFMPEG). You can also pull the provided Docker image to run flow extraction.

**Comment by niveditarahurkar** [comment]
I have the ffmpeg here:
nirahurk@cs231a1-vm:~/temporal-segment-networks/opencv-2.4.13.5/3rdparty/ffmpeg$ ls
ffmpeg_version.cmake  ffopencv.c  make.bat  opencv_ffmpeg_64.dll  opencv_ffmpeg.dll  readme.txt
nirahurk@cs231a1-vm:~/temporal-segment-networks/opencv-2.4.13.5/3rdparty/ffmpeg$
When I do import cv2 from here it works. But when I try to import from cd /temporal-segment-networks/ it complains with the above error.

**Comment by yjxiong** [comment]
This means you could have another opencv installation. Try change your environment variables (PATH, LD_LIBRARY_PATH) to use the working one.

**Comment by niveditarahurkar** [comment]
@yjxiong Thank you! My opencv was in /usr/bin/Python2.7 and my notebook was running on anaconda3/python3.7. So when I moved to python 2.7 it worked. However, I am facing another issue. #268

**Comment by Malithi-gif** [comment]
@niveditarahurkar how you change environment variables in colab?

**Comment by Malithi-gif** [comment]
@yjxiong can you explain how to change the directory of OpenCV. I am running on google colab?
