### ISSUE TITLE
Each time i run the video-level testing, a different test accuracy is displayed.

### ISSUE THREAD

**Issue by lengmm** [yjxiong/temporal-segment-networks#126]
hello@yjxiong ，I change you codes to solve a binary classification. The training process had no problem. Every time I ran the video-level testing case,I got different test accuracy.Could you give me some advice？

**Comment by yjxiong** [comment]
The testing process should be deterministic. Does your split parse have any randomness in the validation set? For example, the frame per video, or videos to be evaluated.

**Comment by lengmm** [comment]
Thank you,I find out what the problem is. The weights of the last layer in network is not loaded correctly.

**Comment by yjxiong** [comment]
Good to know.
Closing this. Please feel free to reopen it if you meet any further problem.
