### ISSUE TITLE
Can pre-trained initialization models be used in commercial applications

### ISSUE THREAD

**Issue by guangbaby** [yjxiong/temporal-segment-networks#127]
Dear @yjxiong,

I have a question.  Can pre-trained initialization models (e.g. bn_inception_spatial_var_init.caffemodel) be used in commercial applications? 

Thank you in advance.

**Comment by yjxiong** [comment]
The codebase is released with its license in 

https://github.com/yjxiong/temporal-segment-networks/blob/master/LICENSE

For the model weights, because we don't have the copyrights of the videos used in training, I suggest you ask for legal advice if you want to use them for commercial products.

**Comment by guangbaby** [comment]
Dear @yjxiong,

Thank you for reply. 
I understood it.
