### ISSUE TITLE
 Error parsing text-format caffe.NetParameter:  Message type "caffe.LayerParameter" has no field named "bn_param".

### ISSUE THREAD

**Issue by buaa-luzhi** [yjxiong/temporal-segment-networks#128]
Hi, @yjxiong
python tools/eval_net.py ucf101 1 rgb FRAME_PATH \
 models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel \
 --num_worker 4 --save_scores SCORE_FILE

W0901 14:59:26.851496 12575 _caffe.cpp:128] Net('models/hmdb51/tsn_bn_inception_rgb_deploy.prototxt', 1, weights='models/hmdb51_split_1_tsn_rgb_reference_bn_inception.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 19:12: Message type "caffe.LayerParameter" has no field named "bn_param".
F0901 14:59:26.854511 12575 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/hmdb51/tsn_bn_inception_rgb_deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

caffe-action has been installed successfully.
Can you give me some advice about how to solve it!

Thank you so much!

**Comment by yjxiong** [comment]
Have you strictly followed the instructions in README? You are running on another version of Caffe installed.

**Comment by buaa-luzhi** [comment]
yes,  according to the ReadMe every step, and download caffe from "https://github.com/yjxiong/caffe" and installed successfully.

**Comment by yjxiong** [comment]
I don't which README you are reading. But people usually go step by step starting from

https://github.com/yjxiong/temporal-segment-networks#get-the-code

and follow on.

**Comment by buaa-luzhi** [comment]
but, i have only one gpu, this is different from you

**Comment by buaa-luzhi** [comment]
The ReadMe is in the temporal-segment-networks zip file, i download it from "https://github.com/yjxiong"

**Comment by yjxiong** [comment]
Then I guess it is the same as the one in the front page of this page. Please read it carefully and follow the step by step guide.

**Comment by buaa-luzhi** [comment]
Thank you!

**Comment by yjxiong** [comment]
I have said in the first reply you are running another version of Caffe. If you have followed the instructions on how to install, this should not have happened.

**Comment by buaa-luzhi** [comment]
I'll reinstall caffe following the instructions.   thank you!

**Comment by buaa-luzhi** [comment]
@yjxiong 
Sorry to disturb you again!
First，git clone --recursive https://github.com/yjxiong/temporal-segment-networks
Second compile caffe, mkdir build && cd build    cmake .. -DUSE_MPI=ON    make && make install
Third， dataset has been download
Fourth, python tools/eval_net.py ucf101 1 rgb FRAME_PATH \
 models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel \
 --num_worker 4 --save_scores SCORE_FILE

Still making mistakes.

I hope you can help me again, thank you!

**Comment by yjxiong** [comment]
Did you use the `build_all.sh` script? I am not able to help you if you keep not following the instructions.

**Comment by buaa-luzhi** [comment]
Because, i have been installed Opencv-3-2-0-rc.
so, if i used build_all.sh, i am worry about conflict with Opencv2..4.13.

**Comment by yjxiong** [comment]
It simply won't.

**Comment by buaa-luzhi** [comment]
Do you have any advice, thank you!

**Comment by buaa-luzhi** [comment]
Ok, thank you, i will try.

**Comment by buaa-luzhi** [comment]
@yjxiong 
Hello,
Thanks for your reply, I am so sorry disturb you again!
First, run the "build_all.sh" script, everything is ok,
However, when execute python tools/evel_net.py ... , this error occurs again.
At the moment, I feel helpless

**Comment by yjxiong** [comment]
I have said you are running another Caffe installed on your machine. Another, less possible, reason could be that you have libboost version lower than 1.55, which will leat to the Python interface failing to compile.

**Comment by buaa-luzhi** [comment]
@yjxiong 
Yes, you are right, i have solved this problem!
Thank you for your reply!

**Comment by yjxiong** [comment]
Closing this. Please feel free to reopen it if you meet any further problem.
