### ISSUE TITLE
Specify which GPUs to be used in training

### ISSUE THREAD

**Issue by GBJim** [yjxiong/temporal-segment-networks#13]
Hi guys:

I have 4 GPU cores with 12G memory. When I run the training command with multi-core setting,
an out-of-memory error was encountered: `Check failed: error == cudaSuccess (2 vs. 0)  out of memory` 

It was caused by my first core, most of the memory of it is occupied by another process.
I tried the command  `CUDA_VISIBLE_DEVICES=1,2,3` to avoid accessing first core, but it doesn't work. The training process always tries to access my first core and cause the error.

The training configuration on the `README.md` only provides the way to specify how many cores to be used but not **which** cores to be used.
```

Environment:

Ubuntu14.04 in nvidia-docker
cuDNN V5
K80 4 GPU cores

```

Any suggestion? :)

**Comment by GBJim** [comment]
I realized that there is a section of GPU setting in solvers. For example the [line 30 of tsn_bn_inception_rgb_solver.prototxt ](https://github.com/yjxiong/temporal-segment-networks/blob/master/models/ucf101/tsn_bn_inception_rgb_solver.prototxt#L30)

Thanks!

**Comment by Ai-is-light** [comment]
@GBJim hi, after setting the device_id:[ 2,3,4], the training network only  work with GPU=2, wihle the GPU=3,4 do not work with GPU=2.
