### ISSUE TITLE
Cannot use GPU in CPU-only Caffe: check mode

### ISSUE THREAD

**Issue by ncuxiaogang** [yjxiong/temporal-segment-networks#130]
Thanks for sharing your code publicly.  I install the OpenMPI with cuda and build with commadn "MPI_PREFIX=/usr/local bash build_all.sh MPI_ON"successfully. Also I have extract the RGB frame and Optical Flow frame successfully. But when I use the sample code "python tools/eval_net.py ucf101 1 rgb FRAME_PATH \
 models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel \
 --num_worker 4 --save_scores SCORE_FILE", I have the error below:

parse frames under folder HMDB51_PATH
0 videos parsed
200 videos parsed
400 videos parsed
600 videos parsed
800 videos parsed
1000 videos parsed
1200 videos parsed
1400 videos parsed
1600 videos parsed
1800 videos parsed
2000 videos parsed
2200 videos parsed
2400 videos parsed
2600 videos parsed
2800 videos parsed
3000 videos parsed
3200 videos parsed
3400 videos parsed
3600 videos parsed
3800 videos parsed
4000 videos parsed
4200 videos parsed
4400 videos parsed
4600 videos parsed
4800 videos parsed
5000 videos parsed
5200 videos parsed
5400 videos parsed
5600 videos parsed
5800 videos parsed
6000 videos parsed
6200 videos parsed
6400 videos parsed
6600 videos parsed
frame folder analysis done
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0905 10:52:12.753376  8856 common.cpp:111] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
Aborted (core dumped)

I have double checked that the file "./lib/caffe-action/CMakelist.txt" in line 18:
caffe_option(CPU_ONLY  "Build Caffe without CUDA support" OFF) # TODO: rename to USE_CUDA

I have no idea why the above error occurs. Would you please give an instruction to solve the problem? Thanks a lot.

**Comment by yjxiong** [comment]
`CPU-only Caffe` The Caffe you are running compiled with CPU only mode. 
Either you don't have GPU on your machine or you are running another Caffe installed on your machine. Please check your environment setting if the latter is the case.

**Comment by ncuxiaogang** [comment]
@yjxiong I have solved the problem. The reason is that I have installed servel versions of Caffe. Thanks a lot.
