### ISSUE TITLE
reshape_param { shape { dim: [-1, 1, 3, 101] } } 

### ISSUE THREAD

**Issue by taoxunqiang** [yjxiong/temporal-segment-networks#131]
Hello, @yjxiong @wanglimin 

I have a question.
In line 790 of ucf101/tsn_bn_inception_rgb_train_val.prototxt:
layer { name: "reshape_fc" type: "Reshape" bottom: "fc" top: "reshape_fc" reshape_param { shape { dim: [-1, 1, 3, 101] } } } 
here, the 3 means 3 axis of RGB?

thank you.

**Comment by yjxiong** [comment]
No. This is for the 3 segments.

**Comment by guangbaby** [comment]
Thank you very much. 
I got it.

**Comment by yjxiong** [comment]
Closing this. Please feel free to reopen it if you meet any further problem.
