### ISSUE TITLE
About extracting optical_flow

### ISSUE THREAD

**Issue by junfengluo** [yjxiong/temporal-segment-networks#135]
Hi, I am reading the papers about recognition and detection of TSN, SSN and UntrimmedNet. But I meet a problem when I try to run the code of TSN about optical_flow extraction. My server system is CentOS and I have no sudo permission, so I can't run the build_all.sh to install all the libraries. How can I solve the problem by other ways? My server has already installed Caffe.
Can I install Opencv by myself?  and then use the "# build dense_flow" part in the build_all.sh to build dense_flow. 
Thanks very much.

**Comment by yjxiong** [comment]
Yes. You can install the dependencies manually.

**Comment by Tonyfy** [comment]
million of thanks firstly.
my server machine not connect to the internet, I just install openmpi, opencv,dense_flow,caffe-action and other dependencies one-by-one, now base on the released ```ucf101_split1_rgb``` and ```ucf101_split1_flow``` caffemodel,I have obtained 94.02% classification accuracy rate when fusion score_weight set to ```1.15:1```.which should be similar to origin paper at 2 modalities(94.0%,Page13/16 Table6)

**Comment by yjxiong** [comment]
@Tonyfy
Good to know. 
BTW, the reported accuracy is an average over the three splits, using fusion weights 1:1. So you don’t have to tune the fusion weights on one split .

**Comment by Tonyfy** [comment]
@yjxiong 
You are right, I just test on split1 , the accuracy is 93.82% when fusion with 1:1(default set in your script), I don't test on split2/split3 yet , cause i guess it should lead to similar result with  split1.
Nextly, i would come to temporal action detection or spatial-temporal action detection base on TSN, thanks to your nice work.

**Comment by sujoyp** [comment]
@yjxiong 
I am having a problem with the flow extraction code. I executed ./build_all.sh omitting the lines requiring sudo access (as I don't have it now and was told by the admin that the dependencies are already installed), and it did build all the required packages. However, when I execute the extract_optical_flow.sh it is showing me extraction done but I don't see any flow images in the folder it created by the video name. I investigated more to find VideoCapture is throwing an error 

   (python:33800): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed

Is this the main problem ? If yes, shouldn't it have been installed by the build_all.sh ?

**Comment by yjxiong** [comment]
Looks like some problem with your Gstreamer installation. Googling your error log links to the following discussion:

https://github.com/jcaden/gst-plugins-bad/issues/1

**Comment by sujoyp** [comment]
I installed GStreamer but it is still not working. It seems that the Video I/O options are showing NO  while installing the OpenCV package using build_all.sh in a CentOS machine.

**Comment by junfengluo** [comment]
@sujoyp  build_all.sh is compiled in Ubuntu like OS， you should install the dependencies manually.

**Comment by sujoyp** [comment]
@junfengluo 
I have installed all the dependencies for OpenCV in CentOS corresponding to the ones mentioned in build_all.sh. The mappings are as follows:
protobuf-devel #libprotobuf-dev
leveldb-devel # libleveldb-dev
snappy-devel #libsnappy-dev
hdf5-devel # libhdf5-serial-dev
protobuf-compiler # protobuf-compiler
atlas-devel # libatlas-base-dev
boost-devel # libboost1.55-all-dev
gflags-devel # libgflags-dev
glog-devel # libgoogle-glog-dev
lmdb-devel # liblmdb-dev
libzip-devel # libzip-dev
opencv-devel # libopencv-dev
gcc-c++ # build-essential
# checkinstall NOTE Ubuntu only
cmake # cmake
pkgconfig # pkg-config
yasm # yasm
libjpeg-turbo-devel # libjpeg-dev
jasper-devel # libjasper-dev
ffmpeg-devel # libavcodec-dev
ffmpeg-devel # libavformat-dev
ffmpeg-devel # libswscale-dev
libdc1394-devel # libdc1394-22-dev
gstreamer-devel # libgstreamer0.10-dev
gstreamer-plugins # libgstreamer-plugins-base0.10-dev NOTE multiple gstreamer-plugins-* packages in CentOS, all installed
libv4l-devel # libv4l-dev
python-devel # python-dev
# python-numpy NOTE from Anaconda
tbb-devel # libtbb-dev
qt-devel # libqt4-dev
gtk2-devel # libgtk2.0-dev
faac-devel # libfaac-dev
lame-devel # libmp3lame-dev
opencore-amr-devel # libopencore-amrnb-dev
opencore-amr-devel # libopencore-amrwb-dev
libtheora-devel  # libtheora-dev
libvorbis-devel # libvorbis-dev
xvidcore-devel # libxvidcore-dev
x264 # x264
v4l-utils # v4l-utils

Is anything missing ?

**Comment by junfengluo** [comment]
I also installed many times in my CentOS server, at last, I didn't follow his guidance but searched the method that using opencv to read videos in Google.

**Comment by sujoyp** [comment]
Can you please direct me to the instructions you used to install opencv as required for this in CentOS ?

**Comment by sujoyp** [comment]
@junfengluo  @yjxiong 
Now I am doing everything in ubuntu 14.04 docker. Also VideoCapture seems to be working fine. However, the optical flow images are not getting extracted. It is creating folders for each video and displaying that it is done but there aren't any images inside the folder. Is there any other reason which is a cause of this ?

**Comment by junfengluo** [comment]
Are you sure the dense_flow part is built will? The optical images are based on this folder.

发自我的 iPhone

**Comment by shajie17** [comment]
@sujoyp hello, I have the same problem with you .
the optical flow images are not getting extracted. It is creating folders for each video and displaying that it is done but there aren't any images inside the folder.
can you tell me how did you solve it.the dense_flow part is built well.thank you very much

**Comment by Line290** [comment]
It seems very slow due to I/O frequently and cannot utilize GPU capacity as much as possible.

**Comment by yjxiong** [comment]
If you have problem building any tool you can use the provided docker image in `README`.

**Comment by Robinxin123** [comment]
@junfengluo  大佬，我也是没有sudo权限，你是怎么手动安装的。。我docker image也用不了，因为登陆还是需要sudo权限
