### ISSUE TITLE
pytorch RGB flow UCF101 batchsize 256 achieves 84.4 accuracy  

### ISSUE THREAD

**Issue by ntuyt** [yjxiong/temporal-segment-networks#138]
I just run the pytorch code using the default configuration with batch size 256.
But I only get the 84.4 accuracy.
In contrast the accuracy reported by paper is 85.5 which is implemented by caffe I think.
Anyone can repeat the performance 85.5 using pytorch?

**Comment by yjxiong** [comment]
I mentioned on the TSN website that one split result with single modality is not stable and should not be used for reporting and comparing performance. Thus in the paper we compare with other methods using average of 3 splits and RGB+Flow.
