### ISSUE TITLE
cudn_version_disable_cudnn_effect

### ISSUE THREAD

**Issue by liu666666** [yjxiong/temporal-segment-networks#14]
Hi, i have two versions of CUDA in my server : CUDA7.0 and CUDA7.5 .  
       When it  configured with CUDA7.5  , cmake shows that OpenCV static library was compiled with CUDA 7.0 support.  
       Please, use the same version or rebuild OpenCV with CUDA 7.5. 
       I do not have the right to rebuild the opencv. so  i have to use the CUDA 7.0,cmake is ok,
       But make occurs errors: lib/caffe-action/include/caffe/util/cudnn.hpp:94:3: error: too many arguments to function ‘cudnnStatus_t cudnnSetFilter4dDescriptor(cudnnFilterDescriptor_t, cudnnDataType_t, int, int, int, int)’,
       It likes the cudnn version, could you please give me a solution?
       Now, i disable the cudnn and make the code successfully configured with cuda7.0, 
       However ,i know disable the cudnn will slow the trainning ,Will  it effect the accuary?
       I also have a question,the step extract the optical flow is obtain each optical flow or down sample and how down sample?

**Comment by yjxiong** [comment]
Disabling cuDNN won't affect the accuracy. But the memory usage will grow due to the native implementation of convolution in Caffe. We have a local build of OpenCV for DenseFlow, you can also use that to build your Caffe. In this way you no longer need the permission to rebuild the system-wide OpenCV installation.

For the second problem, optical flow is extracted for each time step.

**Comment by liu666666** [comment]
Thanks for your prompt reply! 
I find that if i build of OpenCV for DenseFlow , First  i need  install OpenCV dependenices such as build-essential, will it update the system-wide dependency?
For the second problem, what each time step means, extract 1 optical flow one second?

**Comment by yjxiong** [comment]
For the dependencies, there is no need to install them once they already present. Building OpenCV itself won't affect system-wide dependency.

Again, optical flow is extracted from each pair of consecutive frames.

**Comment by yjxiong** [comment]
@liu666666 , did you manage to build TSN?

**Comment by liu666666** [comment]
I Disabled  cuDNN and make TSN successfully, but when i use the scripts(eval_net.py) to eval a video,i meet a bug which says than no module name pyActionRecog. i did not fix it now and can you tell me how?Thanks for your guidance!

**Comment by yjxiong** [comment]
Try add `.` to your PYTHONPATH variable.
