### ISSUE TITLE
Compile error. Does the code  not support cuda8 cudnn5?

### ISSUE THREAD

**Issue by wanghxcis** [yjxiong/temporal-segment-networks#140]
/home/whx/ml/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

/home/whx/ml/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

/home/whx/ml/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

/home/whx/ml/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

/home/whx/ml/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

/home/whx/ml/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

/home/whx/ml/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_00003563_00000000-5_sigmoid_layer.cpp4.ii".
/home/whx/ml/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

**Comment by wanghxcis** [comment]
Btw, when I disabled cudnn, the compilation passed

**Comment by yjxiong** [comment]
If you have problem with cuDNN v5, you may try using the commit `b0655854919f12812e40cdae4dace20b1536010d` of the caffe-action submodule.

**Comment by wanghxcis** [comment]
Thanks for your help.
