### ISSUE TITLE
Visualize video test results

### ISSUE THREAD

**Issue by chaobeiying** [yjxiong/temporal-segment-networks#141]
Hi，
Thanks your great work!
but I want to know how to get the visualization video test results rather than a number of resutl.

**Comment by yjxiong** [comment]
I cannot understand what you want. Would please make it more clear?

**Comment by junfengluo** [comment]
Maybe he want to get the classification result of a given video, not the test result on the whole data. In this way, no need to write a dataset parser if he want to test a custom dataset.

**Comment by Tonyfy** [comment]
Simplely change the tools/eval_net.py could implemente a testing demo, such as classify only one video.

**Comment by junfengluo** [comment]
Yes, you are right.

**Comment by chaobeiying** [comment]
您好！
我想表达的是，我输入一段视频，然后识别里边的行为分别属于哪一类，给我一个可视化的结果。
就像这个http://vlg.cs.dartmouth.edu/c3d/里边给的视频样例一样。可以实现吗？
谢谢您！

**Comment by yjxiong** [comment]
我们不提供制作demo视频的服务。你可以用每帧的分类结果自行制作。
