### ISSUE TITLE
Clarifai and GoogLeNet models trained on UCF101 split 1

### ISSUE THREAD

**Issue by zhujiagang** [yjxiong/temporal-segment-networks#142]
Have you released VGG-16, Clarifai and GoogLeNet TSN models (.caffemodel) trained on UCF101 split 1? Or your former work "Towards Good Practices for Very Deep Two-Stream ConvNets", Clarifai and GoogLeNet two stream models on UCF101?

**Comment by yjxiong** [comment]
We did not report the performance of TSN with the architectures you mentioned in the paper. They are compared only in the single segment case. You can try them out with TSN if you need the performance numbers.
