### ISSUE TITLE
损失函数基本不变

### ISSUE THREAD

**Issue by jackyCold** [yjxiong/temporal-segment-networks#143]
熊老师：
您好！我是一个新人，本来想利用下载的代码进行训练，初始权值也是下载的，但是训练过程中损失函数基本保持不变，都是在loss=4.6上下波动，想问哈这是什么原因？怎么解决？
修改的参数：batch_size=1，gpu=1，是因为这个修改导致的原因吗

**Comment by junfengluo** [comment]
batch_size 太小了吧

**Comment by jackyCold** [comment]
@junfengluo    我也觉得是我batch_size太小了，您能确定我的结果是因为batch_size导致的吗？ 我是新手

**Comment by yonghenglh6** [comment]
batch_size太小会导致batch_norm层完全不能正常运作。  建议至少8以上

**Comment by jackyCold** [comment]
@junfengluo  好的，明白了！谢谢您

**Comment by AlanZhang1995** [comment]
@jackyCold  您好，我目前也想用这个网络跑一些测试，但是运行scripts/get_reference_models.sh的时候，链接服务器总是失败，不知道您那里是否有下载好的reference model么，可以给我分享一份么。我看到issue里有跟我遇到同样问题的人，但是作者还没有给予回答。（我也是新人，不知道这样要model是不是违规。如果违规的话请麻烦各位大大告诉我一下）

**Comment by jackyCold** [comment]
@AlanZhang1995   您给我留一个邮箱吧，我私下发给你

**Comment by AlanZhang1995** [comment]
@jackyCold 谢谢您，我邮箱2587409293@qq.com

**Comment by yjxiong** [comment]
Please follow the instructions on training your models. Do not change the parameters when you are unclear about what you are doing.
