### ISSUE TITLE
what's the dataset structure

### ISSUE THREAD

**Issue by cmhungsteve** [yjxiong/temporal-segment-networks#144]
I already extract the video frames for HMDB51, and I wanted to use `build_file_list.sh` to generate the list of training/validation. However, it seems that the code can't find the images. My structure is as follows:

```

brush_hair/
......video 1/
............img_0001.jpg
............img_0002.jpg
............img_0003.jpg
            ......
......video 2/
......video 3/
      ......
cartwheel/
catch/
......

```
Is this structure wrong? If so, how should I modify it? Thank you.

**Comment by yjxiong** [comment]
Videos should be put under a root directory. Each video has its own directory with all extracted frames in it. The folder names should be the video IDs.

For example 
```
UC101_videos/
....v_ApplyEyeMakeup_g01_c01/
........img_00001.jpg
........img_00002.jpg
...
........x_00001.jpg
...
........y_00001.jpg
```

For video IDs, see the split files such as

https://github.com/yjxiong/temporal-segment-networks/blob/master/data/ucf101_splits/trainlist02.txt

I do recommend using the provided tools to extract frames and optical flow.

**Comment by surajkothawade** [comment]
What about untrimmed video data sets like Activity Net?
We have multiple activities in each video and the code in `build_file_list.sh` does not seem to read the time points. Also the video names in the extracted frame folder are without the segment number. eg: 4k-F7EXpcrM**_0** whereas the video name in the folder is 4k-F7EXpcrM.
See: https://github.com/yjxiong/temporal-segment-networks/blob/master/pyActionRecog/benchmark_db.py#L48
