### ISSUE TITLE
Problem in getting reference models

### ISSUE THREAD

**Issue by entalent** [yjxiong/temporal-segment-networks#145]
We wanted to use the models pre-trained on UCF101 and HMDB51 for testing, but when executing command
`
bash scripts/get_reference_models.sh
`
as mentioned by readme, there is such output:
```
--2017-10-20 09:27:28--  http://mmlab.siat.ac.cn/tsn_model/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel.v5
Resolving mmlab.siat.ac.cn (mmlab.siat.ac.cn)... 210.75.252.74
Connecting to mmlab.siat.ac.cn (mmlab.siat.ac.cn)|210.75.252.74|:80... failed: Connection timed out.
Retrying.

--2017-10-20 09:28:33--  (try: 2)  http://mmlab.siat.ac.cn/tsn_model/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel.v5
Connecting to mmlab.siat.ac.cn (mmlab.siat.ac.cn)|210.75.252.74|:80... failed: Connection timed out.
Retrying.
```
The wget always get a timeout, and we then found that the domain name 'mmlab.siat.ac.cn' seems no longer accessible now. Is there any other place where these pretrained model could be downloaded?

**Comment by apockill** [comment]
I'm also having this issue

**Comment by AlanZhang1995** [comment]
I'm also having this issue :(

**Comment by wanglimin** [comment]
There is a problem with our server. Please stay tuned.

**Comment by minhtriet** [comment]
I have these models in my machine, is it allowed to upload them somewhere and put the link here?

**Comment by wanglimin** [comment]
@minhtriet Sure, you are welcome to upload these models and put the links here.

**Comment by minhtriet** [comment]
The models are [here](https://drive.google.com/drive/folders/0B5W8J-bvn8J1bDA3cGl2WFk1VWM?usp=sharing)

**Comment by yjxiong** [comment]
I have relocated all the reference models to my Azure storage, which is accessible worldwide. Please update the codebase to receive the change. 

Sorry for the inconvenience caused by instability of our servers.
