### ISSUE TITLE
process always get killed 

### ISSUE THREAD

**Issue by dmorin1** [yjxiong/temporal-segment-networks#146]
After starting inference using:
python tools/eval_net.py ucf101 1 rgb optical_flow/ models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel.v5 --num_worker 1 --save_scores scores.txt

I always get this: 
...
I1021 17:13:52.403010 28260 layer_factory.hpp:74] Creating layer inception_5a/1x1
I1021 17:13:52.403050 28260 net.cpp:99] Creating Layer inception_5a/1x1
I1021 17:13:52.403066 28260 net.cpp:479] inception_5a/1x1 <- inception_4e/output_inception_4e/output_0_split_0
I1021 17:13:52.403082 28260 net.cpp:130] This layer is inheriting previous layer's sync mode: 1
I1021 17:13:52.403105 28260 net.cpp:435] inception_5a/1x1 -> inception_5a/1x1
I1021 17:13:52.403129 28260 net.cpp:163] Setting up inception_5a/1x1
Killed

Any insight in what could be the problem?

Thank you.

**Comment by dmorin1** [comment]
Sometime instead of process killed during initialization I get:
================
I1023 13:22:59.307379 23445 net.cpp:244] inception_3a/relu_double_3x3_reduce does not need backward computation.
I1023 13:22:59.307391 23445 net.cpp:244] inception_3a/double_3x3_reduce_bn does not need backward computation.
I1023 13:22:59.307404 23445 net.cpp:244] inception_3a/double_3x3_reduce does not need backward computation.
I1023 13:22:59.307416 23445 net.cpp:244] inception_3a/relu_3x3 does not need backward computation.
I1023 13:22:59.307428 23445 net.cpp:244] inception_3a/3x3_bn does not need backward computation.
I1023 13:22:59.307440 23445 net.cpp:244] inception_3a/3x3 does not need backward computation.
I1023 13:22:59.307452 23445 net.cpp:244] inception_3a/relu_3x3_reduce does not need backward computation.
I1023 13:22:59.307464 23445 net.cpp:244] inception_3a/3x3_reduce_bn does not need backward computation.
I1023 13:22:59.307478 23445 net.cpp:244] inception_3a/3x3_reduce does not need backward computation.
I1023 13:22:59.307492 23445 net.cpp:244] inception_3a/relu_1x1 does not need backward computation.
I1023 13:22:59.307503 23445 net.cpp:244] inception_3a/1x1_bn does not need backward computation.
I1023 13:22:59.307514 23445 net.cpp:244] inception_3a/1x1 does not need backward computation.
I1023 13:22:59.307528 23445 net.cpp:244] pool2/3x3_s2_pool2/3x3_s2_0_split does not need backward computation.
I1023 13:22:59.307540 23445 net.cpp:244] pool2/3x3_s2 does not need backward computation.
I1023 13:22:59.307551 23445 net.cpp:244] conv2/relu_3x3 does not need backward computation.
I1023 13:22:59.307562 23445 net.cpp:244] conv2/3x3_bn does not need backward computation.
I1023 13:22:59.307574 23445 net.cpp:244] conv2/3x3 does not need backward computation.
I1023 13:22:59.307586 23445 net.cpp:244] conv2/relu_3x3_reduce does not need backward computation.
I1023 13:22:59.307596 23445 net.cpp:244] conv2/3x3_reduce_bn does not need backward computation.
I1023 13:22:59.307610 23445 net.cpp:244] conv2/3x3_reduce does not need backward computation.
I1023 13:22:59.307621 23445 net.cpp:244] pool1/3x3_s2 does not need backward computation.
I1023 13:22:59.307632 23445 net.cpp:244] conv1/relu_7x7 does not need backward computation.
I1023 13:22:59.307643 23445 net.cpp:244] conv1/7x7_s2_bn does not need backward computation.
I1023 13:22:59.307656 23445 net.cpp:244] conv1/7x7_s2 does not need backward computation.
I1023 13:22:59.307665 23445 net.cpp:285] This network produces output fc-action
I1023 13:22:59.308123 23445 net.cpp:551] Collecting Learning Rate and Weight Decay.
I1023 13:22:59.308231 23445 net.cpp:300] Network initialization done.
I1023 13:22:59.308249 23445 net.cpp:301] Memory required for data: 74005652
Traceback (most recent call last):
  File "tools/eval_net.py", line 119, in <module>
    video_scores = map(eval_video, eval_video_list)
  File "tools/eval_net.py", line 69, in eval_video
    video_frame_path = f_info[0][vid]
KeyError: 'v_ApplyEyeMakeup_g01_c01'
==============
Could it be that I'm running out of memory?
In which unit is this memory required ?

**Comment by yjxiong** [comment]
If you run out of memory, you can find the kill log in the output of  `dmesg`.

The second error indicates the scripts cannot find the videos. Please check your file paths.

**Comment by dmorin1** [comment]
I'm testing this on NVidia Jetson TX1 board that has limited RAM memory: only 4GB.
@yjxiong has you mention dmesg contain log that I ran out of memory.

More specifically the dmesg log look like this:
 Out of memory: Kill process 2189 (python) score 242 or sacrifice child
[415833.552290] Killed process 2189 (python) total-vm:10266836kB, anon-rss:980208kB, file-rss:5040kB

For the second scenario, file was missing from the frame path.  After modifying testlist01.txt to a smaller dataset. I was successfully able to run the test and have a prediction reported.

Thank you.
