### ISSUE TITLE
Multiprocessing error when running build_of.py

### ISSUE THREAD

**Issue by JacobKong** [yjxiong/temporal-segment-networks#147]
Thanks for your awesome work! However, after building the dense flow module, when i ran build_of.py to extract optical flow, I got following multiprocessing errors:
`Traceback (most recent call last):
  File "tools/build_of.py", line 140, in <module>
    pool.map(run_optical_flow, zip(vid_list, xrange(len(vid_list))))
  File "/home/jk/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/jk/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
EOFError: EOF when reading a line`
How can I resolve this problem. Looking forward to your reply!
Thank you!

**Comment by yjxiong** [comment]
I am not sure what is wrong. The erroring code line could be

https://github.com/python/cpython/blob/master/Lib/multiprocessing/pool.py#L657

Seems the apply has failed for some reason. I didn't meet this before and cannot identify it with no context information. Perhaps you can try running it again and provide more information for us to help you.

**Comment by JacobKong** [comment]
Thanks for your reply. I have solved this problem. Maybe by changing the
python library, but I am not quite sure!

yjxiong <notifications@github.com>于2017年10月24日周二 上午6:58写道：

**Comment by yjxiong** [comment]
Good to know you have solved the problem. Good luck!

**Comment by Austin997** [comment]
Hi there,
I came cross the similar problem when I use the following command:

python tools/eval_net.py ucf101 1 rgb out-folder \models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel \--num_worker 4 --save_scores score

The error is:
Traceback (most recent call last):
  File "tools/eval_net.py", line 124, in <module>
    video_scores = pool.map(eval_video, eval_video_list)
  File "/home/vision2/anaconda2/envs/tsnv2o/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/vision2/anaconda2/envs/tsnv2o/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
KeyError: 'v_ApplyEyeMakeup_g01_c01'

Does someone know how to solve the problem? Thanks in advance.

**Comment by yjxiong** [comment]
@Austin997 is your `out-folder` containg the extracted frames?

**Comment by Austin997** [comment]
@yjxiong Yes, and it shows frame folder analysis done in the terminal

**Comment by yjxiong** [comment]
Is it shown the number of videos analyzed? It should be around 13000 for UCF101. If you see 0 video then the folder structure could be incorrect.

**Comment by Austin997** [comment]
@yjxiong  Sorry for replying so late. It seems that the folder contains the frames of HMDB51. I re-extract the frames of UCF101 and it works well now. Thanks for your quick reply!

**Comment by yjxiong** [comment]
Cool. Enjoy!
