### ISSUE TITLE
Testing Single Video

### ISSUE THREAD

**Issue by praneetha111** [yjxiong/temporal-segment-networks#15]
Hi,

In the testing description for Temporal Segment Networks it is mentioned that there is a facility to analyze single video.

"For the benchmark datasets, we will measure average accuracy on the testing splits. We also provide the facility to analyze a single video." 

Could you please tell me how I should go about analyzing a single video? Can I use the same eval_net.py script for this purpose?

Thanks!

**Comment by yjxiong** [comment]
Single video testing is going to be released later this week.

**Comment by praneetha111** [comment]
Okay Thanks. I wrote a script to test single video to use it till then.

Thanks!

**Comment by GBJim** [comment]
Hi @yjxiong 
I found the single video testing scripts in Matlab.
Are there Python version of single video testing scripts?
