### ISSUE TITLE
extacting optical flow,but return zero...

### ISSUE THREAD

**Issue by shanYanGuan** [yjxiong/temporal-segment-networks#150]
I run this commond:
`sh scripts/extract_optical_flow.sh /media/server/data1/gsy/tsn/videos/brush_hair/ /media/server/data1/gsy/tsn/out/ 1`

Bur out folder is blank...terminal just show those information
```
Extracting optical flow from videos in folder: /media/server/data1/gsy/tsn/videos/brush_hair/
0
```
what's wrong?

**Comment by shanYanGuan** [comment]
I have figured it out... no need to add'/'     naive question,sorry>_<

**Comment by Koping** [comment]
hi,shanYanGuan! my out folder is also blank, it will create all the folder about the vedio, however it contains nothing. 
my commond is 
sh scripts/extract_optical_flow.sh  /media/koping/tsn/videos /media/koping/tsn/out/ 1

**Comment by shanYanGuan** [comment]
try this : sh scripts/extract_optical_flow.sh /media/koping/tsn/videos
/media/koping/tsn/out 1

2017-11-07 20:48 GMT+08:00 Koping <notifications@github.com>:

**Comment by wangwen1995** [comment]
hi,shanyanGuan,i also have the problem and i tried the solution you have menthioned above,but it dosenot work!just like this:
$ sh scripts/extract_optical_flow.sh data/UCF-101 data/flow_ucf101 1
Extracting optical flow from videos in folder: data/UCF-101
0

**Comment by ASMIftekhar** [comment]
Hey @wangwen39  did you find the solution?
