### ISSUE TITLE
Reproducing results on Kinetics Dataset using inception V3

### ISSUE THREAD

**Issue by hugorichard** [yjxiong/temporal-segment-networks#151]
Hi, Xiong
I cannot reproduce your results on the kinetics data set using inception v3 network and weights. I obtain 
56% accuracy with RGB images
42% accuracy with flow images 
58% accuracy using average of both scores.

Here is the procedure I use:
- Download Kinetics Validation set
- Download Kinetics weights from http://yjxiong.me/others/kinetics_action/
- Load weights using  CaffeNet(proto, model, 0)
- Compute flow using dense_flow
- Take 25 "equidistant" frames from the video and for each frame take 5 following "xflows" and "yflow" frames
- Process the data using net_rgb.predict_single_frame([frame,], "fc_action", frame_size=(452, 341))) for frames and net_flow.predict_single_flow_stack(flow_stack, "fc_action", frame_size=(452, 341)) for flows where a flow stack is the concatenation of x and y flows: [flow_x1, flow_y1, flow_x2, flow_y2,...]
- The flow and rgb scores are obtained using the "default_aggregated_function" (which is roughly the mean)

My script was inspired from the code in tools/eval_net.py

There is obviously something I am missing. Do you have any any idea about what could cause the performances to drop ?

Best,
Hugo

**Comment by yjxiong** [comment]
Why not first using eval_net.py? It could be either code issue or data issue.
