### ISSUE TITLE
some issues about the pre-training caffemodel

### ISSUE THREAD

**Issue by KaiJin1995** [yjxiong/temporal-segment-networks#154]
I want to download your pre_training caffemodel,but I found the website http://mmlab.siat.ac.cn can't connect,so it's hard to download the caffemodel ,although  I have the  shadow socks ......   Could you give another website or netdisc address？
Thanks very much!!

**Comment by yjxiong** [comment]
All models have been moved out of that server days ago. Please update your codebase.
