### ISSUE TITLE
Some question about GatherLayer

### ISSUE THREAD

**Issue by KaiJin1995** [yjxiong/temporal-segment-networks#156]
When i use the code in your vgg_16_rgb_train_val_fast.prototxt , there is a layer which name is 'gather' which used to gather data from different GPU .
However,I didn't find the Gather layer in the tsn_bn_inception_rgb_train_val.prototxt,which means that TSN don't gather data from different GPU. 
Could you tell me why don't use gather layer?

**Comment by KaiJin1995** [comment]
Hi,You say that the actual BatchSize=batchsize x num_gpu=32 x 4=128. But if you don't have gather layer,I think the BatchSize is not equal to 128, because we don't combine the database and we only seperate 4 small database to train it . So the actuall BathchSize is only 32. Do you think i am right?

**Comment by yjxiong** [comment]
Gather layer does not affect the effective batchsize. It is not a part of data parallel training. It just helps the system avoid transferring the huge weight parameter matrices of fully connected layers to save communication time.
