### ISSUE TITLE
ImportError: /usr/local/lib/libopencv_imgcodecs.so.3.2: undefined symbol: _ZNK2cv11_InputArray7getMat_Ei

### ISSUE THREAD

**Issue by woshigcy** [yjxiong/temporal-segment-networks#157]
Hi,Thank you for your work first!
when i run the code like below, it makes some mistake, and i didn't how it happened , can you give me some suggestion about this ? Thank you!
 
sudo python2 tools/eval_net.py ucf101 1 rgb /home/zhangtian/UCFOUT/ models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel --num_worker 3 --save_scores score.txt
Namespace(caffe_path='./lib/caffe-action/', dataset='ucf101', flow_x_prefix='flow_x_', flow_y_prefix='flow_y_', frame_path='/home/zhangtian/UCFOUT/', gpus=None, modality='rgb', net_proto='models/ucf101/tsn_bn_inception_rgb_deploy.prototxt', net_weights='models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel', num_frame_per_video=25, num_worker=3, rgb_prefix='img_', save_scores='score.txt', split=1)
Traceback (most recent call last):
  File "tools/eval_net.py", line 38, in <module>
    from pyActionRecog.action_caffe import CaffeNet
  File "./pyActionRecog/action_caffe.py", line 4, in <module>
    import caffe
  File "/home/zhangtian/workspace/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/home/zhangtian/workspace/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
**ImportError: /usr/local/lib/libopencv_imgcodecs.so.3.2: undefined symbol: _ZNK2cv11_InputArray7getMat_Ei**

**Comment by woshigcy** [comment]
是opencv的原因，重新编译opencv，或者在Makefile里指定opencv路径


原始邮件
发件人:humengdoudounotifications@github.com
收件人:yjxiong/temporal-segment-networkstemporal-segment-networks@noreply.github.com
抄送:woshigcygaochunyang@sensoro.com; State changestate_change@noreply.github.com
发送时间:2018年1月10日(周三) 16:51
主题:Re: [yjxiong/temporal-segment-networks] ImportError:/usr/local/lib/libopencv_imgcodecs.so.3.2: undefined symbol:_ZNK2cv11_InputArray7getMat_Ei (#157)


i face the same problem like yours, mine is libopencv_gpu.so.2.4 undefined symbol, so have you solvered this problem?

**Comment by humengdoudou** [comment]
问题是这样子的，给你看一下，我本来是发在你的anet2016-cuhk下面的：



I build the codebase successfully by running sh build_all.sh，but when running ANET_HOME="/root/caffe_video_end2end" python examples/classify_video.py data/plastering.avi
error happens as fellow：
Traceback (most recent call last):
File "examples/classify_video.py", line 17, in 
from pyActionRec.action_classifier import ActionClassifier
File "/root/caffe_video_end2end/pyActionRec/action_classifier.py", line 3, in 
from action_flow import FlowExtractor
File "/root/caffe_video_end2end/pyActionRec/action_flow.py", line 7, in 
from libpydenseflow import TVL1FlowExtractor
ImportError: /root/caffe_video_end2end/3rd-party/opencv-2.4.13/build/lib/libopencv_gpu.so.2.4: undefined symbol: _ZN2cv3gpu9convertToERKNS0_6GpuMatERS1_ddP11CUstream_st

above says the libopencv_gpu.so.2.4 is an undefined symbol，but in 3rd-party/opencv-2.4.13/build/lib by using ls -l，i can see that：
libopencv_gpu.so -> libopencv_gpu.so.2.4
libopencv_gpu.so.2.4 -> libopencv_gpu.so.2.4.13
libopencv_gpu.so.2.4.13

which means the libopencv_gpu.so.2.4 has already linked to libopencv_gpu.so.2.4.13.

By the way，i have tested your caffe_tsn codebase，the linkage relation is the same like above，but i can run extract features、test、train correctly.

and i also compile the anet2016-cuhk code by using the caffe_tsn build_all.sh, the linkage relation also shows libopencv_gpu.so.2.4 has already linked to libopencv_gpu.so.2.4.13. but it still shows the above bug.










因为我是直接使用build_all.sh编译的，没有使用opencv的makefile，刚重新把opencv全删了编译了下，还是不行。

想问下，如果在Makefile里面指定路径的话，具体是哪个Makefile，opencv/build的makefile还是caffe-action的makefile？

谢谢



****************************************************************************
胡孟


手机：17858610726
邮箱：humengnju@sina.com    humeng19890726@126.com
****************************************************************************
在2018年1月10日 17:00，woshigcy<notifications@github.com> 写道：
是opencv的原因，重新编译opencv，或者在Makefile里指定opencv路径


原始邮件
发件人:humengdoudounotifications@github.com
收件人:yjxiong/temporal-segment-networkstemporal-segment-networks@noreply.github.com
抄送:woshigcygaochunyang@sensoro.com; State changestate_change@noreply.github.com
发送时间:2018年1月10日(周三) 16:51
主题:Re: [yjxiong/temporal-segment-networks] ImportError:/usr/local/lib/libopencv_imgcodecs.so.3.2: undefined symbol:_ZNK2cv11_InputArray7getMat_Ei (#157)


i face the same problem like yours, mine is libopencv_gpu.so.2.4 undefined symbol, so have you solvered this problem?
