### ISSUE TITLE
Did you evaluate the performance of ResNet?

### ISSUE THREAD

**Issue by xlliuplus7** [yjxiong/temporal-segment-networks#16]
I notice that you compare the performance  of different CNN architectures, among which BN-inception achieves best accuracy. Did you try the residual networks? Can it bring better performance with other setting consistent?
Thank you in advance.

**Comment by wanglimin** [comment]
Hi, we did not try ResNet before and you could try it by yourself. I guess it could bring some improvement.

**Comment by yjxiong** [comment]
ResNet is, of course, a good architecture to go. I encourage you to try it out under TSN. And we will be happy to know the results.
