### ISSUE TITLE
Change the crop_size to 227 and something about data transform

### ISSUE THREAD

**Issue by JiqiangZhou** [yjxiong/temporal-segment-networks#163]
hi,
I met an error when I change the crop_size from 224 to 227 , my input UCF101 rgb image is 320*240

Can you tell me if the data processing procedure is as follow:
    Load an image and then crop it with random heght and width( the width and height of cropped regions are randomly selected from {256; 224; 192; 168g}, and then resize it to 224.

But when I change crop_size from 224 to 227 ,an error occured:
     **data_transformer.cpp:490] Check failed: height <= datum_height (227 vs. 226)**

Thank you so much!

**Comment by JiqiangZhou** [comment]
I solved this problem.
All frames have a size of 320x240, except for 4 videos:
v_PommelHorse_g05_c01
v_PommelHorse_g05_c02
v_PommelHorse_g05_c03
v_PommelHorse_g05_c04
Those videos have a size of 400x226.

Thank you!

**Comment by JiqiangZhou** [comment]
So I want to know why you check the size of network input and the video's size, because in the paper:these cropped regions will be resized to 224 × 224 for network training. So the network's input can be set to any size. I can't understand this CHECK's meaning. 

following code is in data_transformer.cpp around 490 lines:
     CHECK_LE(height, datum_height);
     CHECK_LE(width, datum_width);

Thank you

**Comment by yjxiong** [comment]
This check is for the general cases where scale augmentation is not used. If you do not want it in your use cases, you can manually lift.
