### ISSUE TITLE
error in Trainning net with optical flow images

### ISSUE THREAD

**Issue by caibing123** [yjxiong/temporal-segment-networks#166]
hi, i use optical flow images to train net, it cause a problem.
the problem is shown:
I1208 17:04:47.734378 19977 video_data_layer.cpp:50] A total of 0 videos.
*** Aborted at 1512723887 (unix time) try "date -d @1512723887" if you are using GNU date ***
PC: @     0x7f6ea84dfaad caffe::VideoDataLayer<>::DataLayerSetUp()
*** SIGSEGV (@0x0) received by PID 19977 (TID 0x7f6ea8b86a80) from PID 0; stack trace: ***
    @     0x7f6ea6d114b0 (unknown)
    @     0x7f6ea84dfaad caffe::VideoDataLayer<>::DataLayerSetUp()
    @     0x7f6ea8512003 caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7f6ea85cb3de caffe::Net<>::Init()
    @     0x7f6ea85cd2d5 caffe::Net<>::Net()
    @     0x7f6ea85e5e1a caffe::Solver<>::InitTestNets()
    @     0x7f6ea85e6686 caffe::Solver<>::Init()
    @     0x7f6ea85e6846 caffe::Solver<>::Solver()
    @           0x412f30 caffe::GetSolver<>()
    @           0x409a62 train()
    @           0x4071b0 main
    @     0x7f6ea6cfc830 __libc_start_main
    @           0x4076e9 _start
    @                0x0 (unknown)
--------------------------------------------------------------------------
mpirun noticed that process rank 3 with PID 0 on node caibing exited on signal 1

**Comment by yjxiong** [comment]
`A total of 0 videos`

check you video list file.
