### ISSUE TITLE
fine-tuning flow network gets error on shape mismatch

### ISSUE THREAD

**Issue by IchBinYanZhang** [yjxiong/temporal-segment-networks#169]
Dear authors,
I encountered the following errors when I tried to fine-tune the ucf101_split_1_tsn_flow_reference_bn_inception.caffemodel

No matter whether I set the (new_width, new_height) to resize my video resolution, I got the following error:

 Finetuning from models/ucf101_split_1_tsn_flow_reference_bn_inception.caffemodel
F1215 23:22:25.634358 19469 blob.cpp:481] Check failed: ShapeEquals(proto) shape mismatch (reshape not set)
*** Check failure stack trace: ***
    @     0x7fb1a7d035ad  google::LogMessage::Fail()
    @     0x7fb1a7d05413  google::LogMessage::SendToLog()
    @     0x7fb1a7d0313b  google::LogMessage::Flush()
    @     0x7fb1a7d05dfe  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb1a80d49f7  caffe::Blob<>::FromProto()
    @     0x7fb1a8084b5d  caffe::Net<>::CopyTrainedLayersFrom()
    @     0x7fb1a80924f5  caffe::Net<>::CopyTrainedLayersFrom()
    @     0x56204cb3dc8e  CopyLayers()
    @     0x56204cb3e1f8  train()
    @     0x56204cb3b02b  main
    @     0x7fb1a6bfa3f1  __libc_start_main
    @     0x56204cb3b5fa  _start
    @              (nil)  (unknown)
Setting device 0

How should I fix this problem? 

I am highly looking forward to your reply!
Thank you very much!

Cheers,
Yan

**Comment by IchBinYanZhang** [comment]
There was a typo on the new layers. Fix it and everything goes well. This issue can be closed. Thank you!

**Comment by yjxiong** [comment]
Closing this. Please feel free to reopen it if you meet any further problem.
