### ISSUE TITLE
I want to make a real-time demo with TSN

### ISSUE THREAD

**Issue by vmaxxwuxiaomin** [yjxiong/temporal-segment-networks#170]
@yjxiong @fetorres @vra 
Hi,
I want to make a real-time demo with this code. But I have a big problem! Our webcam can track and crop more than 1 people in the video, does this network can deal with multi-input in the same time (multiple cropped persons do the same or different actions in the same time)? And give the corresponding output in a short time?
Thank you!

**Comment by yjxiong** [comment]
It depends on how you implement it. Basically, TSN models take video frames as input and produce action labels. So the question is how you will put this fact in your use case. 

In terms of runtime, it should run at around 15FPS on modern GPUs (TitanX, etc).
