### ISSUE TITLE
error when extract optical flow

### ISSUE THREAD

**Issue by SongKAY** [yjxiong/temporal-segment-networks#171]
Hi!
When I try this:
`bash scripts/extract_optical_flow.sh SRC_FOLDER OUT_FOLDER NUM_WORKER`
It only output one line 
`Extracting optical flow from videos in folder: /data1/sxm/Thumos14/thumos2014/frame/videos/videos`
Then nothing happened and I haven't got any images or optical flows in my OUT_FOLDER...
I wonder why..Is there anybody face the same problem???

**Comment by yjxiong** [comment]
Not sure what is the problem. Have succeeded in building DenseFlow?

**Comment by a258sa258s** [comment]
same question
use build_all.sh build all finish
but denseflow 
./extract_gpu -f test.avi -x tmp/flow_x -y tmp/flow_y -i tmp/image -b 20 -t 1 -d 0 -s 1 -o dir
fail 
error message : 
FATAL [default] CRASH HANDLED; Application has crashed due to [SIGSEGV] signal
WARN  [default] Aborting application. Reason: Fatal log at [temporal-segment-networks/lib/dense_flow/include/easylogging++/src/easylogging++.h:5583] 已經終止 (core dumped)

**Comment by a258sa258s** [comment]
我找到原因了!!!
因為我python預設是python3,但TSN我使用2來建置.
所以把extract_optical_flow.sh內的第八行python改成python3即可
//
solution:
because build TSN use python2 but anaconda default is python3
so,let extract_optical_flow.sh line 8 python become python2
work!

**Comment by SongKAY** [comment]
我也找到原因了..好像是因为我提取的frame和flow的文件名不正确....

**Comment by Rizhiy** [comment]
I am experiencing the same problem. I'm already using python2 in a virtual environment, any idea how to fix?

**Comment by badstones** [comment]
chek the output folder is correct, the error would be fixed

**Comment by Ivy-blooming** [comment]
> chek the output folder is correct, the error would be fixed
@badstones I think my output folder is correct，but I also want to know the path how to set

**Comment by VSunN** [comment]
I also encountered this problem, but this problem is randomly appearing during the extraction process. What's the problem?

**Comment by desti-nation** [comment]
> 我也找到原因了..好像是因为我提取的frame和flow的文件名不正确....

请问文件名如何设置？能不能举个例子

**Comment by liuglen** [comment]
@badstones  @SongKAY What's the correct output folder name?

**Comment by Robinxin123** [comment]
请教下，有人遇到过local/errors.log: data or file not found 这个问题吗？
anybody got the problem "local/errors.log: data or file not found" ?

**Comment by nanhui69** [comment]
> Not sure what is the problem. Have succeeded in building DenseFlow?

@a258sa258s 你的问题解决了么？

> 我也找到原因了..好像是因为我提取的frame和flow的文件名不正确....

**Comment by nanhui69** [comment]
@SongKAY  How could you solve that prblem？can you give a example?

**Comment by zhoumumu** [comment]
Here is another fixing. The channels of my videos‘ collection are various, like tiktok, youtube, or phone shooting. And part of the videos got the problem while the others goes well.
I found that there are tiny varainces in the videos' format, such as 'frame/second', 'encoder' and 'tbr' (show them using cmd "ffmpeg -i 'XXX.mp4' "). Problem fixed after I convert them to a more standard format using cmd "ffmpeg -y -i XXX.mp4 -r 30 -strict -2" (-r 30 set f/s=30; -strict -2 keeps the original audio encoder).

**Comment by blowing-wind** [comment]
我遇到了同样的问题，最后发现是磁盘空间满了
