### ISSUE TITLE
Unable to locate package libboost1.55-all-dev

### ISSUE THREAD

**Issue by Autopawn** [yjxiong/temporal-segment-networks#174]
`build_all.sh` script tries to install `libboost1.55-all-dev`.

On ubuntu 16.04 LTS this throws the following errors:

```bash
E: Unable to locate package libboost1.55-all-dev
E: Couldn't find any package by glob 'libboost1.55-all-dev'
E: Couldn't find any package by regex 'libboost1.55-all-dev'
```

A workaround is manually installing.
```bash
sudo apt-get libboost-all-dev
```

**Comment by yjxiong** [comment]
Thanks.

**Comment by Rizhiy** [comment]
Is `libboost1.55` required or can I use `libboost1.58`?

**Comment by yjxiong** [comment]
You can surely use a higher version.

**Comment by anuragreddygv323** [comment]
how to install it manually ?

**Comment by ghost** [comment]
E: Invalid operation libboost-all-dev
 How to resolve ?

Not resolve by above replies

**Comment by nelaturuharsha** [comment]
sudo apt-get install libboost-all-dev

**Comment by dandingol03** [comment]
doesn't work after i install libboost1.58

**Comment by fusesujan** [comment]
> sudo apt-get install libboost1.55-all-dev

[sudo] password for fm-pc-lt-275: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libboost1.55-all-dev
E: Couldn't find any package by glob 'libboost1.55-all-dev'
E: Couldn't find any package by regex 'libboost1.55-all-dev'
