### ISSUE TITLE
Speed of extracting optical flow with GPU

### ISSUE THREAD

**Issue by WillDamon** [yjxiong/temporal-segment-networks#175]
@yjxiong
million of thanks firstly.
Could you please tell me about the speed of extracting optical flow with GPU? My project  is about real-time action recognition, each video of mine is 90 seconds, I do not  know whether the flow model is fast enough for my project(especially the extracting optical flow period). Thank you so much!

**Comment by yjxiong** [comment]
Officially OpenCV says 14FPS. But on latest GPUs, it should be faster than real-time.
