### ISSUE TITLE
Split of train/val/test datasets of HMDB51 and UCF101 

### ISSUE THREAD

**Issue by propaganda12** [yjxiong/temporal-segment-networks#177]
The HMDB51 has 51 classes, and 100 videos are selected for training(70/100 videos) and testing(30/100 videos) of each class, but how to split the training dataset into train and val is not mentioned. Could you tell your split policy of train/val/test datasets for HMDB51 and UCF101.

**Comment by rocksyne** [comment]
According to [abursuc from Github](https://github.com/feichtenhofer/twostreamfusion/issues/14)
The splits correspond to the ones defined by the authors of the UCF 101 dataset. Basically the dataset is split into train and test data three times. The dataset is not so big and this is just a manner to try to see how the models trained on it generalize to various types of the data. You should find out more about it on the UCF 101 web page http://crcv.ucf.edu/data/UCF101.php


[The Train/Test Splits for Action Recognition on UCF101 data set can be downloaded by clicking here.](http://crcv.ucf.edu/data/UCF101/UCF101TrainTestSplits-RecognitionTask.zip)

[The Train/Test Splits for Action Detection on UCF101 data set can be downloaded by clicking here.](http://crcv.ucf.edu/data/UCF101/UCF101TrainTestSplits-DetectionTask.zip)

I hope this helps. If you find the one for HMDB51 please share with me via rockksyne@gmail.com.

**Comment by kedingu** [comment]
The official split train/val of hmdb51 and the dataset are below : https://serre-lab.clps.brown.edu/resource/hmdb-a-large-human-motion-database/#Downloads
