### ISSUE TITLE
Test datasets for HMDB51 and UCF101

### ISSUE THREAD

**Issue by propaganda12** [yjxiong/temporal-segment-networks#178]
Take HMDB51 for example, it has 51 video classes and 6766 videos in total. 70 videos for training and  30 videos for validating for each class during training in your experiment. So in your test stage, what is the testing dataset? The total HMDB51 dataset?

**Comment by yjxiong** [comment]
I assume you are new to this area. Welcome!

The standard splits can be found at the dataset website. One should use these splits to make fair comparisons.
