### ISSUE TITLE
Video-level testing - SCORE_FILE

### ISSUE THREAD

**Issue by Nothgard** [yjxiong/temporal-segment-networks#179]
I try runnig python tools/eval_scores.py SCORE_FILE , but I think the file is not found, any ideas? I read the readme and nothing

Traceback (most recent call last):
  File "tools/eval_scores.py", line 15, in <module>
    score_npz_files = [np.load(x) for x in args.score_files]
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 370, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'SCORE_FILE'

**Comment by yjxiong** [comment]
SCORE_FILE refers to the name of your score file
