### ISSUE TITLE
dense_flow build error

### ISSUE THREAD

**Issue by TimidLion** [yjxiong/temporal-segment-networks#180]
Hi, I'm using nvidia-docker container with CUDA9.0 and cudnn, and builded opencv2.4.13 completely.
When building dense_flow I failed to make with error
```
/usr/bin/ld: cannot find -lopencv_dep_nppial
/usr/bin/ld: cannot find -lopencv_dep_nppicc
/usr/bin/ld: cannot find -lopencv_dep_nppicom
/usr/bin/ld: cannot find -lopencv_dep_nppidei
/usr/bin/ld: cannot find -lopencv_dep_nppif
/usr/bin/ld: cannot find -lopencv_dep_nppig
/usr/bin/ld: cannot find -lopencv_dep_nppim
/usr/bin/ld: cannot find -lopencv_dep_nppist
/usr/bin/ld: cannot find -lopencv_dep_nppisu
/usr/bin/ld: cannot find -lopencv_dep_nppitc
collect2: error: ld returned 1 exit status
CMakeFiles/pydenseflow.dir/build.make:121: recipe for target 'libpydenseflow.so' failed
make[2]: *** [libpydenseflow.so] Error 1
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/pydenseflow.dir/all' failed
make[1]: *** [CMakeFiles/pydenseflow.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
Actually I changed my opencv-2.4.13/cmake files according to
here[https://stackoverflow.com/questions/46584000/cmake-error-variables-are-set-to-notfound]
However, if I don't change the file in opencv, it will have 
```unsupported gpu architecture 'compute_70'```

**Comment by yjxiong** [comment]
This is normal as CUDA9 changes the nppi naming conventions. You can refer to 
https://github.com/yjxiong/anet2016-cuhk/blob/docker_server/build_all.sh#L22
for how to build in a docker of cuda9

**Comment by ArchieGu** [comment]
@yjxiong  I used the patch and I successfully installed the opencv 2.4, but I still got the same error above when compiling the dense flow.
I can't see where the problem is, could you please help me with that?

**Comment by ArchieGu** [comment]
@yjxiong  I followed the instruction to use the patch, I can install the opencv 2.4, but I still get the same problem above.

**Comment by Anton-Velikodnyy** [comment]
@yjxiong  your suggestion did not work.
