### ISSUE TITLE
Extract optical flow with gpu

### ISSUE THREAD

**Issue by haofanwang** [yjxiong/temporal-segment-networks#181]
When run command `bash scripts/extract_optical_flow.sh SRC_FOLDER OUT_FOLDER NUM_WORKER`,is there  a way to select which GPU to use?

**Comment by haofanwang** [comment]
nvm.Closed.

**Comment by zzw1123** [comment]
Hi, could you please share the solution? And what is the meaning of "nvm"?

**Comment by yjxiong** [comment]
@zzw1123 https://stackoverflow.com/questions/39649102/how-do-i-select-which-gpu-to-run-a-job-on

**Comment by zzw1123** [comment]
@yjxiong Thanks for the answer. I am also wondering that if the code can run on CPU in stead of GPU?

**Comment by yjxiong** [comment]
Yes. But it could be slow.

**Comment by zzw1123** [comment]
OK! Thanks a lot for your help!
