### ISSUE TITLE
Cannot use GPU in CPU-only Caffe

### ISSUE THREAD

**Issue by Nothgard** [yjxiong/temporal-segment-networks#182]
Hello, im trying run the next line  "python tools/eval_net.py ucf101 1 rgb FRAME_PATH \
 models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel \
 --num_worker 4 --save_scores SCORE_FILE"

but i have the next error : 

"frame folder analysis done
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0129 18:44:12.782696 30213 common.cpp:99] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
Aborted (core dumped)"

my computer is new, only has the caffe version that you use, and i followed the same steps, and i have this error, my machine dont have CUDA and drivers of my Nvidia card, i need install CUDA or some drivers?

**Comment by yjxiong** [comment]
You are running another installation of Caffe which you compiled to CPU-only mode. Please check your environment settings.

**Comment by YHDang** [comment]
Hello, could you run the CPU-only mode successfully? There is no CUDA on my machine. When I ran the `build_all.sh`, the problem occurred:
`E: Unable to locate package libboost1.55-all-dev`
`E: Couldn't find any package by glob 'libboost1.55-all-dev'`
`E: Couldn't find any package by regex 'libboost1.55-all-dev'`

Can you help me solve this problem?
