### ISSUE TITLE
caffe-action build error

### ISSUE THREAD

**Issue by TedaLIEz** [yjxiong/temporal-segment-networks#183]
I'm building the environment for this repo on Ubuntu 16.04, opencv and dense_flow has been built successfully, but I got an error while building the caffe-action:

> [ 83%] Linking CXX shared library ../../lib/libcaffe.so 
/usr/bin/ld: cannot find -lQt5::Core
/usr/bin/ld: cannot find -lQt5::Gui
/usr/bin/ld: cannot find -lQt5::Widgets
/usr/bin/ld: cannot find -lQt5::Test
/usr/bin/ld: cannot find -lQt5::Concurrent
/usr/bin/ld: cannot find -lQt5::OpenGL
collect2: error: ld returned 1 exit status

How can I solve this issue?

Edit:
I've checked the installation of Qt by:
`qmake --version`

> QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu

**Comment by TedaLIEz** [comment]
I solved this issue. For those who have this issue:
Step 1: check the dependencies:

> sudo apt-get install libqt5concurrent5
sudo apt-get install libqt5test5
sudo apt-get install libqt5core5a
sudo apt-get install libqt5opengl5
sudo apt-get install qtdeclarative5-dev

Step 2: run `ldconfig`

Step 3: add those lines in `CMakeLists.txt` at front:

> find_package(Qt5Gui)
find_package(Qt5Core)
find_package(Qt5Widgets)
find_package(Qt5Test)
find_package(Qt5Concurrent)
find_package(Qt5OpenGL)

I am not sure step 2 & 3 are both needed, but it's worth to give it a try :D
All tools built. Happy experimenting!

**Comment by yjxiong** [comment]
I assume it should not use Qt for dependency. Are you using the `build_all.sh`?

**Comment by TedaLIEz** [comment]
yes, I used your `build_all.sh`. It seems that qt is used in the caffe module. Building `opencv` and `dense_flow` are totally fine.

**Comment by yjxiong** [comment]
Caffe does not use Qt. If it links to them, it may suggest some hidden problem in the dependencies. Anyway, you can proceed with the experiments to see if it works as expected.

**Comment by TedaLIEz** [comment]
OK. I'll head on to the experiments.
