### ISSUE TITLE
Training TSN with single gpu

### ISSUE THREAD

**Issue by TedaLIEz** [yjxiong/temporal-segment-networks#185]
Sadly I've got only one gpu on my machine, but I want to run the training process, the `train_tsn.sh` needs openmpi as a necessity. In this case, should I comment out the `mpirun` command in `train_tsn.sh` and run 

> $TOOLS/caffe train --solver=models/${DATASET}/tsn_bn_inception_${MODALITY}_solver.prototxt  \
>    --weights=models/bn_inception_${MODALITY}_init.caffemodel 2>&1 | tee ${LOG_FILE}

 directly? 

By the way, I didn't run your `build_all.sh` with the flag `MPI_ON`.

**Comment by Philliprince** [comment]
@TedaLIEz Why did you close this issue? Have you successfully trained it at last?
