### ISSUE TITLE
caffe layer type BN in tsn_bn_inception_rgb_deploy.prototxt

### ISSUE THREAD

**Issue by double-vane** [yjxiong/temporal-segment-networks#19]
Hi，Could you tell me where I‘ll ’ find the layer type name of BN?

Is it created by yourself or comes from Official website？

**Comment by double-vane** [comment]
Thank you very much. I found it in the caffe-action\src\caffe\layers.
I'm sorry to bother you always.

**Comment by yjxiong** [comment]
It is in our Caffe repo which comes with TSN, carrying our implementation of Batch Normalization operation. 

To my knowledge the official version of Caffe needs two layers to resemble this operation.
