### ISSUE TITLE
Dense flow installation problem 

### ISSUE THREAD

**Issue by Nandan532189** [yjxiong/temporal-segment-networks#190]
I'm trying to install "dense_flow" on server which has Ubuntu 16.04. 
I'm getting these errors :
#################################################################################
Building Dense Flow
-- Could NOT find LIBZIP (missing:  LIBZIP_LIBRARY LIBZIP_INCLUDE_DIR_ZIP LIBZIP_INCLUDE_DIR_ZIPCONF) 
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   python
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBZIP_INCLUDE_DIR_ZIP
   used as include directory in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow
   used as include directory in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow
   used as include directory in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow
   used as include directory in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow
   used as include directory in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow
LIBZIP_INCLUDE_DIR_ZIPCONF
   used as include directory in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow
   used as include directory in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow
   used as include directory in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow
   used as include directory in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow
   used as include directory in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow
LIBZIP_LIBRARY
    linked by target "extract_cpu" in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow
    linked by target "denseflow" in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow
    linked by target "extract_warp_gpu" in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow
    linked by target "extract_gpu" in directory /home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow

-- Configuring incomplete, errors occurred!
See also "/home/nandan/VisualComputing/temporal-segment-networks/lib/dense_flow/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
Failed to build Dense Flow. Please check the logs above.
#############################################################################
Note: I'm not sudo user on this server. I checked the "libzip" and found this location
libzip.so.2 (libc6,x86-64) => /usr/lib/libzip.so.2

**Comment by ArchieGu** [comment]
How did you solve the problem??

**Comment by Mohamad73** [comment]
anybody solved this problem?
