### ISSUE TITLE
Warp flow reference models

### ISSUE THREAD

**Issue by dougsoares** [yjxiong/temporal-segment-networks#191]
Hi @yjxiong ,

Could you please provide the reference models for warp flow? I noticed that the scripts/get_reference_models.sh only download rgb and flow models.

Thank you so much in advance.

**Comment by kstys** [comment]
Do you come across the error when you install dense flow @dougsoares

**Comment by yjxiong** [comment]
Sorry, we don't provide that. Warp flow is costly to use and provides only marginal accuracy improvements.
