### ISSUE TITLE
install optical flow 

### ISSUE THREAD

**Issue by kstys** [yjxiong/temporal-segment-networks#192]
Hello,I install the dense flow and come across this question about: 

CMakeFiles/extract_warp_gpu.dir/build.make:115: recipe for target 'extract_warp_gpu' failed
make[2]: *** [extract_warp_gpu] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/extract_warp_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_warp_gpu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed

I don't know how to do it .

**Comment by yjxiong** [comment]
This error message is incomplete. Please paste the full compilation log.

**Comment by yjxiong** [comment]
You can use the built docker image. See README
