### ISSUE TITLE
Extracting optical frames

### ISSUE THREAD

**Issue by programmer1997** [yjxiong/temporal-segment-networks#194]
First of all thank you for this research paper

When I issue this command
`bash scripts/extract_optical_flow.sh SRC_FOLDER OUT_FOLDER NUM_WORKER`
Then it prints the video length as 0. It does not detect the videos

**Comment by programmer1997** [comment]
I found the solution
The folder at the path SRC_FOLDER should contain sub  folders which should contain the videos

**Comment by ASMIftekhar** [comment]
Do you mean all the videos in different sub-folders? Like if there are 1000 videos then should I make 1000 separate folders?
