### ISSUE TITLE
Flow image with large step? 

### ISSUE THREAD

**Issue by jayleicn** [yjxiong/temporal-segment-networks#196]
Hi @yjxiong ,

Currently TSN uses flow images extracted with dense_flow step=1. If I want to use the kinetics pretrained model, can I use extract flow images with larger steps e.g. step=10? From my understanding, larger step is fine for RGB stream, but for flow images, the calculation of optical flow will be problematic since every flow image is computed using two neighboring gray images sampled at step=10 instead of 1. Does this make sense? 

If so, any quick idea how to downsample flow images at extraction to save time while keeping the flow calculation correct? Since I got a large number of videos. 

Thanks,
Jie

**Comment by yjxiong** [comment]
I don't think extracting flow with a large stride is a good idea. If you are indeed limited in time, just use RGB diff.

**Comment by yjxiong** [comment]
Anything to consider is if you got a large number of videos *with annotations*, you may not need to use any pretrained models.

**Comment by jayleicn** [comment]
Thanks! Yes, I agree with you it is not a good idea to extract flow with a large stride. 

I only use the pretrained model to extract feature for other usages. So it should be fine for the purpose. I am thinking about extracting flow with step=1, but only do the extraction 3 times every second. For example, if I got a one-second video with its frames indexed as [1, ..., 30], so I could get 3 flow images at [1,2], [11,12] and [21, 22].  Does it sound good to you?

**Comment by yjxiong** [comment]
If you need to extract features, first consider the starting frames of your extraction. For example, you want to start at [0, 10, 20, 30, ...]. TSN's flow model takes five consecutive flow frames as an input. Then you should extract flow between [0, 5], [10, 15], [20, 25] [30, 25],...

**Comment by jayleicn** [comment]
Thanks! Is the dense_flow tool able to do that? It seems to me that the script could only extract at fixed step.

**Comment by yjxiong** [comment]
No for the binary. But you can use its Python binding for that cause

**Comment by jayleicn** [comment]
Do you mean this script? https://github.com/yjxiong/dense_flow/blob/master/build_of.py  It simply calls the binary.

**Comment by jayleicn** [comment]
Thanks for pointing out!
