### ISSUE TITLE
How to extra frames?

### ISSUE THREAD

**Issue by poppingcode** [yjxiong/temporal-segment-networks#197]
i use the temporal-segment-networks/tools/build_of.py,
but i find the function dump_frames is not use . How does it work（extra frames）
thanks!

**Comment by yjxiong** [comment]
The binary will write the files. That’s how it works.

**Comment by poppingcode** [comment]
now，are you wirte in the build_of.py?
thanks

**Comment by cgokce** [comment]
refer to the #211
