### ISSUE TITLE
eval_net.py

### ISSUE THREAD

**Issue by Anguliachao** [yjxiong/temporal-segment-networks#199]
Hello, thank you for the nice repo! However I faced the issue: I run the .sh file exactly in the readme file , however ,when I try to eval_net on hmdb51 dataset, I encounter this problem of caffe, but I already compile the home-brewed-caffe in this paper. Can anyone help me with this ? thanks a lot! @yjxiong @wanglimin 

> root@46640cef050e:/workspace/temporal-segment-networks/lib/caffe-action# cd ../..
root@46640cef050e:/workspace/temporal-segment-networks# python tools/eval_net.py hmdb51 1 rgb output_folder/ models/hmdb51/tsn_bn_inception_rgb_deploy.prototxt models/hmdb51_split_1_tsn_rgb_reference_bn_inception.caffemodel --num_worker 1 --save_scores score.log
Namespace(caffe_path='./lib/caffe-action/', dataset='hmdb51', flow_x_prefix='flow_x_', flow_y_prefix='flow_y_', frame_path='output_folder/', gpus=None, modality='rgb', net_proto='models/hmdb51/tsn_bn_inception_rgb_deploy.prototxt', net_weights='models/hmdb51_split_1_tsn_rgb_reference_bn_inception.caffemodel', num_frame_per_video=25, num_worker=1, rgb_prefix='img_', save_scores='score.log', split=1)
hmdb51
parse frames under folder output_folder/
0 videos parsed
200 videos parsed
400 videos parsed
600 videos parsed
800 videos parsed
1000 videos parsed
1200 videos parsed
1400 videos parsed
1600 videos parsed
1800 videos parsed
2000 videos parsed
2200 videos parsed
2400 videos parsed
2600 videos parsed
2800 videos parsed
3000 videos parsed
3200 videos parsed
3400 videos parsed
3600 videos parsed
3800 videos parsed
4000 videos parsed
4200 videos parsed
4400 videos parsed
4600 videos parsed
4800 videos parsed
5000 videos parsed
5200 videos parsed
5400 videos parsed
5600 videos parsed
5800 videos parsed
6000 videos parsed
6200 videos parsed
6400 videos parsed
6600 videos parsed
frame folder analysis done
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0507 02:38:40.610601 22932 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0507 02:38:40.610621 22932 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0507 02:38:40.610625 22932 _caffe.cpp:142] Net('models/hmdb51/tsn_bn_inception_rgb_deploy.prototxt', 1, weights='models/hmdb51_split_1_tsn_rgb_reference_bn_inception.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 19:12: Message type "caffe.LayerParameter" has no field named "bn_param".
F0507 02:38:40.611668 22932 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/hmdb51/tsn_bn_inception_rgb_deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by Anguliachao** [comment]
I built **Dense_flow** and **Caffe-action** successfully, I checked **caffe.proto** It does have **bn_param** parameter, however when I run this python script , it raise the problem of **No field named 
 bn_param**

**Comment by fetorres** [comment]
You might have another version of caffe on your machine that is being found first.  If that is the case, Issue 168 has one way to solve the problem.

**Comment by Anguliachao** [comment]
hi @fetorres , thank you , may I ask which issue 168 it is ? can you send me a link? I checked bvlc issue168 seems not right

**Comment by fetorres** [comment]
Here it is, sorry:  https://github.com/yjxiong/temporal-segment-networks/issues/168

**Comment by Anguliachao** [comment]
@fetorres Thanks a lot. I figured it out and to make sure the changes takes effect. Add extra two lines to set environment variable

> import sys
sys.path.insert(0,'/path/to/caffe-action')
import os
os.environ['PYTHONPATH'] = 'path/to/caffe-action'

**Comment by fetorres** [comment]
I am glad it is working for you.  If you set the PYTHONPATH environment variable to include '/path/to/cafee-action', the other command should not be necessary.  For my case, I did not want to have PYTHONPATH point to this version of caffe because other python programs used the standard version of Caffe.  

Doing both won't hurt anything for your case, but some people might consider setting an environment variable within a buried .py file to be something one should avoid.  Instead, at the command line use export PYTHONPATH=/path/to/caffe-action:$PYTHONPATH
