### ISSUE TITLE
Construct file lists

### ISSUE THREAD

**Issue by Zhuysheng** [yjxiong/temporal-segment-networks#200]
when i construct file lists use  bash scripts/build_file_list.sh ucf101 /home/z/data/jpegs_256,i meet: 
frame folder analysis done
writing list files for training/testing
Traceback (most recent call last):
  File "tools/build_file_list.py", line 38, in <module>
    lists = build_split_list(split_tp, f_info, i, shuffle)
  File "/home/zhuyisheng/tsn/temporal-segment-networks/pyActionRecog/benchmark_db.py", line 58, in build_split_list
    train_rgb_list, train_flow_list = build_set_list(split[0])
  File "/home/zhuyisheng/tsn/temporal-segment-networks/pyActionRecog/benchmark_db.py", line 48, in build_set_list
    frame_dir = frame_info[0][item[0]]
KeyError: 'v_HandStandPushups_g08_c01

**Comment by Mohamad73** [comment]
Hello, I am getting the same error, how did you solve the problem?

**Comment by sucaohan** [comment]
请问您解决了么，我也有同样的问题

**Comment by zys20172212265** [comment]
@sucaohan 您好，我是由于字母的大小写问题。

**Comment by Jimmy880** [comment]
@zys20172212265 can you be more specific? I used docker to build the file list, but I got the exactly same error.

**Comment by zys20172212265** [comment]
@Jimmy880 For example, it shows KeyError: 'v_HandStandPushups_g08_c01', maybe your folder name is 'v_handStandPushups_g08_c01', 'H' and 'h' is different. It may solve your problem.
