### ISSUE TITLE
Check failed: data_ 

### ISSUE THREAD

**Issue by h-bo** [yjxiong/temporal-segment-networks#204]
Use tsn to extract feature and meet that problem.
Code:

import caffe

test_input = np.array(np.ones((1,299,299,3)), np.float32)
model_path = './inception_v3_kinetics_rgb_pretraine/inception_v3_rgb_deploy.prototxt' 
param_path = './inception_v3_kinetics_rgb_pretraine/inception_v3_kinetics_rgb_pretrained.caffemodel' 
#caffe.set_mode_cpu
net = caffe.Net(model_path, param_path, caffe.TEST)
pdb.set_trace()
net.blobs['data'].data[...] = test_input.transpose([0,3,1,2])
out = net.forward()

Error Log:
[log.txt](https://github.com/yjxiong/temporal-segment-networks/files/2099157/log.txt)

**Comment by yjxiong** [comment]
Where is the error

**Comment by h-bo** [comment]
Updated
Thanks

**Comment by yjxiong** [comment]
Please use the provided script to extract score of features. You can modify the script to extract features.
