### ISSUE TITLE
CMake Error: The source directory "/home/zhaohuaqing/Downloads/temporal-segment-networks-master/lib/dense_flow" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by zhaobaozi** [yjxiong/temporal-segment-networks#205]
HI @yjxiong ,when i do bash ./build.sh i meet"CMake Error: The source directory "/home/zhaohuaqing/Downloads/temporal-segment-networks-master/lib/dense_flow" does not appear to contain CMakeLists.txt.
what should i do?

**Comment by yjxiong** [comment]
Read the README. You should use --recursive with git clone.
