### ISSUE TITLE
error about eval_net.py

### ISSUE THREAD

**Issue by zhaobaozi** [yjxiong/temporal-segment-networks#207]
HI @yjxiong 
when i run python tools/eval_net.py ucf101 1 rgb /home/USER/Downloads/temporal-segment-networks/data/UCF-101  models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel  --num_worker 1 --save_scores aaaa.log
I MEET Traceback (most recent call last):
  File "tools/eval_net.py", line 119, in <module>
    video_scores = map(eval_video, eval_video_list)
  File "tools/eval_net.py", line 69, in eval_video
    video_frame_path = f_info[0][vid]
KeyError: 'v_ApplyEyeMakeup_g08_c01'
What shoulf i do?

**Comment by yjxiong** [comment]
Your video is not found by the system. check your video directore paths.
