### ISSUE TITLE
How the framework store the BN statistics

### ISSUE THREAD

**Issue by h-bo** [yjxiong/temporal-segment-networks#209]
Issue from
https://github.com/yjxiong/action-detection/issues/55

I rewrote tsn model by tensorflow. But when reusing the pretrianed model you support, I found the result worse than expected. I found your BN layer might be a little different from simplily x= (x-mean_x)/var_x*scale + bias. Is that so? If not, can you please have an introduction to your BN layer.
Thanks

There are 4 params for BN layer, and I think the order is scale, offset, mean, variance.

**Comment by yjxiong** [comment]
As I said it is the exact same implementation of the BN paper. The only reason of difference I can think of is that tensorflow has different handling of BN statistics. But I am not able to help you with that.

If you want to use modern frameworks, why not use PyTorch. We have official PyTorch implementation available and tensorflow in not in our plate right now.
