### ISSUE TITLE
about extract_optical_flow.sh

### ISSUE THREAD

**Issue by lianuo** [yjxiong/temporal-segment-networks#211]
Thanks for your works on TSN!

I have a problem on generate data set from original UCF101 videos。
I failed when  run the bash build_all.sh 
but actually  ,I just need the rgb frames.when I run the extract_optical_flow.sh ,no images were generated .
I found the function dump_frames in "tools/build_of.py" is not being called by the main function, is that the reason ?

**Comment by lianuo** [comment]
I modified the build_of.py ,so it can extra rgb now ,thanks~

**Comment by alirezamosh** [comment]
@lianuo Is it possible for you to share the code? I'm trying to do the same thing. Thank you.

**Comment by zzw1123** [comment]
@lianuo Could you please share the modified code? Thanks a lot!

**Comment by cgokce** [comment]
Modified file for only RGB frames:
https://gist.github.com/cgokce/39ac1e617a20ede4471e92549f7430b6
