### ISSUE TITLE
libpng16.so: undefined reference to `inflateValidate'

### ISSUE THREAD

**Issue by juzhitao** [yjxiong/temporal-segment-networks#213]
[ 58%] Linking CXX executable ../../bin/opencv_createsamples
//root/anaconda2/lib/libpng16.so.16：对‘inflateValidate@ZLIB_1.2.9’未定义的引用
collect2: error: ld returned 1 exit status
apps/visualisation/CMakeFiles/opencv_visualisation.dir/build.make:106: recipe for target 'bin/opencv_visualisation' failed
make[2]: *** [bin/opencv_visualisation] Error 1
CMakeFiles/Makefile2:7593: recipe for target 'apps/visualisation/CMakeFiles/opencv_visualisation.dir/all' failed
make[1]: *** [apps/visualisation/CMakeFiles/opencv_visualisation.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
//root/anaconda2/lib/libpng16.so.16：对‘inflateValidate@ZLIB_1.2.9’未定义的引用
collect2: error: ld returned 1 exit status
apps/annotation/CMakeFiles/opencv_annotation.dir/build.make:106: recipe for target 'bin/opencv_annotation' failed
make[2]: *** [bin/opencv_annotation] Error 1
CMakeFiles/Makefile2:7536: recipe for target 'apps/annotation/CMakeFiles/opencv_annotation.dir/all' failed
make[1]: *** [apps/annotation/CMakeFiles/opencv_annotation.dir/all] Error 2
^Cmake[2]: *** Deleting file 'bin/opencv_perf_ocl'
make[2]: *** Deleting file 'bin/opencv_test_legacy'
make[2]: *** Deleting file 'bin/opencv_test_highgui'
make[2]: *** Deleting file 'bin/opencv_perf_calib3d'
make[2]: *** Deleting file 'bin/opencv_perf_objdetect'
make[2]: *** Deleting file 'bin/opencv_test_objdetect'
make[2]: *** Deleting file 'bin/opencv_test_imgproc'
make[2]: *** Deleting file 'bin/opencv_perf_imgproc'
make[2]: *** Deleting file 'bin/opencv_test_photo'
make[2]: *** Deleting file 'bin/opencv_createsamples'
modules/ocl/CMakeFiles/opencv_perf_ocl.dir/build.make:738: recipe for target 'bin/opencv_perf_ocl' failed
make[2]: *** Deleting file 'bin/opencv_traincascade'
make[2]: *** Deleting file 'bin/opencv_haartraining'
make[2]: *** [bin/opencv_perf_ocl] 中断
make[2]: *** Deleting file 'bin/opencv_test_features2d'
make[2]: *** Deleting file 'bin/opencv_test_calib3d'
make[2]: *** Deleting file 'bin/opencv_perf_video'
CMakeFiles/Makefile2:4679: recipe for target 'modules/gpu/CMakeFiles/opencv_gpu.dir/all' failed
make[1]: *** [modules/gpu/CMakeFiles/opencv_gpu.dir/all] 中断
CMakeFiles/Makefile2:5236: recipe for target 'modules/ocl/CMakeFiles/opencv_perf_ocl.dir/all' failed
make[1]: *** [modules/ocl/CMakeFiles/opencv_perf_ocl.dir/all] 中断
modules/objdetect/CMakeFiles/opencv_perf_objdetect.dir/build.make:138: recipe for target 'bin/opencv_perf_objdetect' failed
make[2]: *** [bin/opencv_perf_objdetect] 中断
CMakeFiles/Makefile2:4075: recipe for target 'modules/objdetect/CMakeFiles/opencv_perf_objdetect.dir/all' failed
make[1]: *** [modules/objdetect/CMakeFiles/opencv_perf_objdetect.dir/all] 中断
modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/build.make:657: recipe for target 'bin/opencv_test_calib3d' failed
make[2]: *** [bin/opencv_test_calib3d] 中断
CMakeFiles/Makefile2:2723: recipe for target 'modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/all' failed
make[1]: *** [modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/all] 中断
make[2]: *** Deleting file 'bin/opencv_perf_features2d'
modules/features2d/CMakeFiles/opencv_perf_features2d.dir/build.make:189: recipe for target 'bin/opencv_perf_features2d' failed
modules/calib3d/CMakeFiles/opencv_perf_calib3d.dir/build.make:163: recipe for target 'bin/opencv_perf_calib3d' failed
make[2]: *** [bin/opencv_perf_features2d] 中断
make[2]: *** [bin/opencv_perf_calib3d] 中断

**Comment by yjxiong** [comment]
Not what's the problem here. You may rebuild OpenCV using the provided version. Or simply use the TSN docker.
