### ISSUE TITLE
bash scripts/extract_optical_flow.sh問題

### ISSUE THREAD

**Issue by 124399839** [yjxiong/temporal-segment-networks#214]
Hi yaunjun
Your work is so useful, thank you very much for your open source. I'm trying to run your code, and I have a lot of errors as fllows:

Deep@gpuserver:~/project/temporal-segment-networks$ bash scripts/extract_optical_flow.sh /home/Deep/project/data/hmdb51/videos/videos /home/Deep/project/temporal-segment-networks/opFlow/hmdb51 1
Extracting optical flow from videos in folder: home/Deep/project/compressed_video_AR/pytorch-coviar-master/data/hmdb51/videos/videos
0
Deep@gpuserver:~/project/temporal-segment-networks$

when i excute "bash scripts/get_reference_models.sh",i have get "All tools built. Happy experimenting!"
 can you help me point them out in this code project?
thanks a lot

**Comment by yjxiong** [comment]
Possibly your videos are not put in the right folder structure. The code assume you have the following folder structure
```
root_dir/
    set_0/
        video_0.mp4
        ...
    set_1/
    ...
```
