### ISSUE TITLE
How dos the docker image work?

### ISSUE THREAD

**Issue by hohmannr** [yjxiong/temporal-segment-networks#217]
Hello there and thank you for your excellent research. I would like to use the optical flow calculations for your newer SSN paper. I have installed `docker` and `nvidia-docker` and I do not quite get how the image works:
if I run `nvidia-docker run bitxiong/tsn` the container only last for a second and only starts up ipython. Would you be so kind to explain to me how the optical flow calculation is working?

**Comment by yjxiong** [comment]
You can run `nvidia-docker run -it bitxiong/tsn bash` to enter the terminal of the container.
