### ISSUE TITLE
I am strong interset in TSN! 

### ISSUE THREAD

**Issue by zhangxiaodi** [yjxiong/temporal-segment-networks#22]
i am a green hand in Deep Action Recognition. and i have no any experience in the field. i want to know install caffe if or not need opencv? and what version is it!

**Comment by yjxiong** [comment]
To use TSN, OpenCV is necessary. It is used for both Caffe and DenseFlow. In standard TSN setup, we have provided you with a bundled OpenCV installation with VideoIO support. The version number is 2.4.12.

Please follow the README to install this standard setup of TSN.

https://github.com/yjxiong/temporal-segment-networks#get-the-code

**Comment by yjxiong** [comment]
Hi @zhangxiaodi ,

Any luck with your installation?

**Comment by yjxiong** [comment]
Closing this. Please feel free to reopen it in event of any problem.

**Comment by yjxiong** [comment]
Quoting @zhangxiaodi 
>I want to know that i compile the code of opencv with many "c++ internal compiler error" in my screen? And in file of build_bash. such libboost1.55-all-dev can't install with apt-get ? may you give me some advice?

Any boost library with a version number higher than 1.54 will be OK. 
I don't have an idea of what is happening with your OpenCV compilation. If you have your own version of OpenCV with VideoIO support, you can use it instead.

**Comment by zhangxiaodi** [comment]
Thank you for your answer!  I have finished installation of this project with your help.  Q1: When i running  ./extract_cpu -f test.avi -x ./tmp/flow_x -y ./tmp/flow_y -i ./tmp/image -b 20 -t 1 -d 0 -s 1 -o ./znb  (PS:tmp and znb is existed). i find flow_x.zip, flow_y.zip, image.zip in tmp and znb  folder have nothing in it.Q2:cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_TBB=ON  -D WITH_V4L=ON .. when i compiling opencv 2.4.12 in vmware,the compilation process can't through. Then I have accomplished compilation process when i set WITH_V4L=OFF. I don't know whether i will under the influence of it. can you give me some advice? and i just begin study this field of action recognition.  so i want to know your code and i am think your propose method is good ideal.    




------------------ 原始邮件 ------------------
发件人: "yjxiong";<notifications@github.com>;
发送时间: 2016年10月22日(星期六) 下午2:23
收件人: "yjxiong/temporal-segment-networks"<temporal-segment-networks@noreply.github.com>; 
抄送: "难得~吐槽"<2629699385@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [yjxiong/temporal-segment-networks] I am strong interset in TSN!(#22)




Quoting @zhangxiaodi 
  
I want to know that i compile the code of opencv with many "c++ internal compiler error" in my screen? And in file of build_bash. such libboost1.55-all-dev can't install with apt-get ? may you give me some advice?
  
Any boost library with a version number higher than 1.54 will be OK. 
 I don't have an idea of what is happening with your OpenCV compilation. If you have your own version of OpenCV with VideoIO support, you can use it instead.

**Comment by yjxiong** [comment]
Please do not use `extract_cpu`. Instead, please stick with the `extract_gpu` tool.

To run it, you may need a GPU and not compile the OpenCV code on the virtual machine.
