### ISSUE TITLE
about Dokcer environment

### ISSUE THREAD

**Issue by Ai-is-light** [yjxiong/temporal-segment-networks#221]
@yjxiong 
Thanks for your excellent repo.  And I got the docker from https://hub.docker.com/r/bitxiong/tsn/tags/
after running this docker, I run the build_all.sh for building the caffe environment. Then, I got the following information:

Caffe Built.
All tools built. Happy experimenting!
root@970d81b70d6b:/app# python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import caffe
Traceback (most recent call last):
  File stdin, line 1, in <module>
ImportError: No module named caffe

So, would you mind giving me some advice, I'm not familiar with caffe.
Looking forward to any replies.

**Comment by lqzhao** [comment]
run build_all.sh, then you can import caffe

**Comment by umangbhatia** [comment]
I am facing the same problem. How did you solve it?

**Comment by DunaiFuentes** [comment]
Same here. Any solutions?

**Comment by DunaiFuentes** [comment]
Seems it just needs to be added to the path. OpenCV too.
```
export PYTHONPATH=/app/lib/caffe-action/python:${PYTHONPATH}
export PYTHONPATH=/app:${PYTHONPATH}
```
