### ISSUE TITLE
about multi-GPUs training and more details about the MPI/mpirun

### ISSUE THREAD

**Issue by Ai-is-light** [yjxiong/temporal-segment-networks#222]
@yjxiong Thanks for your excellent repo and code.
my run.sh
mkdir -p snapshots
mkdir -p training

N_GPU=4
MPI_BIN_DIR= #/usr/local/openmpi/bin/
TOOLS=/app/lib/caffe-action/build/tools
${MPI_BIN_DIR}mpirun -np $N_GPU \
HDF5_DISABLE_VERSION_CHECK=1 \
$TOOLS/caffe train  --solver=solver.prototxt --weights=../../xxx.caffemodel, 2>&1 | tee -a training/log.txt

My question is how to set the different number of gpus to train the model. Although, I set the N_GPU=4, there is only the GPU=0 working. So, how do I set the different number of GPUs, like setting GPUs=4,5,6,7.
And I also setting the GPU number like $TOOLS/caffe train  --gpu=0,1,2,3 --solver=solver.prototxt --weights=../../xxx.caffemodel, 2>&1 | tee -a training/log.txt, but it not work and got ERROR: illegal value '1,2' specified for int32 flag 'gpu', it's really odd. When $TOOLS/caffe train  --gpu=3 --solver=solver.prototxt --weights=../../xxx.caffemodel, 2>&1 | tee -a training/log.txt, I can work
And, there is a big problem to me, the folder of /usr/local/openmpi/bin/ is not existing, I don't why. Because I build the docker with
MPI_PREFIX=<root path to openmpi installation> bash build_all.sh MPI_ON.
Finally, I always get the following information，

mpirun has detected an attempt to run as root.
Running at root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

You can override this protection by adding the --allow-run-as-root
option to your cmd line. However, we reiterate our strong advice
against doing so - please do so at your own risk.

what's meaning?

Looking forward to any replies.

**Comment by Ai-is-light** [comment]
after build the caffe docker, and when I train the network, I got the information as following:

You are running caffe compiled with MPI support. Now it's running in non-parallel model
what's meaning?
What's more, I can't use the multi-gpus to train my model.

Looking forward to any advice.

**Comment by Ai-is-light** [comment]
@GBJim
 hi, after setting the device_id:[ 2,3,4], the training network only work with GPU=2, wihle the GPU=3,4 do not work with GPU=2.

**Comment by yjxiong** [comment]
The default training script uses 4 GPUs. 

You should set the GPU ids in the solver like
https://github.com/yjxiong/temporal-segment-networks/blob/master/models/ucf101/tsn_bn_inception_flow_solver.prototxt#L30

Other ways won't work

**Comment by AlanZhang1995** [comment]
@yjxiong I also meet this  problem. When i try to train it on two 1080Ti, I find it out of memory. Checking log, I find something as follow

I1021 07:34:50.020670 13128 caffe.cpp:112] Use CPU.
I1021 07:34:50.026909 13129 caffe.cpp:112] Use CPU.
Setting device 0
I1021 07:34:51.528982 13128 caffe.cpp:120] Swtiching to GPU 0
I1021 07:34:51.530387 13129 caffe.cpp:120] Swtiching to GPU 0
Setting device 0
I1021 07:34:51.534981 13128 caffe.cpp:190] Starting Optimization
I1021 07:34:51.535069 13128 solver.cpp:34] Initializing solver from parameters: 

I guess this means it initializes two networks on only GPU 0

BTW, I'm using the docker from your website and I don't find '/usr/local/openmpi/bin/' neither. So i'm not sure whether openMPI works normally or not.

Looking forward to your reply.

**Comment by AlanZhang1995** [comment]
I install MPI myself in the docker container and it works well.
thx!

**Comment by yjxiong** [comment]
@AlanZhang1995 Yes you are right. I may add a MPI installation in the docker image. Thanks for the updates!

**Comment by Hiker01** [comment]
I meet the same problem. Dose it mean that I should install openMPI in  my container?

**Comment by AlanZhang1995** [comment]
> I meet the same problem. Dose it mean that I should install openMPI in my container?
For me, installing MPI myself in the container solves the problem and i think it's worthy trying. BTW, you can refer to  dockerfile linked as follow to install MPI or to build a new image.
https://github.com/AlanZhang1995/LeinaoPAI/blob/master/images/temporal-segment-networks2/Dockerfile

**Comment by AlanZhang1995** [comment]
> I meet the same problem. Dose it mean that I should install openMPI in my container?

For me, installing MPI myself in the container solves the problem and i think it's worthy trying. BTW, you can refer to dockerfile linked as follow to install MPI or to build a new image.
https://github.com/AlanZhang1995/LeinaoPAI/blob/master/images/temporal-segment-networks2/Dockerfile

**Comment by WWwaycon** [comment]
> > I meet the same problem. Dose it mean that I should install openMPI in my container?
> 
> For me, installing MPI myself in the container solves the problem and i think it's worthy trying. BTW, you can refer to dockerfile linked as follow to install MPI or to build a new image.
> https://github.com/AlanZhang1995/LeinaoPAI/blob/master/images/temporal-segment-networks2/Dockerfile

hello,if i install MPI in the container,should i build caffe again?
