### ISSUE TITLE
error in Construct file lists for training and validation

### ISSUE THREAD

**Issue by NicoleNicoleXiang** [yjxiong/temporal-segment-networks#223]
hello，yjxiong
when i was trying to generate training and test list by running bash scripts/build_file_list.sh ucf101 FRAME_PATH
i got this error:
Traceback (most recent call last):
  File "tools/build_file_list.py", line 39, in <module>
    lists = build_split_list(split_tp, f_info, i, shuffle)
  File "/home/xlp/project4/temporal-segment-networks/pyActionRecog/benchmark_db.py", line 64, in build_split_list
    train_rgb_list, train_flow_list = build_set_list(split[0])
  File "/home/xlp/project4/temporal-segment-networks/pyActionRecog/benchmark_db.py", line 54, in build_set_list
    frame_dir = frame_info[0][item[0]]
KeyError: 'v_ApplyEyeMakeup_g08_c01'

i have to say the way of extracting the frame was not as yours and the structure of my data is 101 files containing defferent video flips files seperately.

**Comment by Mohamad73** [comment]
Hello, I am getting the same error, did find a solution for this error?

**Comment by yjxiong** [comment]
Your video frames are not present in the folder you specified. You need to first generate the frames before constructing file lists.

**Comment by sucaohan** [comment]
have u solved it?

**Comment by a-whitej** [comment]
D=/data/UCF-101
O=/data/train_data
for d in `ls $D`; do 
   for f in `ls $D/$d`; do
       #bf=$(echo $f | cut -d . -f1)
       if [ ! -d $O/$d  ];then
           mkdir $O/$d
       fi		
       ./extract_cpu -f=$D/$d/$f -x=$O/$d/flow_x-$f -y=$O/$d/flow_y-$f -i=$O/$d/image-$f -b=20 -t=1 -d=0 -s=1 -o=dir
	   break
   done
done

then create frame files in /data/train_data which has directores such as ApplyEyeMakeup,  Archery,BalanceBeam, and this direcory has jpg file such as image_00012.jpg/flow_x_00012.jpg/flow_y_00012.jpg.

but run
 bash scripts/build_file_list.sh ucf101  /data/train_data
  File "./pyActionRecog/benchmark_db.py", line 49, in build_set_list
    frame_dir = frame_info[0][item[0]]
KeyError: 'v_ApplyEyeMakeup_g08_c01'

Another problem, I am wondering how to extract flow for all directory like shell script above. but it can overwrite the files.

**Comment by MaYuefeng** [comment]
> D = / data / UCF-101 
> O = / data / train_data 
> for d in `ls $D`; 这样做
> 对于F中`ls $D/$d`; 如果[！做
> #bf = $（echo $ f | cut -d。-f1）
> -d $ O / $ d];然后
> mkdir $ O / $ d 
> fi 
> ./extract_cpu -f = $ D / $ d / $ f -x = $ O / $ d / flow_x- $ f -y = $ O / $ d / flow_y- $ F -i = $ O / $ d /图像- $ F -b = 20 -t = 1 -d = 0 -s = 1 -o = DIR 
> 断裂
> 完成
> 处理完毕
> 
> 然后在/ data / train_data中创建具有诸如ApplyEyeMakeup，Archery，BalanceBeam之类的目录的框架文件，并且该目录具有jpg文件，例如image_00012.jpg / flow_x_00012.jpg / flow_y_00012.jpg。
> 
> 但是 在build_set_list frame_dir = frame_info [0] [item [0]] 
> KeyError中运行bash脚本/build_file_list.sh ucf101 / data / train_data 
> 文件“ ./pyActionRecog/benchmark_db.py”，第49行KeyError ：'v_ApplyEyeMakeup_g08_c01'
> 
> 
> 另一个问题，我想知道如何为所有目录（如上面的shell脚本）提取流。但它可以覆盖文件。

I also met your problem? How did you solve it?

**Comment by MaYuefeng** [comment]
> Your video frames are not present in the folder you specified. You need to first generate the frames before constructing file lists.

@yjxiong  I used the script you provided to extract the video frame, but also returned the same error, how can I solve it?

My mistakes are as follows:

root@a397dbc68948:~/temporal-segment-networks# bash scripts/build_file_list.sh ucf101 /dataVolume/mayuefeng_file/root_folder/ApplyEyeMakeup
processing dataset ucf101
parse frames under folder /dataVolume/mayuefeng_file/root_folder/ApplyEyeMakeup
0 videos parsed
frame folder analysis done
writing list files for training/testing
Traceback (most recent call last):
  File "tools/build_file_list.py", line 39, in <module>
    lists = build_split_list(split_tp, f_info, i, shuffle)
  File "./pyActionRecog/benchmark_db.py", line 59, in build_split_list
    train_rgb_list, train_flow_list = build_set_list(split[0])
  File "./pyActionRecog/benchmark_db.py", line 49, in build_set_list
    frame_dir = frame_info[0][item[0]]
KeyError: 'v_ApplyLipstick_g08_c01'

**Comment by Nauman007** [comment]
hi can you show me a sample file list ? how does it look like and what is the file structure ?
regards!
