### ISSUE TITLE
Single Frame Classification w/ RGB and Flow Stream 

### ISSUE THREAD

**Issue by ZacharyIG** [yjxiong/temporal-segment-networks#224]
Hi,

I'm working on a similar problem, and I was wondering how you approached training the RGB/Flow models to classify at the frame level. Did you individually label frames for all UCF/HMDB data for example? Or just set all frame target labels to the video-level label? Thank you for clarifying.

**Comment by yjxiong** [comment]
You can read this in the paper. The training is done at the video level.
