### ISSUE TITLE
eval_scores.py

### ISSUE THREAD

**Issue by LuchenCatherine** [yjxiong/temporal-segment-networks#225]
line 25:  score_list = [x['scores'][:, 0] for x in score_npz_files]

Sorry for I cannot understand [:, 0] here. Can you explain it? 
Thank you very much!

**Comment by yjxiong** [comment]
It is because that the object contains both scores and labels. See here

https://github.com/yjxiong/temporal-segment-networks/blob/master/tools/eval_net.py#L112
