### ISSUE TITLE
I can't Get trained models

### ISSUE THREAD

**Issue by JiaHongTai** [yjxiong/temporal-segment-networks#230]
when i run bash /scripts/get_reference_models.sh  just got no such   file or directory 
did i missed something?

**Comment by yanqian123** [comment]
run bash scripts/get_reference_models.sh if you are under temporal-segment-networks-master/

**Comment by JiaHongTai** [comment]
thanks, got it

**Comment by yjxiong** [comment]
Closing this. Please feel free to reopen it if you meet any further problem.
