### ISSUE TITLE
Features extraction at frame level

### ISSUE THREAD

**Issue by pinkfloyd06** [yjxiong/temporal-segment-networks#233]
Hello @yjxiong,

Let me first thank you for your work.

Can l extract features representation (from last fully connected layer) for each frame (rather than for the whole video ?

Thank you a lot

**Comment by yjxiong** [comment]
Yes you can do that by some modification to the eval_net.py. But we don't have the code available to this.

**Comment by 770258506** [comment]
Hello @pinkfloyd06 ，
Have you solved the problem of feature extraction？
Do you have the code to extract features  (from last fully connected layer) for each frame or for the whole video,can you send me a copy?  My e-mail : 569421407@qq.com

Thank you a lot
