### ISSUE TITLE
Warped or Optical Flow?

### ISSUE THREAD

**Issue by Chonwing** [yjxiong/temporal-segment-networks#236]
In your paper, you listed the accuracies of two modalities and three modalities. In this code, when extracting optical flow, are we doing two or three modalities(in read.me it says optical flow or warped flow)? if two, are we using the warped or optical?

**Comment by Chonwing** [comment]
@yjxiong Any idea?

**Comment by yjxiong** [comment]
This code uses the standard optical flow for the experiments. If you follow the instructions in the README you are extracting optical flow. You can run the warp flow experiments by yourself.
