### ISSUE TITLE
Epoch size

### ISSUE THREAD

**Issue by fuankarion** [yjxiong/temporal-segment-networks#24]
Hi,

I'm fine tuning the TSN for action recognition in another dataset (only rgb data). I'd like to know how  to estimate the number of iterations in an epoch. 

By reading the paper and checking the train_val. I'm guessing that **at least** *N***batchsize* images are feed into the network every iteration ( where *N* is 'num_segment').  If I were right, an epoch would be: V/batchsize, where V is the total amount of videos.

However the param 'scale_ratios' and the amount of memory the GPU uses, makes me guess that,  more than *N***batchsize* images are feed into the network every iteration. Can you help me on this one?

Thanks
Fuanka

**Comment by yjxiong** [comment]
Your calculation of `V/batchsize` is correct. `scale_ratios` will not change the feeding behavior, it just controls the preprocessing of frames.
