### ISSUE TITLE
Error when extract optical flow images

### ISSUE THREAD

**Issue by VSunN** [yjxiong/temporal-segment-networks#243]
Hi,
When extracting the optical flow with gpu, I checked the error log file and found the out of memory error. But I don't know which video caused it. Does this mean that I need to re-extract the optical flow or that the program will automatically re-extract the video with the error? 
Hope to get your reply. @yjxiong

**Comment by yjxiong** [comment]
There is no auto-retry in the code. What you can do is to see the number frames for each video and verify the number in the extracted folders.
