### ISSUE TITLE
FPS calculation

### ISSUE THREAD

**Issue by yumiaoGitHub** [yjxiong/temporal-segment-networks#246]
I am research on the calculation of FPS in this project(340 FPS). Is there any explanation on the start and end point? I have tried calculate the forward time through caffe test tool(benchmark), but it showed a little difference. Will it be possible to show the code which you calculate the fps? Thanks a lot!

**Comment by yjxiong** [comment]
It’s not measures by Caffe test. It’s measured by running the provided toolbox.

**Comment by yumiaoGitHub** [comment]
Thank you for reply. I tested the time of predict_single_frame with python tool(time).  The result showed 30fps with over_sample=TRUE and 60fps with  over_sample=FALSE. I am wondering where is the difference between our methods?

**Comment by iamhoushiyou** [comment]
> It’s not measured by Caffe test. It’s measured by running the provided toolbox.

where is the toolbox?
