### ISSUE TITLE
test script error

### ISSUE THREAD

**Issue by KnightOfTheMoonlight** [yjxiong/temporal-segment-networks#26]
I just did the build instruction as you state in the README. However, I encountered the building errors below. It is weird because I have checked the caffe.proto file as in the lib folder, which has the field named "bn_param" for LayerParameter. 

By the way, the only difference bewteen your instruction and mine is that I did not use Anaconda for python.

[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 19:12: Message type "caffe.LayerParameter" has no field named "bn_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1101 09:15:29.878906 18368 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/ucf101/tsn_bn_inception_rgb_deploy.prototxt
*** Check failure stack trace: ***

**Comment by yjxiong** [comment]
I guess you may have another version of Caffe installed on the machine. And you may either be using the Python interfaces from that version or have had your Python interfaces linked to that version. Please have a look on LD_LIBRARY_PATH or the `ldd` the `_caffe.so` under the `python/` directory of the bundled Caffe.

**Comment by KnightOfTheMoonlight** [comment]
Yes. I have another version of caffe installed. And the python I used is not the default one in the system path. And I found that I have set the compiled pycaffe for that version has been set in `PYTHONPATH`.

I have not seen any setting for python path from your README rather than standard caffe. And I did not find `_caffe.so` file under the `python/` path. So I thought it must because the Python interface is not compiled. And I have no idea of how to solve that for TSN.

**Comment by yjxiong** [comment]
If the Python wrapper is not compiled, please try to compile it. In general, using a wrapper from another version of codebase won't help.

To compile it, you need to have boost version higher than 1.54. Usually, you can get that with `apt-get`.  Then please go into the build directory of Caffe. Run the `cmake ..` command and check the output. If the output contains something like

`python interface is disabled`

this means CMake cannot build the Python interfaces, due to either missing Python libraries in the paths or earlier Boost version. Please make sure the Python interface is compiled before using the provided scripts.

**Comment by KnightOfTheMoonlight** [comment]
I have add 
`# boost
set(Boost_NO_SYSTEM_PATHS ON)
set(BOOST_ROOT "/harddrives/epsilon/linli/libraries/boost")
set(BOOST_INCLUDEDIR "/harddrives/epsilon/linli/libraries/boost/include/boost")
set(BOOST_LIBRARYDIR "/harddrives/epsilon/linli/libraries/boost/lib")`
before 
`# ---[ Dependencies
include(cmake/Dependencies.cmake)`

of `ROOT/lib/caffe-action/CMakeLists.txt`
 
to solve this problem.

This problem is because I use personal python and boost library. And cmake can not find the specific  ones. The above solution is perfect for pycaffe.

**Comment by yjxiong** [comment]
Good to know. And thank you for posting the solutions!

**Comment by cc786537662** [comment]
I have the same quesion and solved by following your solution,thank you!

**Comment by buaa-luzhi** [comment]
Hello, @KnightOfTheMoonlight @cc786537662 
I have the same question like you!  Can you help me.
I have added these commands in    ROOT/lib/caffe-action/CMakeLists.txt
Like this....
................
caffe_option(USE_MPI "whether to include MPI parallelization" OFF) #Used to switch on and off MPI

# boost set(Boost_NO_SYSTEM_PATHS ON) set(BOOST_ROOT
"/harddrives/epsilon/linli/libraries/boost") set(BOOST_INCLUDEDIR
"/harddrives/epsilon/linli/libraries/boost/include/boost") set(BOOST_LIBRARYDIR
"/harddrives/epsilon/linli/libraries/boost/lib")

# ---[ Dependencies
include(cmake/Dependencies.cmake)  
..........

> _**But, when i compile caffe-action again,**_  some errors arise.

~/temporal-segment-networks/lib/caffe-action/build$ cmake ..
CMake Error: Error in cmake code at
/home/e829/temporal-segment-networks/lib/caffe-action/CMakeLists.txt:30:
Parse error.  Expected a command name, got quoted argument with text "/harddrives/epsilon/linli/libraries/boost".
-- Configuring incomplete, errors occurred!
See also "/home/e829/temporal-segment-networks/lib/caffe-action/build/CMakeFiles/CMakeOutput.log".
See also "/home/e829/temporal-segment-networks/lib/caffe-action/build/CMakeFiles/CMakeError.log"

Looking forward to your reply, thank you very much!

**Comment by buaa-luzhi** [comment]
Hello, @KnightOfTheMoonlight @cc786537662 
I have the same question.
.......
caffe_option(USE_MPI "whether to include MPI parallelization" OFF) #Used to switch on and off MPI

# boost set(Boost_NO_SYSTEM_PATHS ON) set(BOOST_ROOT
"/harddrives/epsilon/linli/libraries/boost") set(BOOST_INCLUDEDIR
"/harddrives/epsilon/linli/libraries/boost/include/boost") set(BOOST_LIBRARYDIR
"/harddrives/epsilon/linli/libraries/boost/lib")

# ---[ Dependencies
include(cmake/Dependencies.cmake)
.......
Just like you , i have added these commands in /lib/caffe-action/CMakeLists.txt

But, when i execute recompile

~/temporal-segment-networks/lib/caffe-action/build$ cmake ..
CMake Error: Error in cmake code at
/home/e829/temporal-segment-networks/lib/caffe-action/CMakeLists.txt:30:
Parse error.  Expected a command name, got quoted argument with text "/harddrives/epsilon/linli/libraries/boost".
-- Configuring incomplete, errors occurred!
See also "/home/e829/temporal-segment-networks/lib/caffe-action/build/CMakeFiles/CMakeOutput.log".
See also "/home/e829/temporal-segment-networks/lib/caffe-action/build/CMakeFiles/CMakeError.log".

**Comment by buaa-luzhi** [comment]
Hello, @KnightOfTheMoonlight @cc786537662
I have the same question like you! Can you help me.
I have added these commands in ROOT/lib/caffe-action/CMakeLists.txt
Like this....
................
caffe_option(USE_MPI "whether to include MPI parallelization" OFF) #Used to switch on and off MPI

boost set(Boost_NO_SYSTEM_PATHS ON) set(BOOST_ROOT

"/boost root/boost") set(BOOST_INCLUDEDIR
"/boost root/boost/include/boost") set(BOOST_LIBRARYDIR
"/boost root/boost/lib")

---[ Dependencies

include(cmake/Dependencies.cmake)
..........

But, when i compile caffe-action again,  this problem stiill exist!

Can you give me some advice, thanks in advance!
