### ISSUE TITLE
the image extraction part does not get the images

### ISSUE THREAD

**Issue by KnightOfTheMoonlight** [yjxiong/temporal-segment-networks#28]
Problem: the image extraction part does not get the images.

The denseflow library is build correctly.
And after run `bash scripts/extraction_optical_flow.sh SRC_FOLDER OUT_FOLDER NUM_WORKER`. I got the correct image paths but did not get the correct rgb and optical flow images. 

I checked the code, and I guess it is `tools/build_of.py` in charge of the image extraction mission. And I guess it must be `build/extract_gpu` for the image extraction task. The running shell outputs the content of  `print '{} {} done.format(vid_id, vid_name)`

Cause the `build/extract_gpu` is binary. I do not know how to check the details.

**Comment by yjxiong** [comment]
Few things to check here:

1. Video paths, are they valid?
2. VideoIO support in OpenCV, is it enabled for OpenCV, see #10  for more details

**Comment by KnightOfTheMoonlight** [comment]
Opps. I used my current opencv.

**Comment by KnightOfTheMoonlight** [comment]
I have another question, is opencv2.4.12 compatible with boost 1.59? 

When compiling, I got the follow message:
`../../lib/libopencv_ts.a(ts_gtest.cpp.o): In function `testing::internal::RE::~RE()':
ts_gtest.cpp:(.text._ZN7testing8internal2RED2Ev+0xf): undefined reference to `regfreeA'
ts_gtest.cpp:(.text._ZN7testing8internal2RED2Ev+0x18): undefined reference to `regfreeA'
../../lib/libopencv_ts.a(ts_gtest.cpp.o): In function `testing::internal::RE::FullMatch(char const*, testing::internal::RE const&)':
ts_gtest.cpp:(.text._ZN7testing8internal2RE9FullMatchEPKcRKS1_+0x2a): undefined reference to `regexecA'
../../lib/libopencv_ts.a(ts_gtest.cpp.o): In function `testing::internal::RE::PartialMatch(char const*, testing::internal::RE const&)':
ts_gtest.cpp:(.text._ZN7testing8internal2RE12PartialMatchEPKcRKS1_+0x2a): undefined reference to `regexecA'
../../lib/libopencv_ts.a(ts_gtest.cpp.o): In function `testing::internal::RE::Init(char const*)':
ts_gtest.cpp:(.text._ZN7testing8internal2RE4InitEPKc+0x62): undefined reference to `regcompA'
ts_gtest.cpp:(.text._ZN7testing8internal2RE4InitEPKc+0x88): undefined reference to `regcompA'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/opencv_perf_core] Error 1
make[1]: *** [modules/core/CMakeFiles/opencv_perf_core.dir/all] Error 2`

And from my search, it might be connected to boost.

**Comment by yjxiong** [comment]
Haven't met this before. Sorry I cannot help on it. Maybe try other version of Boost before digging into the problem.

**Comment by KnightOfTheMoonlight** [comment]
I have found the respective key words under my boost and system boost like below:
`linli@amax-SYS-7048GR-TR:/usr/include$ grep -n -H -R "regexecA"`
`boost/regex.h:61:using boost::regexecA;`
`boost/regex/v4/cregex.hpp:163:BOOST_REGEX_DECL int BOOST_REGEX_CCALL regexecA(const regex_tA*, const char*, regsize_t, regmatch_t*, int);`
`boost/regex/v4/cregex.hpp:182:#define regexec regexecA`

`linli@amax-SYS-7048GR-TR:/harddrives/epsilon/linli/libraries/boost$ grep -n -H -R "regexecA"
include/boost/regex.h:61:using boost::regexecA;`
`include/boost/regex/v4/cregex.hpp:163:BOOST_REGEX_DECL int BOOST_REGEX_CCALL regexecA(const regex_tA*, const char*, regsize_t, regmatch_t*, int);`
`include/boost/regex/v4/cregex.hpp:182:#define regexec regexecA
boost_1_59_0/libs/regex/example/timer/regex_timer.cpp:331:         regexecA(&r, s2.c_str(), nsubs, matches.get(), 0);`
`boost_1_59_0/libs/regex/example/timer/regex_timer.cpp:337:               result = regexecA(&r, s2.c_str(), nsubs, matches.get(), 0);`
`boost_1_59_0/libs/regex/example/timer/regex_timer.cpp:341:         cout << "POSIX regexecA time: " << (tim * 1000000 / iters) << "us" << endl;`
`boost_1_59_0/libs/regex/doc/posix_api.qbk:41:   int regexecA(const regex_tA*, const char*, unsigned int, regmatch_t*, int);`
`boost_1_59_0/libs/regex/doc/posix_api.qbk:58:   #define regexec regexecA`
`boost_1_59_0/libs/regex/doc/html/boost_regex/ref/posix.html:77:<span class="keyword">int</span> <span class="identifier">regexecA</span><span class="special">(</span><span class="keyword">const</span> <span class="identifier">regex_tA</span><span class="special">*,</span> <span class="keyword">const</span> <span class="keyword">char</span><span class="special">*,</span> <span class="keyword">unsigned</span> <span class="keyword">int</span><span class="special">,</span> <span class="identifier">regmatch_t</span><span class="special">*,</span> <span class="keyword">int</span><span class="special">);</span>
boost_1_59_0/libs/regex/doc/html/boost_regex/ref/posix.html:94:<span class="preprocessor">#define</span> <span class="identifier">regexec</span> <span class="identifier">regexecA</span>`
`boost_1_59_0/libs/regex/test/regress/test_deprecated.cpp:105:   if(boost::regexecA(&re, search_text.c_str(), max_subs, matches, posix_match_options) == 0)`
`boost_1_59_0/libs/regex/test/c_compiler_checks/posix_api_check.c:48:   result = regexecA(&re, text, 1, matches, REG_NOTBOL | REG_NOTEOL | REG_STARTEND);`
`boost_1_59_0/libs/regex/test/c_compiler_checks/posix_api_check.cpp:49:   result = regexecA(&re, text, 1, matches, REG_NOTBOL | REG_NOTEOL | REG_STARTEND);`
`boost_1_59_0/libs/regex/src/posix_api.cpp:217:BOOST_REGEX_DECL int BOOST_REGEX_CCALL regexecA(const regex_tA* expression, const char* buf, regsize_t n, regmatch_t* array, int eflags)
Binary file boost_1_59_0/bin.v2/libs/regex/build/gcc-4.8/release/link-static/threading-multi/libboost_regex.a matches`
`Binary file boost_1_59_0/bin.v2/libs/regex/build/gcc-4.8/release/link-static/threading-multi/posix_api.o matches`
`Binary file boost_1_59_0/bin.v2/libs/regex/build/gcc-4.8/release/threading-multi/libboost_regex.so.1.59.0 matches`
`Binary file boost_1_59_0/bin.v2/libs/regex/build/gcc-4.8/release/threading-multi/posix_api.o matches`
`boost_1_59_0/boost/regex.h:61:using boost::regexecA;`
`boost_1_59_0/boost/regex/v4/cregex.hpp:163:BOOST_REGEX_DECL int BOOST_REGEX_CCALL regexecA(const regex_tA*, const char*, regsize_t, regmatch_t*, int);`
`boost_1_59_0/boost/regex/v4/cregex.hpp:182:#define regexec regexecA`
`Binary file lib/libboost_regex.so.1.59.0 matches`
`Binary file lib/libboost_regex.a matches`
`Binary file lib/libboost_regex.so matches`

all the keywords are found like above.

**Comment by KnightOfTheMoonlight** [comment]
Finally!!!
This bug is because boost and linux have the same `regex.h` file. And renaming this file temporally can fix this. ref: https://groups.google.com/forum/#!searchin/caffe-users/regex.h/caffe-users/zTfFsRnNl9c/ckD-bar6BAAJ
So at the end I use my boost 1.59 and opencv2.4.12. and make the right opencv path for denseflow. this bug is fixed.

**Comment by wcj021312** [comment]
@KnightOfTheMoonlight  hello, I meet the same problem when I run bash scripts/extraction_optical_flow.sh SRC_FOLDER OUT_FOLDER NUM_WORKER ,the image extraction part does not get the images. can you give me some suggest about the image extraction? Thank you .

**Comment by KnightOfTheMoonlight** [comment]
@wcj021312  Did you check all the details above first?

**Comment by wcj021312** [comment]
Video paths is true, and opencv support videoIO, what detail that I need to check? example?

**Comment by KnightOfTheMoonlight** [comment]
So could I assume you have already successfully run the bash build_all.sh? My problem comes from building issues. 
By the way, did you get the videos by this -> https://github.com/yjxiong/temporal-segment-networks#get-the-videos?

**Comment by wcj021312** [comment]
Thank you very much for yuor reply, I have successfully run the bash build_all.sh, but the videos  is Downloaded by myself， not follow the way get-the-videos.  this is the why i failed? I will try, thank you !




------------------ 原始邮件 ------------------
发件人: "Lin Li";<notifications@github.com>;
发送时间: 2017年7月27日(星期四) 晚上6:24
收件人: "yjxiong/temporal-segment-networks"<temporal-segment-networks@noreply.github.com>; 
抄送: "C.J！！！"<2925428721@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [yjxiong/temporal-segment-networks] the image extraction partdoes not get the images (#28)




So could I assume you have already successfully run the bash build_all.sh? My problem comes from building issues.
 By the way, did you get the videos by this -> https://github.com/yjxiong/temporal-segment-networks#get-the-videos?

**Comment by yjxiong** [comment]
@wcj021312 
In case you are using your own videos, make sure they put in a two-level directory structure. This is assumed in the extraction script.
https://github.com/yjxiong/temporal-segment-networks/blob/master/tools/build_of.py#L115

Or you can change the script to fit your storage pattern.

**Comment by ymxv** [comment]
> Opps. I used my current opencv.

hello，i meet the same question, when i run scripts/extract_optical_flow, there is no images generated, but the path generated, and i checked build_of.py ,i don't think the flowing code has worked, do you have any idea? thank u!

cmd = os.path.join(df_path + 'build/extract_gpu')+' -f {} -x {} -y {} -i {} -b 20 -t 1 -d {} -s 1 -o {} -w {} -h {}'.format(quote(vid_path), quote(flow_x_path), quote(flow_y_path), quote(image_path), dev_id, out_format, new_size[0], new_size[1])
os.system(cmd)

**Comment by jimmy-ng** [comment]
@ymxv  You can solve it by using this command instead: 
cmd = os.path.join(df_path + 'build/extract_gpu')+' -f={} -x={} -y={} -i={} -b=20 -t= 1 -d={} -s=1 -o={} -w={} -h={}'.format(quote(vid_path), quote(flow_x_path), quote(flow_y_path), quote(image_path), dev_id, out_format, new_size[0], new_size[1])
