### ISSUE TITLE
batch_size

### ISSUE THREAD

**Issue by xuzero** [yjxiong/temporal-segment-networks#29]
You say that the the effective batchsize equals to batch_size*iter_size*n_gpu, to be 128. Your parameter is 32*1(iter_size)*4(GPU), i have to set it to 16(bath_size)*4(iter_size)*2(GPU) make batchsize to be 128 due to my poor server,what about other parameter?such as the stepvalue and max_iter, keep it still or multiple 4 because the iter_size become 4 rather than 1? Do i need to change other parameter？ i do the work on the ucf101 spilt1.

i also have another question, you set the new_length to 5 in the tsn_bn_inception_flow_train_val.prototxt,
but the better parameter should be 10 according to the 2 stream paper(NIPS14).Is it a bug or 5 is better for TSN?
Thanks!

**Comment by yjxiong** [comment]
Generally, as long as you use the same effective batchsize, no other parameter need to be altered.

For the `new_length`, 5 is working reasonably well with TSN and leads to faster training. So we use 5 instead of 10. It is not a bug.
