### ISSUE TITLE
.caffemodel可视化

### ISSUE THREAD

**Issue by double-vane** [yjxiong/temporal-segment-networks#30]
你好，请问如何可视化初始的.caffemodel？
例如bn_inception_flow_init.caffemodel

**Comment by yekeping** [comment]
do you finish the experiment?

**Comment by double-vane** [comment]
@yekeping  实现了rgb的，但是flow的效果很不好

**Comment by georgiazhang** [comment]
Did you solve the problem about visual the model?I can run the original deepdraw,but i can't  run it with the TSN model.Please help me.
