### ISSUE TITLE
what is the best usage strategy with openmpi

### ISSUE THREAD

**Issue by KnightOfTheMoonlight** [yjxiong/temporal-segment-networks#31]
Sorry to say that I have almost zero knowledge about openmpi. 
I just know it is used for parallelization and acceleration and `--num_worker` is some kind of parameter for openmpi.

For example, I have 4 GPU 12G/per.
What is the best usage strategy for this? Or is there any tricks to try to find the best usage strategy?
The bigger, the better? 

:-) . I just don't want to waste any of the machines and my time.

**Comment by yjxiong** [comment]
Just put as much as you have into the training. The bundled Caffe is optimized to guarantee you get almost linear acceleration w.r.t. number of GPUs.

**Comment by KnightOfTheMoonlight** [comment]
I have used 8 workers out of 4 GPU for image extraction. But in the end, I find some video frames are not extracted. So the worker number upper-bound is the number of GPU card, right?

**Comment by yjxiong** [comment]
It is fine to have more workers than that, as long as their assigned device IDs are within range of your available GPUs.
