### ISSUE TITLE
build_all.sh error!!!please help--/usr/bin/ld: cannot find -lopencv_dep_cudart

### ISSUE THREAD

**Issue by cc786537662** [yjxiong/temporal-segment-networks#33]
when i do bash build_all.sh,
i get the wrong message:
one:
    [ 71%] Linking CXX shared library libpydenseflow.so
    /usr/bin/ld: cannot find -lopencv_dep_cudart
    collect2: error: ld returned 1 exit status
    make[2]: *** [extract_gpu] Error 1
this happened,when do the "Building Dense Flow",i read the build_all.sh and i delete the code after "build opencv"part ,opencv build OK like this:
      [ 99%] Built target opencv_test_contrib
      [100%] Built target opencv_python
      OpenCV 2.4.12 built
but when i add the "Building Dense Flow" part or run "Caffe Built"indenpendently,i got the same error,this is when i skip "Building Dense Flow" part and do"Caffe Built"part :
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/xuliang/temporal-segment-networks/lib/caffe-action/build
    [  1%] Built target proto
    Scanning dependencies of target caffe
    [  1%] Linking CXX shared library ../../lib/libcaffe.so
    /usr/bin/ld: cannot find -lopencv_dep_cudart
    collect2: error: ld returned 1 exit status
    make[2]: *** [lib/libcaffe.so] Error 1
    make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
    make: *** [all] Error 2
    Caffe Built
my machine is centos,and  iknow the code in build_all.sh "apt-get" don't work,so i have install the dependences in yum,i still try to use opecv2.4.9 or 2.4.13,errors are the same,would do please help me?thank u!!
problem seems to happend to opencv because -lopencv_dep_cudart error ,but i don't know how to fix it.

**Comment by yjxiong** [comment]
Does your OpenCV have CUDA support enabled? If it is from yum, in some cases it might not have CUDA support.

**Comment by cc786537662** [comment]
YES,i do compile opencv like this:
cmake -D WITH_CUDA=ON \
    -D ENABLE_FAST_MATH=1 \
    -D CUDA_FAST_MATH=1 \
    -D INSTALL_C_EXAMPLES=OFF \
    -D WITH_CUBLAS=1 \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules ~/opencv \
    -D BUILD_EXAMPLES=ON \
    -D CMAKE_BUILD_TYPE=RELEASE \
    -D WITH_TBB=ON  -D WITH_V4L=ON \
    -D WITH_FFMPEG=OFF \
    -D USE_MPI=ON  -D CMAKE_INSTALL_PREFIX=/usr/local CMakeLists.txt

and opencv make fine,but still ::
[  1%] Linking CXX shared library ../../lib/libcaffe.so
/usr/bin/ld: cannot find -lopencv_dep_cudart


when do the  "Building Dense Flow" part and the "Caffe Built"part ,that makes crazy,,,thank you in advanced！

**Comment by yjxiong** [comment]
Did you confirm the output of CMake looks fine?

Also, it is possible that your OpenCV version in compiling is not the same one used for linking.

**Comment by cc786537662** [comment]
请问您的代码依赖于ffmpeg库吗？编译opencv时-D WITH_FFMPEG=OFF 这一项对后面的编译会有影响吗？

**Comment by yjxiong** [comment]
Yes.

**Comment by cc786537662** [comment]
非常感谢作者，我已经安装好了，原来用的centos各种问题，换到ubuntu的服务器直接build_all,完成

**Comment by mangdian** [comment]
请问您是怎么解决/usr/bin/ld: cannot find -lopencv_dep_cudart这个问题的

**Comment by cc786537662** [comment]
@mangdian 我把服务器系统从centos换成ubuntu这个问题就消失了，在centos上折腾了很久还是未解决该问题

**Comment by IvyGongoogle** [comment]
@yjxiong 我的系统是ubuntu16.04，但是我遇到了@cc786537662一样的问题。build_all脚本中

`OpenCV_DIR=../../../3rd-party/opencv-$version/build/ cmake .. -DUSE_MPI=ON -DMPI_CXX_COMPILER="${CAFFE_MPI_PREFIX}/bin/mpicxx"`这句话的意思是编译caffe时用上面自己下载编译过的opencv2.4.13/build这个库吗？ 而上面编译opencv2.4.13时用的是`cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_TBB=ON -D WITH_V4L=ON ..`这个命令，而-D WITH_CUDA默认是ON的，这样的话我们上面编译的opencv2.4.13是have CUDA support enabled的啊，为什么这里还会报错找不到-lopencv_dep_cudart呢：

```
/usr/bin/ld: cannot find -lopencv_dep_cudart
collect2: error: ld returned 1 exit status
src/caffe/CMakeFiles/caffe.dir/build.make:80893: recipe for target 'lib/libcaffe.so' failed
make[2]: *** [lib/libcaffe.so] Error 1
CMakeFiles/Makefile2:240: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2

```
@yjxiong 可以再给点建议吗？

**Comment by yjxiong** [comment]
add `-DCUDA_USE_STATIC_CUDA_RUNTIME=OFF` to your build command.

**Comment by IvyGongoogle** [comment]
@yjxiong your advice do work! thank you very much~
