### ISSUE TITLE
How to tansform conv1 weights in caffemodel from (64,3,3,3) to (64,20,3,3)?

### ISSUE THREAD

**Issue by haohao900618** [yjxiong/temporal-segment-networks#34]
@yjxiong The TemporalNet finetunes from VGG-16 and dou you have the tool to tansform conv1 weights in caffemodel from (64,3,3,3) to (64,20,3,3). If you have please share it on the website. Thanks for you!

**Comment by yjxiong** [comment]
We have already provided the download for VGG here

http://mmlab.siat.ac.cn/pretrain/vgg_16_action_flow_pretrain.caffemodel

**Comment by haohao900618** [comment]
@yjxiong Thanks for your attention. I want to try the other pre-trained models. Coluld you please share the transformer tool others. Thanks for you sincerely!

**Comment by yjxiong** [comment]
Then use this

https://gist.github.com/yjxiong/de4869c3a5bb3f0f810c

**Comment by haohao900618** [comment]
@yjxiong Good jobs! Thanks for your work!
