### ISSUE TITLE
question_of_TSN_Accuracy_On_UCF101_split1

### ISSUE THREAD

**Issue by liu666666** [yjxiong/temporal-segment-networks#35]
Hi,Thanks for your sharing!
I get the accuracy is 87.36% with the TSN architecture and your model and deploy file and your caffe code,
but your paper say the the accuracy is 87.9%, I set the num_sample to be 25 and did not use the multi_scale in the predict_single_flow_stack function in the eval_net.py( https://github.com/yjxiong/temporal-segment-networks/blob/master/tools/eval_net.py).
BTW, the server is equipped with k80 and cuda7.5 and cudnn4.0, i downsample the video by getting 1 frame per 15 frames.  In the eval_net.py line121, i use the sliding_window_aggregation_func rather than the default_aggregation_func, i think that  the funxtion of sliding_window_aggregation_func  is to make use of the TSN,right?
Could you please tell me the reason?  Thank you very much!

**Comment by yjxiong** [comment]
You should use the default aggregation function and use 25 snippets for evaluation. Please follow exactly what the paper says to obtain the results.

It is OK to see minor differences in single split single modality accuracies while the combined results are quite consistent. But if you did not use all frames of the videos for training, I cannot guarantee you will get the same results.
