### ISSUE TITLE
Why my reference flow downloaded model doesn't produce the right result.

### ISSUE THREAD

**Issue by yonghenglh6** [yjxiong/temporal-segment-networks#37]
Hi:
When I test the reference model download from website a. The flow model produce very low accuracy.
Here is my config:
```
args.dataset='ucf101'
args.split=1
args.modality='flow'
args.frame_path='XXXXXXX/datas/UCF101/img_output'
args.net_proto='models/ucf101/tsn_bn_inception_flow_deploy.prototxt'
args.net_weights='models/ucf101_split_1_tsn_flow_reference_bn_inception.caffemodel'
args.save_scores='flow_score2'
```
It produced the Final accuracy 13.278916% on UCF101 split 1.
While the only-rgb model produced the Final accuracy 86.037706%.
Are there any mistake for my config? Or any other body get the same accuracy number as mine?
Seeking for help~~

**Comment by yjxiong** [comment]
Your configs look fine. Have you followed the steps in the `README`, including the optical flow extraction, and assured every step succeeded?

**Comment by yonghenglh6** [comment]
Thanks for your reply. 
I checked all steps, ran again and get the same wrong result again.
I'm going to rearrange all in another environment to find the reason.

**Comment by yonghenglh6** [comment]
Hi  yjxiong,
Sorry to bother you again.
My optical flow data was extracted by your dense flow program. But when I look into the result directory, the images contains data with cyclical interval of one image. Just as the picture says:
![qq 20161215011237](https://cloud.githubusercontent.com/assets/6671814/21192718/7f83ca46-c264-11e6-9e28-24701bd5e735.png)

![qq 20161215011302](https://cloud.githubusercontent.com/assets/6671814/21192723/827838b8-c264-11e6-990a-dca3a4e2ba6b.png)

Some of the images contains data, while some of them show nothing. These two kinds appear periodically. 
Forgive my ignorance of optical flow methods.
Is this normal?  Or may some of my environment have faults?

**Comment by yjxiong** [comment]
Are you using the script `scripts/extraction_optical_flow.sh`? Would you please also provide the video name of frames in your question?

**Comment by yonghenglh6** [comment]
Yes, I used the script you mentioned, "scripts/extraction_optical_flow.sh". 
The first image sequence I posted comes from v_ApplyEyeMakeup_g01_c01, but the second losts the source name. 
I changed to a new environment,rearranged all, and ran the program again, but still got the same wrong result.
Thank you anyway. I'll try another database.

**Comment by yjxiong** [comment]
Your flow frames indeed look different from what I got. Here I have the same first sequence for your references. Just to note that the flow model is trained with TVL1 optical flow, which is provided by the `extract_flow_gpu` tool in DenseFlow. It needs the OpenCV to be compiled with GPU support. 

Please have a look at whether you are using the TVL1 algorithm for flow extraction.

![image](https://cloud.githubusercontent.com/assets/6830199/21226441/781b49f8-c310-11e6-8fe9-49584d1871e7.png)

**Comment by yonghenglh6** [comment]
Maybe this is the reason.
I edited the script to "**extract_cpu**" before. Because I found using cpu with 24 num_worker is much faster than using gpu, and by my common sense the extracted result would not be changed.
Now I changed back. And when it is done, I will report again.

**Comment by yjxiong** [comment]
Good to know the reason. 

Yes, you can train your own model using other optical flow algorithms while the performance might be similar. But the reference model is trained with TVL1, so using other algorithms in testing will yield incompetent results.

**Comment by yonghenglh6** [comment]
I retrain the flow model with the UCF101 frames extracted by **extract_flow_cpu**. But it converges hardly. 
The loss is about 1.2 when the iteration is 20000, and it is still 0.8 when the iteration is 80000. 
And the 20000-iteration flow model got a 56% test accuracy.
It seems the frame extracted by **extract_flow_cpu** is very different from that by "extracted_flow_gpu".
I wondered why you used **extract_flow_gpu** instead of **extract_flow_cpu**.  The speed of **extract_flow_gpu** is so slow that it may take several days, while extract_flow_cpu with 24 threads takes only three hours. 
Thank you. When I have more experiments, I will report again.

**Comment by yjxiong** [comment]
`extract_flow_cpu` has multiple flow algorithms, and the parameters are set to work on the TVL1 algorithm.
I don't know which algorithm you are using. And to our experiences, using 4 TitanX GPUs the flow extraction of UCF101 is done in 4 hours.

**Comment by yjxiong** [comment]
@yonghenglh6 
Any luck with your experiments?

**Comment by yonghenglh6** [comment]
Extracting with gpu is still in progress, and will be finished tomorrow. 
I have two titan X, but when extracting, the gpu-util from `nvidia-smi` is always zero.
Thanku.
When it is done, I will report again.

**Comment by yjxiong** [comment]
@yonghenglh6 
I just checked the DenseFlow codebase. The CPU version of `extract_flow` only implemented Farneback flow, which is quite different from TVL1. So the difference in extracted flow images you experienced might be caused by this.
