### ISSUE TITLE
flow modality 

### ISSUE THREAD

**Issue by double-vane** [yjxiong/temporal-segment-networks#39]
![2016-12-19 20-37-09](https://cloud.githubusercontent.com/assets/20334378/21313267/c43d2388-c62b-11e6-8f56-d2d20bf93b5b.png)
![2016-12-19 20-37-38](https://cloud.githubusercontent.com/assets/20334378/21313266/c4398886-c62b-11e6-9b89-54969a3ea5dd.png)

OK! I asked you about the issue that I can't get the correct result. And I re-downloaded  the `bn_inception_flow_init.caffemodel` with the command `get_init_models.sh` .
I checked its properties which modified on August 30th.
Will I download the correct?
![2016-12-20 20-51-52](https://cloud.githubusercontent.com/assets/20334378/21313513/401c87ae-c62d-11e6-97b2-86e22bef5a18.png)
@yjxiong  Very much looking forward to your answer.

**Comment by double-vane** [comment]
![solver](https://cloud.githubusercontent.com/assets/20334378/21313700/4d203350-c62e-11e6-91aa-7ed18de6a685.png)
![train_val](https://cloud.githubusercontent.com/assets/20334378/21313701/4d23ae4a-c62e-11e6-8ecb-fac888a2b802.png)
Is my batchsize set too small？

**Comment by yjxiong** [comment]
Possibly. 
How many GPUs are you using for training? Please note that, the effective batchsize, which is `batch_size*iter_size*num_gpu` should be around `128`.

**Comment by double-vane** [comment]
@yjxiong only one. I'll modify as you said.

**Comment by double-vane** [comment]
By the way,Why must be 128？

**Comment by yjxiong** [comment]
Cause this will affect the number epochs. Too few epochs will be not enough for the model to converge. 
And it is a common practice to use relative larger batchsize than 32.

**Comment by double-vane** [comment]
Thank you very much  for your concentration and it's work but too time consuming
