### ISSUE TITLE
For the cpu version of dense_flow lib

### ISSUE THREAD

**Issue by YunLexi** [yjxiong/temporal-segment-networks#45]

**Comment by YunLexi** [comment]
The line of 42 in  lib/dense_flow/src/dense_flow.cpp  should be corrected from: encodeFlowMap(flow_split[0], flow_split[0], str_x, str_y, bound); to encodeFlowMap(flow_split[0], flow_split[1], str_x, str_y, bound);?

**Comment by yjxiong** [comment]
Thanks for raising the issue. I'll look at it very soon.

**Comment by yjxiong** [comment]
You are correct. I just fixed this in the DenseFlow repo.

Also, I would like to note that the CPU version of DenseFlow only implemented Farneback flow, which is different from the TVL1 flow we used for this project.

**Comment by yjxiong** [comment]
Again, thanks for you kind help!
