### ISSUE TITLE
tsn网络对于每一个snippet下采样的比例？

### ISSUE THREAD

**Issue by cc786537662** [yjxiong/temporal-segment-networks#46]

**Comment by cc786537662** [comment]
请问文章中你们指出要对一个Video分段为Sk，然后对每一个Sk随机采样为Tk，请问对于RGB和Flow两个流的下采样比例是多少呢？分为三段是每一段上RGB图像下采样保留几帧呢？Flow又是保留保留几张呢？从源代码看是每一个snippet在RGB上是保留一帧，flow上是保留5张吗？
谢谢

**Comment by yjxiong** [comment]
There is no subsampling rate in TSN. For each segment, there is always one snippet sampled regardless of the segment's length. A snippet is composed of one frame for RGB input and 5 frames for optical flow input.

This is described clearly in the paper.

**Comment by cc786537662** [comment]
Thank you for your kind reply!
I should read your paper more carefully,sorry to ask such negligent qusetion.

**Comment by yjxiong** [comment]
No problem.

Good luck with your experiments!

**Comment by kstys** [comment]
@cc786537662 Hello，
A video will be divided to 3 segments  ,if A video has 150 frames and A segement will contain 50 frames ,A frames will be chosen from the 50 frames as a snippet?
