### ISSUE TITLE
about multiple scale input 

### ISSUE THREAD

**Issue by KnightOfTheMoonlight** [yjxiong/temporal-segment-networks#47]
From your TSN paper, you said that you used scale jittering for the inputs.
However, from your code in `./pyActionRecog/action_caffe.py`, I think you just put multiple scale input in RGB image in the function of `predict_single_frame`. However for the optical flow input, you did not add multiple scale input in the function of `predict_single_flow_stack`. 

Here comes another question. For the multiple input crop, you just use `{256, 224, 192, 168}` as you said in the paper, right? What is the performance improvement with the scale jittering?

And besides, I have tried limin's TDD multiple scale input setting, namely, while extracting CNN features for each video, I just use multiple scale input and multiple input blob size correspondingly. I copied limin's setting, namely,  (480,640), (340,454), (240,320), (170,227), (120,160), however, this settings get problems in the inception layer. Because the input block sizes for inception module is mismatched. Do you have any suggestions for this kind of multiple input size setting?

**Comment by yjxiong** [comment]
In testing, we do not use multi-scale input for fair comparison with other methods. The option is just for future use. Scale jittering is only used in training.

The problem of your inception models come from the different convention used in inferring the output sizes. When the kernel size cannot divide the input size, the pooling layers and convolution layers of Caffe will get different output sizes from the same input size. So you can choose an input size that bypass this convention of just change how the layers compute its output sizes.
