### ISSUE TITLE
ImportError: No module named _caffe

### ISSUE THREAD

**Issue by fetorres** [yjxiong/temporal-segment-networks#49]
Hello,

I am trying to run the eval_net.py example in the README description, but I get 
"ImportError: No module named _caffe".  I am running in an Anaconda environment.  Everything seemed to install OK with no errors.

I run the command
python tools/eval_net.py ucf101 1 rgb UCF-101_frames/ models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel --num_worker 4 --save_scores scoresOutput.txt

I get:
Traceback (most recent call last):
  File "tools/eval_net.py", line 38, in <module>
    from pyActionRecog.action_caffe import CaffeNet
  File "/data/torres/temporal-segment-networks/pyActionRecog/action_caffe.py", line 4, in <module>
    import caffe
  File "./lib/caffe-action/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "./lib/caffe-action/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: No module named _caffe

I have tried to read through google posts for this error, but they all refer to the standard Caffe installation, including the "make pycaffe" part of it.  Your installation is customized and therefore different :)

Do you have any suggestions for me?

Thank you,
Frank Torres
Palo Alto Research Center

**Comment by yjxiong** [comment]
This indicates you didn't build the Python bindings of Caffe. The `make pycaffe` command is also for this.

We use CMake, it will automatically build the Python bindings once all dependencies are met. Please check whether you followed the steps in `build_all.sh`.

**Comment by fetorres** [comment]
Thank you.  It took some time, but I figured out my problem.  I had corrupted boost files deep in installs and updates.  I needed to completely clean boos off my compute server and then reinstall fresh.  now it works.
Best,Frank

**Comment by yjxiong** [comment]
Thanks for sharing your solutions! 

Closing this issue as it is resolved.
