### ISSUE TITLE
No space left on device while compiling OpenCV using the build script

### ISSUE THREAD

**Issue by YuMao1993** [yjxiong/temporal-segment-networks#50]
[ 52%] Building CXX object apps/haartraining/CMakeFiles/opencv_haartraining_engine.dir/cvcommon.cpp.o
/usr/local/cuda/include/math_functions.h(303) (col. 90): catastrophic error: error while writing generated C file: No space left on device

I verified that I have enough space for my /tmp folder (several gigabytes). Any thoughts?

**Comment by yjxiong** [comment]
No idea. Please check your storage.
