### ISSUE TITLE
Different number of segments

### ISSUE THREAD

**Issue by mzolfaghari** [yjxiong/temporal-segment-networks#51]
Hi,

I'm trying to change the number of segments but changing the numbers in data layer and loss layer does not help!. Could you please provide information regarding this. 

Thanks,

**Comment by yjxiong** [comment]
Segment number has also to be changed in the consensus module.

In particular, please change the `num_segments` param in

https://github.com/yjxiong/temporal-segment-networks/blob/master/models/ucf101/tsn_bn_inception_rgb_train_val.prototxt#L11

and the `3` in the pooling and the reshape layer at

https://github.com/yjxiong/temporal-segment-networks/blob/master/models/ucf101/tsn_bn_inception_rgb_train_val.prototxt#L790

**Comment by mzolfaghari** [comment]
@yjxiong  Thanks for your quick reply. Also, "mean_value" in the VideoData layer need to be set properly based on the number of segments.
Now, it works.

Thanks,

**Comment by yjxiong** [comment]
Great to know. And good luck with your experiments!

Closing this. Please feel free to reopen it if you meet any further problem.

**Comment by shamoqianting** [comment]
@mzolfaghari could you give more details about how to set the "mean_value" in the VideoData layer ? I am new to caffe and don't understand the variable very well. Thank you very much.

**Comment by jeena72** [comment]
@mzolfaghari if possible kindly share the exact changes required to be made in '*_train_val.prototxt' to train TSN using different number of segment, thanks a lot in advance!

**Comment by mzolfaghari** [comment]
@shamoqianting @jeena72 
lets assume that we have 5 segments( on UCF101 dataset). Then necessary changes:

In data layer:
```
num_segments: 5
mean_value: [104, 117, 123,104, 117, 123,104, 117, 123,104, 117, 123,104, 117, 123]
```
In loss accuracy part:
```
layer { name: "reshape_fc" type: "Reshape" bottom: "fc" top: "reshape_fc" reshape_param { shape { dim: [-1, 1, 5, 101] } } } 
layer { name: "segment_consensus" type: "Pooling" bottom: "reshape_fc" top: "pool_fusion" pooling_param { pool: AVE kernel_h: 5 kernel_w: 1 } }

```

**Comment by jeena72** [comment]
@mzolfaghari I did as you suggested, and was successful in training using different number of segments. Thanks a lot for your prompt help!
