### ISSUE TITLE
Hyperparameters for experiments

### ISSUE THREAD

**Issue by joeyhng** [yjxiong/temporal-segment-networks#53]
The number of iterations and decay schedule in the solvers are different from the papers. Should I expect the ones in the solvers to be able to reproduce the best performance?

Also, do you train the HMDB flow model initialized from UCF101 model or just use the provided init model?

Thanks!

**Comment by yjxiong** [comment]
Hi! As we mentioned in the README, we fixed a bug in the bundled Caffe which affects the hyperparameter. So please stick to the parameters in the provided solvers for the sake of best performance.

Models on HMDB51 and UCF101 are both trained from the provided init model. No need for pre-training HMDB51 model on UCF101.

**Comment by joeyhng** [comment]
Thanks!
