### ISSUE TITLE
can this code run on cpu-only caffe?

### ISSUE THREAD

**Issue by q252558242** [yjxiong/temporal-segment-networks#56]
Because my computer cannot support GPU acceleration, I want to now how can if I can change this code to run on cpu-only ?

**Comment by yjxiong** [comment]
It can. But it may take many days to train your networks. Running CPU-only can be achieved setting the solver to `CPU` mode.

**Comment by q252558242** [comment]
thanks a lot.

**Comment by saranyagopal1** [comment]
Hi @yjxiong ,
I changed the solver mode to CPU. It hit a floating point exception.
*** SIGFPE (@0x7fdf7a45d45d) received by PID 26723 (TID 0x7fdf7aa3aa00) from PID 2051396701; stack trace: ***
    @     0x7fd8a21c7849 caffe::Net<>::Net()
    @     0x7fa381875c46 caffe::Solver<>::Solver()
    @     0x7f1311eb245d caffe::VideoDataLayer<>::DataLayerSetUp()
    @           0x4181f0 caffe::GetSolver<>()
    @           0x40fc2d train()
    @           0x40e5a6 main
    @     0x7fdf78b41cb0 (unknown)
    @     0x7fd8a2176a10 caffe::Solver<>::InitTrainNet()
    @     0x7f1311ef7bb5 caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7fa37fe6ef45 (unknown)
    @           0x40eb8b (unknown)
    @     0x7fdf7a45d45d caffe::VideoDataLayer<>::DataLayerSetUp()
    @                0x0 (unknown)
    @     0x7fd8a2177aae caffe::Solver<>::Init()
    @     0x7f1311fd6ab7 caffe::Net<>::Init()
    @     0x7fdf7a4a2bb5 caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7fdf7a581ab7 caffe::Net<>::Init()
    @     0x7f1311fd8849 caffe::Net<>::Net()
    @     0x7fd8a2177c46 caffe::Solver<>::Solver()
    @           0x4181f0 caffe::GetSolver<>()
    @           0x40fc2d train()
    @           0x40e5a6 main
    @     0x7fdf7a583849 caffe::Net<>::Net()
    @     0x7fdf7a532a10 caffe::Solver<>::InitTrainNet()
    @     0x7f1311f87a10 caffe::Solver<>::InitTrainNet()
    @     0x7fd8a0770f45 (unknown)
    @           0x40eb8b (unknown)
    @     0x7fdf7a533aae caffe::Solver<>::Init()
    @     0x7f1311f88aae caffe::Solver<>::Init()
    @     0x7fdf7a533c46 caffe::Solver<>::Solver()
    @           0x4181f0 caffe::GetSolver<>()
    @                0x0 (unknown)
    @           0x40fc2d train()
    @           0x40e5a6 main
    @     0x7fdf78b2cf45 (unknown)
    @           0x40eb8b (unknown)
    @     0x7f1311f88c46 caffe::Solver<>::Solver()
    @           0x4181f0 caffe::GetSolver<>()
    @           0x40fc2d train()
    @           0x40e5a6 main
    @                0x0 (unknown)
    @     0x7f1310581f45 (unknown)
    @           0x40eb8b (unknown)
    @                0x0 (unknown)
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 26722 on node saranya-H97M-D3H exited on signal 8 (Floating point exception).

@YingQian94 ,
Were you able to successfully run this on CPU-only mode?
