### ISSUE TITLE
can this code run on mac?

### ISSUE THREAD

**Issue by guangbaby** [yjxiong/temporal-segment-networks#57]
Hello, @yjxiong @wanglimin 

Thank you for sharing the wonderful code.

The version of my mac  is sierra 10.12.3.
Currently,  when I built "bash build_all.sh", there is a error like:
 "/usr/local/Cellar/temporal-segment-networks/3rd-party/opencv2.4.12/modules/highgui/src/cap_qtkit.mm:46:9: fatal error: 
'QTKit/QTKit.h' file not found
#import <QTKit/QTKit.h>"

So I want to know how can I change this code to run on mac?

Thank you in advance.

**Comment by yjxiong** [comment]
Basically, the Python code of TSN should run on Mac. But compiling OpenCV and Caffe might be trickier.
So if you have already got OpenCV and Caffe you should be good to go.

**Comment by yjxiong** [comment]
@guangbaby , any luck?

**Comment by guangbaby** [comment]
Hello, @yjxiong @wanglimin 
Sorry for reply so later.
Yes, I solved it by changing OpenCV from 2.4.12 to 2.4.13.2. 
2.4.13.2 worked well in my computer.
By the way, I also tried your work  in a service with ubuntu 14.04 and  a GPU.
It worked well. 
Later I will try to solve my task using this method.
Thank you very much again.

**Comment by yjxiong** [comment]
Great to know. And good luck with your experiments!
