### ISSUE TITLE
Extracting features: AttributeError: 'CaffeNet' object has no attribute 'blobs'

### ISSUE THREAD

**Issue by mshreve** [yjxiong/temporal-segment-networks#58]
Hello, I am trying to extract the features from the trained network (HMDB5 RGB) using the 'blobs' attribute. However, it doesn't seems that the version of caffe included with TSN has that functionality. Is there a different way to extract the features from a particular layer? I have tried the following:

>>> net.blobs['inception_5b/pool_proj_bn'].data[0].reshape(1,-1)

but I get the following error:

>>> AttributeError: 'CaffeNet' object has no attribute 'blobs'

Any help would be greatly appreciated!

Thanks,
MS

**Comment by yjxiong** [comment]
It surely has blobs access as we are also using it. Would you please check whether you are using the correct way to construct the net instance?

**Comment by mshreve** [comment]
Thanks for your response, that was it. I was modifying the **eval_net.py** and didn't check to how the net was being loaded. It loads the net in 'net._net', so to access blobs using this file you need to use 'net._net.blobs[]...'
