### ISSUE TITLE
number of hmdb51 videos used for training and testing

### ISSUE THREAD

**Issue by fetorres** [yjxiong/temporal-segment-networks#59]
Hello,

Thank you for sharing this code, this is a great body of work.
I am curious about the train/test splits, particularly for the hmdb51 videos.  From the *split*.txt files, it looks like a number of videos are labeled as "0" rather than "1" or "2", so that they are not used.  Is this correct, and if so, what criterion is used to exclude?

Thank you :)

**Comment by fetorres** [comment]
Update:  I see this is something identified from the original HMDB51 dataset:
http://serre-lab.clps.brown.edu/wp-content/uploads/2013/10/split_readme.txt

So that is something they decided, not your group, correct?

Thank you

**Comment by yjxiong** [comment]
Hi! Yes you are right. We are using the official splits as a standard practice.
