### ISSUE TITLE
which version Opencv should be used to compile dense_flow ?

### ISSUE THREAD

**Issue by zyoohv** [yjxiong/temporal-segment-networks#61]
I tried to compile dense_flow with opencv_3.1.0, but it seems that there are some wrong to me.

Could you tell me the version of Opencv you used ?

best wish.

**Comment by zyoohv** [comment]
and this is the error when i run command: make

`
[  7%] Building CXX object CMakeFiles/denseflow.dir/src/common.cpp.o
In file included from /home/zyoohv/dense_flow/src/common.cpp:5:0:
/home/zyoohv/dense_flow/include/common.h:23:20: error: ‘vector’ has not been declared
                    vector<uchar>& encoded_x, vector<uchar>& encoded_y,
                    ^
/home/zyoohv/dense_flow/include/common.h:23:26: error: expected ‘,’ or ‘...’ before ‘<’ token
                    vector<uchar>& encoded_x, vector<uchar>& encoded_y,
                          ^
/home/zyoohv/dense_flow/include/common.h:36:18: error: variable or field ‘writeImages’ declared void
 void writeImages(vector<vector<uchar>> images, string name_temp);
                  ^
/home/zyoohv/dense_flow/include/common.h:36:18: error: ‘vector’ was not declared in this scope
/home/zyoohv/dense_flow/include/common.h:36:18: note: suggested alternative:
In file included from /usr/include/c++/5/vector:64:0,
                 from /usr/include/c++/5/bits/random.h:34,
                 from /usr/include/c++/5/random:49,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:53,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/video/tracking.hpp:47,
                 from /home/zyoohv/dense_flow/include/common.h:10,
                 from /home/zyoohv/dense_flow/src/common.cpp:5:
/usr/include/c++/5/bits/stl_vector.h:214:11: note:   ‘std::vector’
     class vector : protected _Vector_base<_Tp, _Alloc>
           ^
In file included from /home/zyoohv/dense_flow/src/common.cpp:5:0:
/home/zyoohv/dense_flow/include/common.h:36:25: error: ‘vector’ was not declared in this scope
 void writeImages(vector<vector<uchar>> images, string name_temp);
                         ^
/home/zyoohv/dense_flow/include/common.h:36:25: note: suggested alternative:
In file included from /usr/include/c++/5/vector:64:0,
                 from /usr/include/c++/5/bits/random.h:34,
                 from /usr/include/c++/5/random:49,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:53,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/video/tracking.hpp:47,
                 from /home/zyoohv/dense_flow/include/common.h:10,
                 from /home/zyoohv/dense_flow/src/common.cpp:5:
/usr/include/c++/5/bits/stl_vector.h:214:11: note:   ‘std::vector’
     class vector : protected _Vector_base<_Tp, _Alloc>
           ^
In file included from /home/zyoohv/dense_flow/src/common.cpp:5:0:
/home/zyoohv/dense_flow/include/common.h:36:37: error: expected primary-expression before ‘>>’ token
 void writeImages(vector<vector<uchar>> images, string name_temp);
                                     ^
/home/zyoohv/dense_flow/include/common.h:36:40: error: ‘images’ was not declared in this scope
 void writeImages(vector<vector<uchar>> images, string name_temp);
                                        ^
/home/zyoohv/dense_flow/include/common.h:36:48: error: ‘string’ was not declared in this scope
 void writeImages(vector<vector<uchar>> images, string name_temp);
                                                ^
/home/zyoohv/dense_flow/include/common.h:36:48: note: suggested alternatives:
In file included from /usr/include/c++/5/string:39:0,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:53,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/video/tracking.hpp:47,
                 from /home/zyoohv/dense_flow/include/common.h:10,
                 from /home/zyoohv/dense_flow/src/common.cpp:5:
/usr/include/c++/5/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
   typedef basic_string<char>    string;   
                                 ^
/usr/include/c++/5/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
/home/zyoohv/dense_flow/src/common.cpp:33:20: error: ‘vector’ has not been declared
                    vector<uchar>& encoded_x, vector<uchar>& encoded_y,
                    ^
/home/zyoohv/dense_flow/src/common.cpp:33:26: error: expected ‘,’ or ‘...’ before ‘<’ token
                    vector<uchar>& encoded_x, vector<uchar>& encoded_y,
                          ^
/home/zyoohv/dense_flow/src/common.cpp: In function ‘void encodeFlowMap(const cv::Mat&, const cv::Mat&, int)’:
/home/zyoohv/dense_flow/src/common.cpp:39:25: error: ‘bound’ was not declared in this scope
                        -bound, bound);
                         ^
/home/zyoohv/dense_flow/src/common.cpp:41:9: error: ‘to_jpg’ was not declared in this scope
     if (to_jpg) {
         ^
/home/zyoohv/dense_flow/src/common.cpp:42:38: error: ‘encoded_x’ was not declared in this scope
         imencode(".jpg", flow_img_x, encoded_x);
                                      ^
/home/zyoohv/dense_flow/src/common.cpp:43:38: error: ‘encoded_y’ was not declared in this scope
         imencode(".jpg", flow_img_y, encoded_y);
                                      ^
/home/zyoohv/dense_flow/src/common.cpp:45:9: error: ‘encoded_x’ was not declared in this scope
         encoded_x.resize(flow_img_x.total());
         ^
/home/zyoohv/dense_flow/src/common.cpp:46:9: error: ‘encoded_y’ was not declared in this scope
         encoded_y.resize(flow_img_y.total());
         ^
/home/zyoohv/dense_flow/src/common.cpp: At global scope:
/home/zyoohv/dense_flow/src/common.cpp:52:18: error: variable or field ‘writeImages’ declared void
 void writeImages(vector<vector<uchar>> images, string name_temp){
                  ^
/home/zyoohv/dense_flow/src/common.cpp:52:18: error: ‘vector’ was not declared in this scope
/home/zyoohv/dense_flow/src/common.cpp:52:18: note: suggested alternative:
In file included from /usr/include/c++/5/vector:64:0,
                 from /usr/include/c++/5/bits/random.h:34,
                 from /usr/include/c++/5/random:49,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:53,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/video/tracking.hpp:47,
                 from /home/zyoohv/dense_flow/include/common.h:10,
                 from /home/zyoohv/dense_flow/src/common.cpp:5:
/usr/include/c++/5/bits/stl_vector.h:214:11: note:   ‘std::vector’
     class vector : protected _Vector_base<_Tp, _Alloc>
           ^
/home/zyoohv/dense_flow/src/common.cpp:52:25: error: ‘vector’ was not declared in this scope
 void writeImages(vector<vector<uchar>> images, string name_temp){
                         ^
/home/zyoohv/dense_flow/src/common.cpp:52:25: note: suggested alternative:
In file included from /usr/include/c++/5/vector:64:0,
                 from /usr/include/c++/5/bits/random.h:34,
                 from /usr/include/c++/5/random:49,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:53,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/video/tracking.hpp:47,
                 from /home/zyoohv/dense_flow/include/common.h:10,
                 from /home/zyoohv/dense_flow/src/common.cpp:5:
/usr/include/c++/5/bits/stl_vector.h:214:11: note:   ‘std::vector’
     class vector : protected _Vector_base<_Tp, _Alloc>
           ^
/home/zyoohv/dense_flow/src/common.cpp:52:37: error: expected primary-expression before ‘>>’ token
 void writeImages(vector<vector<uchar>> images, string name_temp){
                                     ^
/home/zyoohv/dense_flow/src/common.cpp:52:40: error: ‘images’ was not declared in this scope
 void writeImages(vector<vector<uchar>> images, string name_temp){
                                        ^
/home/zyoohv/dense_flow/src/common.cpp:52:48: error: ‘string’ was not declared in this scope
 void writeImages(vector<vector<uchar>> images, string name_temp){
                                                ^
/home/zyoohv/dense_flow/src/common.cpp:52:48: note: suggested alternatives:
In file included from /usr/include/c++/5/string:39:0,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:53,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/video/tracking.hpp:47,
                 from /home/zyoohv/dense_flow/include/common.h:10,
                 from /home/zyoohv/dense_flow/src/common.cpp:5:
/usr/include/c++/5/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
   typedef basic_string<char>    string;   
                                 ^
/usr/include/c++/5/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
CMakeFiles/denseflow.dir/build.make:62: recipe for target 'CMakeFiles/denseflow.dir/src/common.cpp.o' failed
make[2]: *** [CMakeFiles/denseflow.dir/src/common.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/denseflow.dir/all' failed
make[1]: *** [CMakeFiles/denseflow.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by zyoohv** [comment]
And these are the errors when i run command: make

[  7%] Building CXX object CMakeFiles/denseflow.dir/src/common.cpp.o
In file included from /home/zyoohv/dense_flow/src/common.cpp:5:0:
/home/zyoohv/dense_flow/include/common.h:23:20: error: ‘vector’ has not been declared
                    vector<uchar>& encoded_x, vector<uchar>& encoded_y,
                    ^
/home/zyoohv/dense_flow/include/common.h:23:26: error: expected ‘,’ or ‘...’ before ‘<’ token
                    vector<uchar>& encoded_x, vector<uchar>& encoded_y,
                          ^
/home/zyoohv/dense_flow/include/common.h:36:18: error: variable or field ‘writeImages’ declared void
 void writeImages(vector<vector<uchar>> images, string name_temp);
                  ^
/home/zyoohv/dense_flow/include/common.h:36:18: error: ‘vector’ was not declared in this scope
/home/zyoohv/dense_flow/include/common.h:36:18: note: suggested alternative:
In file included from /usr/include/c++/5/vector:64:0,
                 from /usr/include/c++/5/bits/random.h:34,
                 from /usr/include/c++/5/random:49,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:53,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/video/tracking.hpp:47,
                 from /home/zyoohv/dense_flow/include/common.h:10,
                 from /home/zyoohv/dense_flow/src/common.cpp:5:
/usr/include/c++/5/bits/stl_vector.h:214:11: note:   ‘std::vector’
     class vector : protected _Vector_base<_Tp, _Alloc>
           ^
In file included from /home/zyoohv/dense_flow/src/common.cpp:5:0:
/home/zyoohv/dense_flow/include/common.h:36:25: error: ‘vector’ was not declared in this scope
 void writeImages(vector<vector<uchar>> images, string name_temp);
                         ^
/home/zyoohv/dense_flow/include/common.h:36:25: note: suggested alternative:
In file included from /usr/include/c++/5/vector:64:0,
                 from /usr/include/c++/5/bits/random.h:34,
                 from /usr/include/c++/5/random:49,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:53,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/video/tracking.hpp:47,
                 from /home/zyoohv/dense_flow/include/common.h:10,
                 from /home/zyoohv/dense_flow/src/common.cpp:5:
/usr/include/c++/5/bits/stl_vector.h:214:11: note:   ‘std::vector’
     class vector : protected _Vector_base<_Tp, _Alloc>
           ^
In file included from /home/zyoohv/dense_flow/src/common.cpp:5:0:
/home/zyoohv/dense_flow/include/common.h:36:37: error: expected primary-expression before ‘>>’ token
 void writeImages(vector<vector<uchar>> images, string name_temp);
                                     ^
/home/zyoohv/dense_flow/include/common.h:36:40: error: ‘images’ was not declared in this scope
 void writeImages(vector<vector<uchar>> images, string name_temp);
                                        ^
/home/zyoohv/dense_flow/include/common.h:36:48: error: ‘string’ was not declared in this scope
 void writeImages(vector<vector<uchar>> images, string name_temp);
                                                ^
/home/zyoohv/dense_flow/include/common.h:36:48: note: suggested alternatives:
In file included from /usr/include/c++/5/string:39:0,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:53,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/video/tracking.hpp:47,
                 from /home/zyoohv/dense_flow/include/common.h:10,
                 from /home/zyoohv/dense_flow/src/common.cpp:5:
/usr/include/c++/5/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
   typedef basic_string<char>    string;   
                                 ^
/usr/include/c++/5/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
/home/zyoohv/dense_flow/src/common.cpp:33:20: error: ‘vector’ has not been declared
                    vector<uchar>& encoded_x, vector<uchar>& encoded_y,
                    ^
/home/zyoohv/dense_flow/src/common.cpp:33:26: error: expected ‘,’ or ‘...’ before ‘<’ token
                    vector<uchar>& encoded_x, vector<uchar>& encoded_y,
                          ^
/home/zyoohv/dense_flow/src/common.cpp: In function ‘void encodeFlowMap(const cv::Mat&, const cv::Mat&, int)’:
/home/zyoohv/dense_flow/src/common.cpp:39:25: error: ‘bound’ was not declared in this scope
                        -bound, bound);
                         ^
/home/zyoohv/dense_flow/src/common.cpp:41:9: error: ‘to_jpg’ was not declared in this scope
     if (to_jpg) {
         ^
/home/zyoohv/dense_flow/src/common.cpp:42:38: error: ‘encoded_x’ was not declared in this scope
         imencode(".jpg", flow_img_x, encoded_x);
                                      ^
/home/zyoohv/dense_flow/src/common.cpp:43:38: error: ‘encoded_y’ was not declared in this scope
         imencode(".jpg", flow_img_y, encoded_y);
                                      ^
/home/zyoohv/dense_flow/src/common.cpp:45:9: error: ‘encoded_x’ was not declared in this scope
         encoded_x.resize(flow_img_x.total());
         ^
/home/zyoohv/dense_flow/src/common.cpp:46:9: error: ‘encoded_y’ was not declared in this scope
         encoded_y.resize(flow_img_y.total());
         ^
/home/zyoohv/dense_flow/src/common.cpp: At global scope:
/home/zyoohv/dense_flow/src/common.cpp:52:18: error: variable or field ‘writeImages’ declared void
 void writeImages(vector<vector<uchar>> images, string name_temp){
                  ^
/home/zyoohv/dense_flow/src/common.cpp:52:18: error: ‘vector’ was not declared in this scope
/home/zyoohv/dense_flow/src/common.cpp:52:18: note: suggested alternative:
In file included from /usr/include/c++/5/vector:64:0,
                 from /usr/include/c++/5/bits/random.h:34,
                 from /usr/include/c++/5/random:49,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:53,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/video/tracking.hpp:47,
                 from /home/zyoohv/dense_flow/include/common.h:10,
                 from /home/zyoohv/dense_flow/src/common.cpp:5:
/usr/include/c++/5/bits/stl_vector.h:214:11: note:   ‘std::vector’
     class vector : protected _Vector_base<_Tp, _Alloc>
           ^
/home/zyoohv/dense_flow/src/common.cpp:52:25: error: ‘vector’ was not declared in this scope
 void writeImages(vector<vector<uchar>> images, string name_temp){
                         ^
/home/zyoohv/dense_flow/src/common.cpp:52:25: note: suggested alternative:
In file included from /usr/include/c++/5/vector:64:0,
                 from /usr/include/c++/5/bits/random.h:34,
                 from /usr/include/c++/5/random:49,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:53,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/video/tracking.hpp:47,
                 from /home/zyoohv/dense_flow/include/common.h:10,
                 from /home/zyoohv/dense_flow/src/common.cpp:5:
/usr/include/c++/5/bits/stl_vector.h:214:11: note:   ‘std::vector’
     class vector : protected _Vector_base<_Tp, _Alloc>
           ^
/home/zyoohv/dense_flow/src/common.cpp:52:37: error: expected primary-expression before ‘>>’ token
 void writeImages(vector<vector<uchar>> images, string name_temp){
                                     ^
/home/zyoohv/dense_flow/src/common.cpp:52:40: error: ‘images’ was not declared in this scope
 void writeImages(vector<vector<uchar>> images, string name_temp){
                                        ^
/home/zyoohv/dense_flow/src/common.cpp:52:48: error: ‘string’ was not declared in this scope
 void writeImages(vector<vector<uchar>> images, string name_temp){
                                                ^
/home/zyoohv/dense_flow/src/common.cpp:52:48: note: suggested alternatives:
In file included from /usr/include/c++/5/string:39:0,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:53,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/video/tracking.hpp:47,
                 from /home/zyoohv/dense_flow/include/common.h:10,
                 from /home/zyoohv/dense_flow/src/common.cpp:5:
/usr/include/c++/5/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
   typedef basic_string<char>    string;   
                                 ^
/usr/include/c++/5/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
CMakeFiles/denseflow.dir/build.make:62: recipe for target 'CMakeFiles/denseflow.dir/src/common.cpp.o' failed
make[2]: *** [CMakeFiles/denseflow.dir/src/common.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/denseflow.dir/all' failed
make[1]: *** [CMakeFiles/denseflow.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yjxiong** [comment]
We use OpenCV 2.4. It is suggested in README to use build_all.sh to build the whole project. 

To use your OpenCV installation, it has to be compiled with VideoIO suppprt.

**Comment by KeyKy** [comment]
have you solve your problem? @zyoohv

**Comment by KeyKy** [comment]
[ 7%] Building CXX object CMakeFiles/denseflow.dir/src/common.cpp.o
In file included from /home/zyoohv/dense_flow/src/common.cpp:5:0:
/home/zyoohv/dense_flow/include/common.h:23:20: error: ‘vector’ has not been declared
vector& encoded_x, vector& encoded_y

@yjxiong I use opencv2.9.4, but also get this error
