### ISSUE TITLE
Error while building dense flow

### ISSUE THREAD

**Issue by songjun54cm** [yjxiong/temporal-segment-networks#62]
when I try to build dense flow, the following error occurred and I have no idea to fix it.

```
[ 50%] Building CXX object CMakeFiles/extract_cpu.dir/tools/extract_flow.cpp.o
make[2]: *** No rule to make target `/lib/libzip.so', needed by `extract_cpu'.  Stop.
make[1]: *** [CMakeFiles/extract_cpu.dir/all] Error 2
make: *** [all] Error 2
```

while build the code I use those following commands:
```
$cmake .. -DCMAKE_C_COMPILER=${gcc482}/gcc \
-DCMAKE_CXX_COMPILER=${gcc482}/g++ \
-DCUDA_USE_STATIC_CUDA_RUNTIME=OFF \
-DLIBZIP_LIBRARY=${libzip_dir}/lib/libzip.so -DPYTHON_LIBRARY=${anaconda_home}/lib/libpython2.7.so.1.0

$make
```

Does anyone has any idea what is wrong?

**Comment by yjxiong** [comment]
`/lib/libzip.so`

This one should not appear in your build command. Use apt-get to install libzip instead.

It is stated in the README that it is the best to use `build_all.sh` script to build these libraries.
