### ISSUE TITLE
Error building denseflow using build script

### ISSUE THREAD

**Issue by dakshvar22** [yjxiong/temporal-segment-networks#63]
Hi,

I am running the build script given in the repository to install the dependencies. I am done with OpenCV installation, but while denseflow setup I run into this error - 

`[ 78%] Linking CXX executable extract_cpu
[ 85%] Linking CXX executable extract_gpu
[ 92%] Linking CXX executable extract_warp_gpu
/usr/bin/ld: cannot find -lQt5::Core
/usr/bin/ld: cannot find -lQt5::Gui
/usr/bin/ld: cannot find -lQt5::Widgets
/usr/bin/ld: cannot find -lQt5::Test
/usr/bin/ld: cannot find -lQt5::Concurrent
/usr/bin/ld: cannot find -lQt5::OpenGL
collect2: error: ld returned 1 exit status
CMakeFiles/extract_cpu.dir/build.make:156: recipe for target 'extract_cpu' failed
make[2]: *** [extract_cpu] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/extract_cpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_cpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lQt5::Core
/usr/bin/ld: cannot find -lQt5::Gui
/usr/bin/ld: cannot find -lQt5::Widgets
/usr/bin/ld: cannot find -lQt5::Test
/usr/bin/ld: cannot find -lQt5::Concurrent
/usr/bin/ld: cannot find -lQt5::OpenGL
collect2: error: ld returned 1 exit status
CMakeFiles/extract_gpu.dir/build.make:156: recipe for target 'extract_gpu' failed
make[2]: *** [extract_gpu] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/extract_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_gpu.dir/all] Error 2
/usr/bin/ld: cannot find -lQt5::Core
/usr/bin/ld: cannot find -lQt5::Gui
/usr/bin/ld: cannot find -lQt5::Widgets
/usr/bin/ld: cannot find -lQt5::Test
/usr/bin/ld: cannot find -lQt5::Concurrent
/usr/bin/ld: cannot find -lQt5::OpenGL
collect2: error: ld returned 1 exit status
CMakeFiles/extract_warp_gpu.dir/build.make:156: recipe for target 'extract_warp_gpu' failed
make[2]: *** [extract_warp_gpu] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/extract_warp_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_warp_gpu.dir/all] Error 2
[100%] Linking CXX shared library libpydenseflow.so
/usr/bin/ld: cannot find -lQt5::Core
/usr/bin/ld: cannot find -lQt5::Gui
/usr/bin/ld: cannot find -lQt5::Widgets
/usr/bin/ld: cannot find -lQt5::Test
/usr/bin/ld: cannot find -lQt5::Concurrent
/usr/bin/ld: cannot find -lQt5::OpenGL
collect2: error: ld returned 1 exit status
CMakeFiles/pydenseflow.dir/build.make:152: recipe for target 'libpydenseflow.so' failed
make[2]: *** [libpydenseflow.so] Error 1
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/pydenseflow.dir/all' failed
make[1]: *** [CMakeFiles/pydenseflow.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Failed to build Dense Flow. Please check the logs above.
`

I installed qt5 using command - sudo apt-get install qt5-default . Am running this on AWS Ubuntu 16.04 with cuda 8. Any suggestions?

**Comment by yjxiong** [comment]
Dense flow does not require Qt by itself. If you can install OpenCV there should be no problem. Can you check your paths.?

**Comment by yuweijiang** [comment]
dense_warp_flow_gpu.cpp:(.text+0x1bbf): undefined reference to `cv::SURF::SURF(double, int, int, bool, bool)'
dense_warp_flow_gpu.cpp:(.text+0x1beb): undefined reference to `cv::SURF::SURF(double, int, int, bool, bool)'
libdenseflow.a(dense_warp_flow_gpu.cpp.o): In function `cv::SURF::~SURF()':
dense_warp_flow_gpu.cpp:(.text._ZN2cv4SURFD1Ev[_ZN2cv4SURFD1Ev]+0xf): undefined reference to `vtable for cv::SURF'
dense_warp_flow_gpu.cpp:(.text._ZN2cv4SURFD1Ev[_ZN2cv4SURFD1Ev]+0x2d): undefined reference to `vtable for cv::SURF'
dense_warp_flow_gpu.cpp:(.text._ZN2cv4SURFD1Ev[_ZN2cv4SURFD1Ev]+0x3b): undefined reference to `vtable for cv::SURF'
dense_warp_flow_gpu.cpp:(.text._ZN2cv4SURFD1Ev[_ZN2cv4SURFD1Ev]+0x51): undefined reference to `VTT for cv::SURF'
collect2: error: ld returned 1 exit status
make[2]: *** [extract_warp_gpu] Error 1
make[1]: *** [CMakeFiles/extract_warp_gpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/weijiang/experiments/temporal-segment-networks-master/lib/dense_flow/src/py_denseflow.cpp:18:39: fatal error: opencv2/nonfree/nonfree.hpp: No such file or directory
 #include "opencv2/nonfree/nonfree.hpp"
                                       ^
compilation terminated.
make[2]: *** [CMakeFiles/pydenseflow.dir/src/py_denseflow.cpp.o] Error 1
make[1]: *** [CMakeFiles/pydenseflow.dir/all] Error 2
make: *** [all] Error 2
Failed to build Dense Flow. Please check the logs above.

Any suggestions? do i have to change the path in the Cmakelists.txt ?

**Comment by yjxiong** [comment]
If you are using the bundled OpenCV it should have the nonfree module. Please see if you using the correct version.

**Comment by yuweijiang** [comment]
you are right! thank you! @yjxiong

**Comment by sherleens** [comment]
Hi, I have met the same problem: g++ main.cpp -o main `pkg-config --cflags --libs opencv`. And I checked my opencv version (that is 2.4.9). Is there any solution?

**Comment by ASMIftekhar** [comment]
> Hi, I have met the same problem: fatal error: opencv2/nonfree/nonfree.hpp: No such file or directory. And I checked my opencv version (that is 2.4.9). Is there any solution?

Same problem. Does anyone have any solution?
