### ISSUE TITLE
failed to build opencv with the build_all script

### ISSUE THREAD

**Issue by yuweijiang** [yjxiong/temporal-segment-networks#64]
^      [7/1620]
/home/weijiang/experiments/temporal-segment-networks-master/3rd-party/opencv-2.4.12/modules/gpu/src/cuda/safe_call.hpp:84:43: note: in definition of macro ‘nppSa
feCall’
 #define nppSafeCall(expr)  ___nppSafeCall(expr, __FILE__, __LINE__, CV_Func)
                                           ^
/home/weijiang/experiments/temporal-segment-networks-master/3rd-party/opencv-2.4.12/modules/gpu/src/graphcuts.cpp:274:146: error: ‘nppiGraphcut8_32f8u’ was not d
eclared in this scope
             static_cast<int>(terminals.step), static_cast<int>(leftTransp.step), sznpp, labels.ptr<Npp8u>(), static_cast<int>(labels.step), state) );
                                                                                                                                                  ^
/home/weijiang/experiments/temporal-segment-networks-master/3rd-party/opencv-2.4.12/modules/gpu/src/cuda/safe_call.hpp:84:43: note: in definition of macro ‘nppSa
feCall’
 #define nppSafeCall(expr)  ___nppSafeCall(expr, __FILE__, __LINE__, CV_Func)
                                           ^
make[2]: *** [modules/gpu/CMakeFiles/opencv_gpu.dir/src/graphcuts.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [modules/gpu/CMakeFiles/opencv_gpu.dir/all] Error 2
make: *** [all] Error 2
Failed to build OpenCV. Please check the logs above.

**Comment by yjxiong** [comment]
Which CUDA version are you using?

**Comment by yuweijiang** [comment]
8.0

**Comment by yjxiong** [comment]
Try OpenCV 2.4.13?

**Comment by yuweijiang** [comment]
my computer have opencv 2.4.8, and i follow the command to bash the build_all.sh, try the opencv 2.4.12

**Comment by yjxiong** [comment]
Please try use 2.14.13 instead of the 2.4.12 version.

**Comment by yuweijiang** [comment]
[ 66%] [ 66%] Building CXX object modules/gpu/CMakeFiles/opencv_gpu.dir/src/video_writer.cpp.o
[ 66%] Building CXX object modules/gpu/CMakeFiles/opencv_gpu.dir/src/arithm.cpp.o
Building CXX object modules/gpu/CMakeFiles/opencv_gpu.dir/src/video_reader.cpp.o
Linking CXX shared library ../../lib/libopencv_gpu.so
[ 70%] Built target opencv_gpu
make: *** [all] Error 2
Failed to build OpenCV. Please check the logs above.

i try use opencv2.4.13 instead of the 2.4.12, it failed.

**Comment by yjxiong** [comment]
Googling `nppGraphCut OpenCV` gives me this:

http://answers.opencv.org/question/95148/cudalegacy-not-compile-nppigraphcut-missing/

It should fix your problem

**Comment by fetorres** [comment]
I can confirm that the change to graphcuts.cpp worked for me when I was making CUDA 8 work.  Sorry, I had not yet posted that information for others to see :(  It would be good to add a comment about this on the README.

I have worked some on moving everything to opencv3 and python 3, but there are a lot of dependencies.  I would be interested to know if others are also interested in that update route.

**Comment by yjxiong** [comment]
@fetorres , Thanks for posting!

FYI, there is an OpenCV 3.1 branch of DenseFlow contributed by other users. 
https://github.com/yjxiong/dense_flow/commits/opencv-3.1

The most convolved part in migration is perhaps the DenseFlow. Hope this can help you.

**Comment by yuweijiang** [comment]
thank you , the method can work!@yjxiong
