### ISSUE TITLE
No module named _caffe

### ISSUE THREAD

**Issue by yuweijiang** [yjxiong/temporal-segment-networks#66]
yuweijiang@hcp-ca-04:~/experiments/temporal-segment-networks$ python tools/eval_net.py ucf101 1 rgb videoout/v_ApplyEyeMakeup_g04_c01 models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel --num_worker 2 --save_scores SCORE_FILE                                           
Namespace(caffe_path='./lib/caffe-action/', dataset='ucf101', flow_x_prefix='flow_x_', flow_y_prefix='flow_y_', frame_path='videoout', gpus=None, modality='rgb', net_proto='models/ucf101/tsn_bn_inception_rgb_deploy.prototxt', net_weights='models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel', num_frame_per_video=25, num_worker=2, rgb_prefix='img_', save_scores='SCORE_FILE', split=1)
Traceback (most recent call last):
  File "tools/eval_net.py", line 38, in <module>
    from pyActionRecog.action_caffe import CaffeNet
  File "./pyActionRecog/action_caffe.py", line 4, in <module>
    import caffe
  File "./lib/caffe-action/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "./lib/caffe-action/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: No module named _caffe

I build successfuly with the build_all.sh.when I use the python eval_net.py ,it failed.Any suggestions?

**Comment by fetorres** [comment]
There should be a link called "_caffe.so" in your ./lib/caffe-action/python/caffe directory.
Could you perform "ls -al" of that directory and show the results?

The link is to temporal-segment-networks/lib/caffe-action/build/lib/_caffe.so
If it is missing, maybe it is worth it to try adding it manually?

**Comment by yjxiong** [comment]
@yuweijiang Please check whether you have built the Python interfaces for the bundled Caffe. It requires boost version 1.55 up, which will be installed in `build_all.sh`. But on some Ubuntu systems, one has to first manually remove libboost-all-dev then install libboost1.55-all-dev or higher ones.

Also, please track your problems in one issue instead of spamming a lot of issues.
