### ISSUE TITLE
Test Image number

### ISSUE THREAD

**Issue by double-vane** [yjxiong/temporal-segment-networks#67]
I see  25 RGB frames or optical flow stacks were sampled for testing, but In the train_val.prototxt, you still used segment temporal in video, so I'm  wondering how it is tested？

In the paper：
we follow the testing scheme of the original two-stream ConvNets [1], where we sample **25** RGB frames or optical ow stacks from the action videos. Meanwhile, we crop 4 corners and 1 center, and their horizontal 
ipping from the sampled frames to evaluate the ConvNets. For the fusion of spatial and temporal stream networks,

In the train_val.prototxt:
layer {
  name: "data"
  type: "VideoData"
  top: "data"
  top: "label"
  video_data_param {
    source: "data/ucf101_rgb_val_split_3.txt"
    batch_size: 1
    new_length: 1
    **num_segments: 3**
    modality: RGB
    name_pattern: "img_%05d.jpg"
  }
  transform_param{
    crop_size: 224
    mirror: false
    mean_value: [104, 117, 123, 104, 117, 123, 104, 117, 123]
  }
  include: { phase: TEST }
}

**Comment by yjxiong** [comment]
Follow the test instructions in README. Caffe's on the fly testing is only for monitoring the training process.

**Comment by double-vane** [comment]
Thank you very much!
I'll read it again
