### ISSUE TITLE
Fine Tuning the model

### ISSUE THREAD

**Issue by dakshvar22** [yjxiong/temporal-segment-networks#70]
Hi,
I want to fine tune the model(specifically the bn_inception_anet_2016_temporal.caffemodel.v5 model) which is given as part of your other repository(Activity Net Repo). I want to fine tune only the last fully connected layers on my own dataset. While I can successfully prepare the dataset and make it ready for training, how do I specify the 'fine tuning' part(freezing of weights) in the caffe solver files. 

Kindly help.

Thanks

**Comment by dakshvar22** [comment]
@yjxiong Any ideas on the above question? :)

**Comment by fetorres** [comment]
Hello,

One way to do it is to edit the prototxt file, changing every instance of lr_mult and decay_mult to 0 in every layer you want to freeze.

**Comment by yjxiong** [comment]
I think the solution is just as @fetorres kindly described.
