### ISSUE TITLE
Combining the RGB and Flow model

### ISSUE THREAD

**Issue by dakshvar22** [yjxiong/temporal-segment-networks#71]
Hi,

In the training regime, you have shown how to train on specific modalities i.e. RGB or Flow images. In the original paper you seem to have used both the models together(spatial and temporal convnet) to arrive at the final results. Can you explain how can we do that. Currently, I have two separate model snapshots, one for RGB and other for flow images.

Kindly help.

Thanks.

**Comment by yjxiong** [comment]
Please see this

https://github.com/yjxiong/temporal-segment-networks#video-level-testing
