### ISSUE TITLE
ImportError: ./lib/caffe-action/python/caffe/_caffe.so: undefined symbol: _ZN5caffe4mtx_E

### ISSUE THREAD

**Issue by Marchong** [yjxiong/temporal-segment-networks#73]
Hi,Thank you for your work first!
when i run the code like below,it makes some mistake,and i didn't how it happened , can you give me some suggestion about this ? Thank you .

zhou@Gaming:~/temporal-segment-networks-master$ sudo python tools/eval_net.py ucf101 1 rgb /home/zhou/temporal-segment-networks-master/Dataset/flows/ucf101  models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel  --num_worker 1 --save_scores home/zhou/temporal-segment-networks-master/Dataset/defen
[sudo] password for zhou: 
Namespace(caffe_path='./lib/caffe-action/', dataset='ucf101', flow_x_prefix='flow_x_', flow_y_prefix='flow_y_', frame_path='/home/zhou/temporal-segment-networks-master/Dataset/flows/ucf101', gpus=None, modality='rgb', net_proto='models/ucf101/tsn_bn_inception_rgb_deploy.prototxt', net_weights='models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel', num_frame_per_video=25, num_worker=1, rgb_prefix='img_', save_scores='home/zhou/temporal-segment-networks-master/Dataset/defen', split=1)
Traceback (most recent call last):
  File "tools/eval_net.py", line 38, in <module>
    from pyActionRecog.action_caffe import CaffeNet
  File "./pyActionRecog/action_caffe.py", line 4, in <module>
    import caffe
  File "./lib/caffe-action/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "./lib/caffe-action/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: ./lib/caffe-action/python/caffe/_caffe.so: undefined symbol: _ZN5caffe4mtx_E

**Comment by yjxiong** [comment]
`./lib/caffe-action/python/caffe/_caffe.so: undefined symbol: _ZN5caffe4mtx_E` 

Do you have multiple versions of Caffe installed and happen to have them in the linker path?

**Comment by Marchong** [comment]
yeah ,I had  make  a official latest vision caffe before it,should i  make clean  it ?

**Comment by yjxiong** [comment]
No idea. Just make sure you `_caffe.so` is linked with the correct one. This can be checked with commands like `ldd _caffe.so`.

**Comment by Marchong** [comment]
Thank you so much ! i just run the build_all.sh again ,now it's working !
but i just have another question ,if i had a TitanX only ,is the OpenMPI is necessary to install ?

**Comment by yjxiong** [comment]
No. But please read the README carefully about the batchsize settings if you want to run training.

**Comment by Marchong** [comment]
Thank you!
