### ISSUE TITLE
newvideo_data_layer with mpi support

### ISSUE THREAD

**Issue by zhujiagang** [yjxiong/temporal-segment-networks#74]
Hi yjxiong. I copy your "video_data_layer.cpp" and modify it a little bit to meet my demand, with a new name "newvideo_data_layer.cpp".  It has same header with your "video_data_layer.cpp" 
```... ...
#include "caffe/data_layers.hpp"
#include "caffe/layer.hpp"
#include "caffe/proto/caffe.pb.h"
#include "caffe/util/io.hpp"
#include "caffe/util/math_functions.hpp"
#include "caffe/util/rng.hpp"

#ifdef USE_MPI
#include "mpi.h"
#include <boost/filesystem.hpp>
using namespace boost::filesystem;
#endif
```
I run it on two Titanx gpu with mpi on, but it reminds me the warning that
```
mpirun was unable to launch the specified application as it could not find an executable:
Executable:
Node: user-SYS-7048GR-TR
while attempting to start process rank 0.
--------------------------------------------------------------------------
2 total processes failed to start
```
Then it turns to one gpu and goes on training. My new layer works well without mpi on. It seems that my code isn't compatible with mpi somewhere.
I also test your "video_data_layer" with your prototxt, it works well.
```
I0329 13:37:14.526973  4150 common.cpp:53] Running parallel training with MPI support!
I0329 13:37:14.529207  4151 common.cpp:53] Running parallel training with MPI support!
Setting device 0
Setting device 1
```
Where can I fix or add something to make my "newvideo_data_layer" work with mpi?

**Comment by yjxiong** [comment]
`mpirun was unable to launch the specified application as it could not find an executable:`

This means your launching command supplies a non-existent location for the Caffe binary. It has nothing to do with your code. I suggest checking your lauching command, especially what is following the `mpirun`.

**Comment by zhujiagang** [comment]
Thank you, I have solved the problem by 
```
TOOLS=lib/caffe-action/build/install/bin

/usr/local/openmpi/bin/mpirun -np $N_GPU \   
$TOOLS/caffe train --solver=models/ucf101/gating_conv_fc_solver.prototxt  \
	--weights=models/gating_conv_fc_init.caffemodel 2>&1 | tee ${LOG_FILE}
```
just as you said.

**Comment by yjxiong** [comment]
Good to know.
