### ISSUE TITLE
Can not solve the problem"folders holding the extracted frames are all empty"

### ISSUE THREAD

**Issue by dphero** [yjxiong/temporal-segment-networks#75]
I try to remove all installed OpenCV libs using ($> sudo find / -name "*opencv*" -exec rm -rf {} \;) and run the build_all.sh again,there are no any errors and warnings in the In the process .but I still got some empty folders, Can you give me some suggestions,thank you very much @yjxiong

**Comment by yjxiong** [comment]
`cd` into `3rd-party/opencv-2.4.12/build/`. 
Run `cmake ..`. 
In its output, find the content about `VideoIO` and see if they are enabled.

**Comment by dphero** [comment]
I have solve the problem and found another cause of the problem 
I try running dence_flow on a single video file and get a Opencv error:NO GPU suppot
So I changed the extract_optical_flow.sh to use extract_cpu and got frames and optical flow images in folders
Using cpu to extracte frames and oprical flow need to take several days, do you know how to fix this OpenCV error that NO GPU Suppot. thank you very much

**Comment by yjxiong** [comment]
Do not use extract_cpu as TVL1 flow has no CPU interface in DenseFlow. 

No GPU support shows that CMake did not find your CUDA environment when building OpenCV. Please check you environment settings.

**Comment by dphero** [comment]
I found configure OpenCV using CMake with WITH_CUDA=ON can solve this problem,my last question is if I just have one GPU, How do I set this parameter  NUM_WORKER

**Comment by yjxiong** [comment]
1 then.

**Comment by dphero** [comment]
thanks again for your help, I don't have any more questions

**Comment by q252558242** [comment]
sorry to disturb you,can you tell me how you solve this problem in detail? I've faced the same problem and don't know how to using Cmake with_cuda=on.

**Comment by dphero** [comment]
`cd`  into `3rd-party/opencv-2.4.12/build/`
Run `cmke WITH_CUDA=ON ..`

**Comment by q252558242** [comment]
thanks a lot
