### ISSUE TITLE
Where to fuse two stream: fc node or softmax probablity?

### ISSUE THREAD

**Issue by zhujiagang** [yjxiong/temporal-segment-networks#77]
In your TSN paper, it says 

> the segmental consensus function is applied before the Softmax normalization.
> To test the models in compliance with their training, we fuse the prediction
> scores of 25 frames and different streams before Softmax normalization.

That is, all fusions (average or weighted) take place before Softmax layer. It uses last fc layer's output to make prediction. Code agrees with your TSN paper.
But in your another paper : Towards Good Practices for Very Deep Two-Stream ConvNets.
It says
>  For the fusion of spatial and temporal nets, we use a weighted linear combination of their prediction scores, where the weight is set as 2 for temporal net and 1 for spatial net.

I've read code of this paper.
```    avg_temporal_pred_fc8 = np.mean(temporal_prediction, axis=1)
avg_temporal_pred = softmax(avg_temporal_pred_fc8)
...  ...
    avg_spatial_pred_fc8 = np.mean(spatial_prediction, axis=1)
    avg_spatial_pred = softmax(avg_spatial_pred_fc8)

    # fused prediction (temporal:spatial = 2:1)
    fused_pred = np.array(avg_temporal_pred) * 2./3 + \
np.array(avg_spatial_pred) * 1./3
```
It is the softmax probablity that you use to fuse two tream.
Is the segment of TSN the reason that TSN is different from original two stream in the way of fusion?
But without softmax normalization, does the fusion of rgb fc node output and flow fc node output make sense? Their output seem to be not in the same level though they all substract their mean value in data layer respectively.

**Comment by yjxiong** [comment]
You are free to experiment base on your understanding. Please stop spamming the issues.

**Comment by zhujiagang** [comment]
Sorry to bother you and thanks for your kind reply. That's all my questions up to now.
