### ISSUE TITLE
get KeyError while testing

### ISSUE THREAD

**Issue by dphero** [yjxiong/temporal-segment-networks#79]
HI @yjxiong ,Thank you for providing the relevant code. I extracted frames and optical flow Images from 2600 videos in UCF-101 and I use following commands to test

`python tools/eval_net.py ucf101 1 rgb /home/hd/d/temporal-segment-networks/full_data/ucf101\
 models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception.caffemodel \
 --num_worker 1 --save_scores rgb_scores`

But after loading the model,I got a error:

Traceback (most recent call last):
  File "tools/eval_net.py", line 119, in <module>
    video_scores = map(eval_video, eval_video_list)
  File "tools/eval_net.py", line 69, in eval_video
    video_frame_path = f_info[0][vid]
KeyError: 'v_ApplyEyeMakeup_g01_c01'

I noticed that this category called ApplyEyeMakeup is not included in the 2600 videos I processed, The code seems to look for data in a specific order, So If I need to test my own data, do I have to first use the data to train the network? How can I use the model you provide to test a single video?

**Comment by yjxiong** [comment]
You have to add your own split in benchmark_db.py if you need customized test.

**Comment by actionderkokon** [comment]
hey， i met the same problem，and according to the build_all.sh, caffe is built successfully, do u solve the problem?
