### ISSUE TITLE
test accuracy on the split3 of RGB data of UCF101 is 100%

### ISSUE THREAD

**Issue by vra** [yjxiong/temporal-segment-networks#80]
Hi @yjxiong ,
I cloned this repo and use the models you trained to test the accuracy of RGB data on the split3 of UCF101. I use the script like this:  
`python tools/eval_net.py ucf101 3 rgb /data2/dataset/ucf101/jpegs_256 models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_1_tsn_rgb_reference_bn_inception    .caffemodel --num_worker 1 --save_scores /home/yunfeng/data10/logs/tsn_rgb3 2>&1 | tee ~/logs/tsn_rgb3.log`
The last part of output is like this:
```bash
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
Accuracy 100.00%
```
So I wonder if any thing wrong with my settings? Can you give me any advice? Thanks.

**Comment by yjxiong** [comment]
You are evaluating the reference model of split 1 on split 3

**Comment by vra** [comment]
I see 😂 sorry for silly question
