### ISSUE TITLE
failed to build caffe

### ISSUE THREAD

**Issue by dphero** [yjxiong/temporal-segment-networks#81]
I have been running this program on another computer without problems. but when i run build_all to build the caffe and dense_flow in my computer, I get the error like:

/home/hd/d/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp(107): error: too few arguments in function call

CMake Error at cuda_compile_generated_softmax_layer.cu.o.cmake:264 (message):
  Error generating file
  /home/hd/d/temporal-segment-networks/lib/caffe-action/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_softmax_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_softmax_layer.cu.o] 错误 1
1 error detected in the compilation of "/tmp/tmpxft_00001fad_00000000-5_cudnn_bn_layer.cpp4.ii".
CMake Error at cuda_compile_generated_cudnn_bn_layer.cu.o.cmake:264 (message):
  Error generating file
  /home/hd/d/temporal-segment-networks/lib/caffe-action/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_bn_layer.cu.o

make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_cudnn_bn_layer.cu.o] 错误 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] 错误 2
make: *** [all] 错误 2

can you give me some suggestions, thank you very much @yjxiong

**Comment by dphero** [comment]
i try to install cudnnv5.0 to fix the above problem and get another error:


/home/hd/d/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp: In function ‘const char* cudnnGetErrorString(cudnnStatus_t)’:
/home/hd/d/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp:21:10: warning: enumeration value ‘CUDNN_STATUS_RUNTIME_PREREQUISITE_MISSING’ not handled in switch [-Wswitch]
   switch (status) {
          ^
/home/hd/d/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp: In function ‘void caffe::cudnn::setConvolutionDesc(cudnnConvolutionStruct**, cudnnTensorDescriptor_t, cudnnFilterDescriptor_t, int, int, int, int)’:
/home/hd/d/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp:108:70: error: too few arguments to function ‘cudnnStatus_t cudnnSetConvolution2dDescriptor(cudnnConvolutionDescriptor_t, int, int, int, int, int, int, cudnnConvolutionMode_t, cudnnDataType_t)’
       pad_h, pad_w, stride_h, stride_w, 1, 1, CUDNN_CROSS_CORRELATION));
                                                                      ^
/home/hd/d/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp:15:28: note: in definition of macro ‘CUDNN_CHECK’
     cudnnStatus_t status = condition; \
                            ^
In file included from /home/hd/d/temporal-segment-networks/lib/caffe-action/include/caffe/util/cudnn.hpp:5:0,
                 from /home/hd/d/temporal-segment-networks/lib/caffe-action/include/caffe/util/device_alternate.hpp:40,
                 from /home/hd/d/temporal-segment-networks/lib/caffe-action/include/caffe/common.hpp:34,
                 from /home/hd/d/temporal-segment-networks/lib/caffe-action/include/caffe/blob.hpp:8,
                 from /home/hd/d/temporal-segment-networks/lib/caffe-action/include/caffe/layer.hpp:8,
                 from /home/hd/d/temporal-segment-networks/lib/caffe-action/src/caffe/layers/cudnn_bn_layer.cpp:8:
/usr/local/include/cudnn.h:500:27: note: declared here
 cudnnStatus_t CUDNNWINAPI cudnnSetConvolution2dDescriptor( cudnnConvolutionDescriptor_t convDesc,
                           ^
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/memory_data_layer.cpp.o] 错误 1
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/eltwise_layer.cpp.o] 错误 1
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/euclidean_loss_layer.cpp.o] 错误 1
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/sigmoid_layer.cpp.o] 错误 1
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/filter_layer.cpp.o] 错误 1
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/reduction_layer.cpp.o] 错误 1
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/lrn_layer.cpp.o] 错误 1
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/image_data_layer.cpp.o] 错误 1
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/relu_layer.cpp.o] 错误 1
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/im2col_layer.cpp.o] 错误 1
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/window_data_layer.cpp.o] 错误 1
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/cudnn_bn_layer.cpp.o] 错误 1
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/data_layer.cpp.o] 错误 1
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/layers/batch_reduction_layer.cpp.o] 错误 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by yjxiong** [comment]
Please check your cuDNN version. We use cuDNN v5.

**Comment by dphero** [comment]
I have installed the cudnn v 5.0,  but I got the same problem

**Comment by yjxiong** [comment]
Please check whether you have multiple versions of cuDNN. They could conflict with each other.

**Comment by dphero** [comment]
I tried using the following command to remove all previous versions and reinstall the cudnn5.0

`cd /usr/local/cuda/include
sudo rm cudnn.h
cd /usr/local/cuda/lib64
$ sudo rm libcudnn.*   `

But it still can not solve this problem.

**Comment by yjxiong** [comment]
Few things to do.

1. Run `rm -rf *` under `build/`. Then run CMake to get the full information of dependencies. In the output, find information related to cuDNN and see if there is anything wrong.

2. Do an exhaustive search for cuDNN related files. They may not be in the location you mentioned.

`error: too few arguments to function ‘cudnnStatus_t cudnnSetConvolution2dDescriptor(cudnnConvolutionDescriptor_t, int, int, int, int, int, int, cudnnConvolutionMode_t, cudnnDataType_t)’`
This error is definitely due to incorrect cuDNN version.

**Comment by dphero** [comment]
Thanks for your suggestion, according to your method, the code can run normally

**Comment by yjxiong** [comment]
So did this solve your problem?

**Comment by dphero** [comment]
I solved the above problem according to your method, but I met some new problem，I test the split1 and get  the accuracy 93.612521, but when I want to test split2 and split3, The code handles a part of the data and suggested an error:


`Check failed:error ==cudaSuccess (4 vs.0) unspecified launch failure`

Can you give me some suggestions?

**Comment by yjxiong** [comment]
Without context info I cannot guess what's happening. Please try following the instructions for testing and paste the full error log here.

**Comment by dphero** [comment]
Can you tell me which instructions  I should test

**Comment by yjxiong** [comment]
https://github.com/yjxiong/temporal-segment-networks#video-level-testing

**Comment by dphero** [comment]
I re-tested twice on split2  again and get the same error when handle different data


`.....
v_BabyCrawling_g02_c06 done
v_BabyCrawling_g02_c07 done
F0415 15:57:44.536542 27311 math_functions.cpp:81] Check failed: error == cudaSuccess (4 vs. 0)  unspecified launch failure
*** Check failure stack trace: ***`

`.....
v_ApplyLipstick_g05_c01 done
v_ApplyLipstick_g05_c02 done
F0415 16:02:44.536542 27311 math_functions.cpp:81] Check failed: error == cudaSuccess (4 vs. 0)  unspecified launch failure
*** Check failure stack trace: ***`

**Comment by yjxiong** [comment]
What is your command to testing? It is weired that it only errors on a single split.

**Comment by dphero** [comment]
I use the following commant

python tools/eval_net.py ucf101 2 rgb /home/hd/d/temporal-segment-networks/full_data/ucf101\
 models/ucf101/tsn_bn_inception_rgb_deploy.prototxt models/ucf101_split_2_tsn_rgb_reference_bn_inception.caffemodel \
 --num_worker 1 --save_scores SCORE_FILE_UCF101_RGB_split2

**Comment by yjxiong** [comment]
I noticed your issue #79 ,  can you confirm you are working on the full dataset of UCF101?

**Comment by dphero** [comment]
I am sure I am  working on the full dataset 
I restart my pc and run the code to test split2 and split3,  it worked without error。I do not know why, if there is further information I will back to you. thank you for your help and best wishes for you

**Comment by yjxiong** [comment]
Good to know. And happy experimenting.
