### ISSUE TITLE
caffe cannot find files ,file lists are generated again but no help 

### ISSUE THREAD

**Issue by q252558242** [yjxiong/temporal-segment-networks#83]
Hi, @yjxiong. Sorry to disturb you. I've change the size of ucf101. I successfully extract the flows and generate file lists.However, when i train the model,caffe report error that could not load file.

**Comment by yjxiong** [comment]
Run `scripts/build_file_list.sh` again. 
See here
https://github.com/yjxiong/temporal-segment-networks#construct-file-lists-for-training-and-validation

**Comment by q252558242** [comment]
thanks for your reply.I just find that the frame and flow i extracted are zip files,so caffe can't find these files.It's too silly of me to ask this question.
