### ISSUE TITLE
problem when extract

### ISSUE THREAD

**Issue by cyani527** [yjxiong/temporal-segment-networks#85]
i am sure i have the correct videos path,and have a opencv with video io support,but i still cannot get the extract

**Comment by cyani527** [comment]
I have the same problem wtih #6 
but i try all them solve way but noway

**Comment by cyani527** [comment]
FATAL[default]check failed:[video_streanm.isOpened()]cannot openvideo stream "/home/xx/UCF-101/TrampolineJumping/v_TrampolineJumping_g04_c03.avi"for optical flow extaction.
WARN[default]Aborting appliation.Reason:Fatal log at[/home/xx/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu/cpp:15]

**Comment by cyani527** [comment]
i only get a empty folder

**Comment by cyani527** [comment]
my opencv can output
--   Video I/O:
--     DC1394 1.x:                  NO
--     DC1394 2.x:                  YES (ver 2.2.1)
--     FFMPEG:                      YES
--       codec:                     YES (ver 54.35.0)
--       format:                    YES (ver 54.20.4)
--       util:                      YES (ver 52.3.0)
--       swscale:                   YES (ver 2.1.1)
--       resample:                  NO
--       gentoo-style:              YE

**Comment by yjxiong** [comment]
Hi @cyani527 . Have you solved your problem?

**Comment by cyani527** [comment]
yes,i have solved my problem,i find there are different between 32bit and 64 bit when use opencv.

**Comment by yjxiong** [comment]
Good to know. Thanks.

**Comment by wcj021312** [comment]
@cyani527  hello, I meet the same problem when I run bash scripts/extraction_optical_flow.sh SRC_FOLDER OUT_FOLDER NUM_WORKER ,the image extraction part does not get the images. can you give me some suggest about the image extraction? Thank you .
