### ISSUE TITLE
problems when build denseflow

### ISSUE THREAD

**Issue by mangdian** [yjxiong/temporal-segment-networks#87]
`
In file included from /home/zangxh/temporal-segment-networks/lib/dense_flow/src/dense_warp_flow_gpu.cpp:2:0:
/home/zangxh/temporal-segment-networks/lib/dense_flow/include/dense_flow.h:9:27: fatal error: easylogging++.h: No such file or directory
compilation terminated.
CMakeFiles/denseflow.dir/build.make:134: recipe for target 'CMakeFiles/denseflow.dir/src/dense_warp_flow_gpu.cpp.o' failed
make[2]: *** [CMakeFiles/denseflow.dir/src/dense_warp_flow_gpu.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/zangxh/temporal-segment-networks/lib/dense_flow/src/zip_utils.cpp:7:27: fatal error: easylogging++.h: No such file or directory
compilation terminated.
CMakeFiles/denseflow.dir/build.make:158: recipe for target 'CMakeFiles/denseflow.dir/src/zip_utils.cpp.o' failed
make[2]: *** [CMakeFiles/denseflow.dir/src/zip_utils.cpp.o] Error 1
In file included from /home/zangxh/temporal-segment-networks/lib/dense_flow/src/dense_flow_gpu.cpp:4:0:
/home/zangxh/temporal-segment-networks/lib/dense_flow/include/dense_flow.h:9:27: fatal error: easylogging++.h: No such file or directory
compilation terminated.
CMakeFiles/denseflow.dir/build.make:110: recipe for target 'CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o' failed
make[2]: *** [CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o] Error 1
In file included from /home/zangxh/temporal-segment-networks/lib/dense_flow/src/dense_flow.cpp:5:0:
/home/zangxh/temporal-segment-networks/lib/dense_flow/include/dense_flow.h:9:27: fatal error: easylogging++.h: No such file or directory
compilation terminated.
CMakeFiles/denseflow.dir/build.make:86: recipe for target 'CMakeFiles/denseflow.dir/src/dense_flow.cpp.o' failed
make[2]: *** [CMakeFiles/denseflow.dir/src/dense_flow.cpp.o] Error 1
In file included from /home/zangxh/temporal-segment-networks/lib/dense_flow/src/common.cpp:5:0:
/home/zangxh/temporal-segment-networks/lib/dense_flow/include/common.h:23:20: error: ‘vector’ has not been declared
                    vector<uchar>& encoded_x, vector<uchar>& encoded_y,
                    ^
/home/zangxh/temporal-segment-networks/lib/dense_flow/include/common.h:23:26: error: expected ‘,’ or ‘...’ before ‘<’ token
                    vector<uchar>& encoded_x, vector<uchar>& encoded_y,
                          ^
/home/zangxh/temporal-segment-networks/lib/dense_flow/include/common.h:36:18: error: variable or field ‘writeImages’ declared void
 void writeImages(vector<vector<uchar>> images, string name_temp);
                  ^
/home/zangxh/temporal-segment-networks/lib/dense_flow/include/common.h:36:18: error: ‘vector’ was not declared in this scope
/home/zangxh/temporal-segment-networks/lib/dense_flow/include/common.h:36:18: note: suggested alternative:
In file included from /usr/include/c++/5/vector:64:0,
                 from /usr/include/c++/5/bits/random.h:34,
                 from /usr/include/c++/5/random:49,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/local/include/opencv2/core/base.hpp:53,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/video/tracking.hpp:47,
                 from /home/zangxh/temporal-segment-networks/lib/dense_flow/include/common.h:10,
                 from /home/zangxh/temporal-segment-networks/lib/dense_flow/src/common.cpp:5:
/usr/include/c++/5/bits/stl_vector.h:214:11: note:   ‘std::vector’
     class vector : protected _Vector_base<_Tp, _Alloc>
           ^
In file included from /home/zangxh/temporal-segment-networks/lib/dense_flow/src/common.cpp:5:0:
/home/zangxh/temporal-segment-networks/lib/dense_flow/include/common.h:36:25: error: ‘vector’ was not declared in this scope
 void writeImages(vector<vector<uchar>> images, string name_temp);
`
I run the build_all.sh,after Opencv is build and install,problems occur when build denseflow.
Can anyone tell me how I can fix this?

**Comment by yjxiong** [comment]
networks/lib/dense_flow/include/dense_flow.h:9:27: fatal error: easylogging++.h

Please try following the steps in README. Especially, use `--recursive` option to clone the repo.

**Comment by mangdian** [comment]
I do cloned easylogging++,but new errors occured.
`[ 50%] Building CXX object CMakeFiles/extract_warp_gpu.dir/tools/extract_warp_flow_gpu.cpp.o
[ 57%] Building CXX object CMakeFiles/extract_cpu.dir/tools/extract_flow.cpp.o
[ 64%] Building CXX object CMakeFiles/extract_gpu.dir/tools/extract_flow_gpu.cpp.o
[ 71%] Building CXX object CMakeFiles/pydenseflow.dir/src/py_denseflow.cpp.o
[ 78%] Linking CXX executable extract_warp_gpu
[ 85%] Linking CXX executable extract_gpu
CMakeFiles/extract_warp_gpu.dir/tools/extract_warp_flow_gpu.cpp.o: In function `__static_initialization_and_destruction_0(int, int)':
extract_warp_flow_gpu.cpp:(.text+0xa50): undefined reference[ 92%] Linking CXX executable extract_cpu
 to `el::base::Storage::Storage(std::shared_ptr<el::LogBuilder> const&)'
CMakeFiles/extract_warp_gpu.dir/tools/extract_warp_flow_gpu.cpp.o: In function `el::LogBuilder::LogBuilder()':
extract_warp_flow_gpu.cpp:(.text._ZN2el10LogBuilderC2Ev[_ZN2el10LogBuilderC5Ev]+0x2b): undefined reference to `el::base::utils::OS::termSupportsColor()'
CMakeFiles/extract_warp_gpu.dir/tools/extract_warp_flow_gpu.cpp.o: In function `el::base::DefaultLogBuilder::DefaultLogBuilder()':
extract_warp_flow_gpu.cpp:(.text._ZN2el4base17DefaultLogBuilderC2Ev[_ZN2el4base17DefaultLogBuilderC5Ev]+0x1b): undefined reference to `vtable for el::base::DefaultLogBuilder'
libdenseflow.a(dense_warp_flow_gpu.cpp.o): In function `calcDenseWarpFlowGPU(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&)':
dense_warp_flow_gpu.cpp:(.text+0x1bf1): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
dense_warp_flow_gpu.cpp:(.text+0x27c1): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
dense_warp_flow_gpu.cpp:(.text+0x318b): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
libdenseflow.a(dense_warp_flow_gpu.cpp.o): In function `el::base::Writer::~Writer()':
dense_warp_flow_gpu.cpp:(.text._ZN2el4base6WriterD2Ev[_ZN2el4base6WriterD5Ev]+0x26): undefined reference to `el::base::Writer::processDispatch()'
libdenseflow.a(zip_utils.cpp.o): In function `writeZipFile(std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
zip_utils.cpp:(.text+0xce): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
zip_utils.cpp:(.text+0x2c0): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
collect2: error: ld returned 1 exit status
CMakeFiles/extract_warp_gpu.dir/build.make:150: recipe for target 'extract_warp_gpu' failed
make[2]: *** [extract_warp_gpu] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/extract_warp_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_warp_gpu.dir/all] Error 2
`

**Comment by yjxiong** [comment]
Please remove all files of TSN and start from scratch again.

**Comment by mangdian** [comment]
Thank you so much,problems solved

**Comment by buaa-luzhi** [comment]
@mangdian 
Hi ,mangdian

I have this problem, too, and many methods have been tried. Can you tell how solve it!

Thank you very much!

**Comment by mangdian** [comment]
@buaa-luzhi I'm not very sure how did I solved this since that it is a long time.you can try cloning repository this with "--recursive" option.This maybe the reason.

**Comment by buaa-luzhi** [comment]
The version of Opencv is 3.2.0.rc,  still reported wrong!, What version are you using now?

Thank you so much!

在2017-08-29 23:09:05，鹿智by1603117@buaa.edu.cn写道：

@buaa-luzhi I'm not very sure how did I solved this since that it is a long time.you can try cloning repository this with "--recursive" option.This maybe the reason.

**Comment by buaa-luzhi** [comment]
Thank you!
I have solved the problem.
Another question, "/extract_gpu -f= test.avi  -x=tmp/flow_x -y=tmp/flow_y -i=tmp/image -b=20 -t=1 -d=0 -s=1 -o=dir"
Only one video can be processed at a time ?

在2017-08-29 23:09:05，鹿智by1603117@buaa.edu.cn写道：

@buaa-luzhi I'm not very sure how did I solved this since that it is a long time.you can try cloning repository this with "--recursive" option.This maybe the reason.

**Comment by mangdian** [comment]
@buaa-luzhi the interface TSN offered can extract a dataset at one time.The "readme" file is clear enough.Besides,if you are using a dataset besides ActivityNet,UCF101,you may need add some code.

**Comment by shanYanGuan** [comment]
@mangdian How did you clone the opencv-3.1 branch?

**Comment by shanYanGuan** [comment]
`/home/guan/githubcode/dense_flow/src/dense_flow_gpu.cpp:5:35: fatal error: opencv2/xfeatures2d.hpp: No such file or directory
compilation terminated.
CMakeFiles/denseflow.dir/build.make:110: recipe for target 'CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o' failed
make[2]: *** [CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/denseflow.dir/all' failed
make[1]: *** [CMakeFiles/denseflow.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`
fatal error break out when I make -j8.what's wrong with it?
