### ISSUE TITLE
error about easylogging++

### ISSUE THREAD

**Issue by mangdian** [yjxiong/temporal-segment-networks#88]
`xtract_warp_flow_gpu.cpp:(.text+0xa50): undefined reference[ 92%] Linking CXX executable extract_cpu
 to `el::base::Storage::Storage(std::shared_ptr<el::LogBuilder> const&)'
CMakeFiles/extract_warp_gpu.dir/tools/extract_warp_flow_gpu.cpp.o: In function `el::LogBuilder::LogBuilder()':
extract_warp_flow_gpu.cpp:(.text._ZN2el10LogBuilderC2Ev[_ZN2el10LogBuilderC5Ev]+0x2b): undefined reference to `el::base::utils::OS::termSupportsColor()'
CMakeFiles/extract_warp_gpu.dir/tools/extract_warp_flow_gpu.cpp.o: In function `el::base::DefaultLogBuilder::DefaultLogBuilder()':
extract_warp_flow_gpu.cpp:(.text._ZN2el4base17DefaultLogBuilderC2Ev[_ZN2el4base17DefaultLogBuilderC5Ev]+0x1b): undefined reference to `vtable for el::base::DefaultLogBuilder'
libdenseflow.a(dense_warp_flow_gpu.cpp.o): In function `calcDenseWarpFlowGPU(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&)':
dense_warp_flow_gpu.cpp:(.text+0x1bf1): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
dense_warp_flow_gpu.cpp:(.text+0x27c1): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
dense_warp_flow_gpu.cpp:(.text+0x318b): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
libdenseflow.a(dense_warp_flow_gpu.cpp.o): In function `el::base::Writer::~Writer()':
dense_warp_flow_gpu.cpp:(.text._ZN2el4base6WriterD2Ev[_ZN2el4base6WriterD5Ev]+0x26): undefined reference to `el::base::Writer::processDispatch()'
libdenseflow.a(zip_utils.cpp.o): In function `writeZipFile(std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
zip_utils.cpp:(.text+0xce): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
zip_utils.cpp:(.text+0x2c0): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
collect2: error: ld returned 1 exit status
CMakeFiles/extract_warp_gpu.dir/build.make:150: recipe for target 'extract_warp_gpu' failed
make[2]: *** [extract_warp_gpu] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/extract_warp_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_warp_gpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/extract_gpu.dir/tools/extract_flow_gpu.cpp.o: In function `__static_initialization_and_destruction_0(int, int)':
extract_flow_gpu.cpp:(.text+0xd37): undefined reference to `el::base::Storage::Storage(std::shared_ptr<el::LogBuilder> const&)'
CMakeFiles/extract_gpu.dir/tools/extract_flow_gpu.cpp.o: In function `el::LogBuilder::LogBuilder()':
extract_flow_gpu.cpp:(.text._ZN2el10LogBuilderC2Ev[_ZN2el10LogBuilderC5Ev]+0x2b): undefined reference to `el::base::utils::OS::termSupportsColor()'
CMakeFiles/extract_gpu.dir/tools/extract_flow_gpu.cpp.o: In function `el::base::DefaultLogBuilder::DefaultLogBuilder()':
extract_flow_gpu.cpp:(.text._ZN2el4base17DefaultLogBuilderC2Ev[_ZN2el4base17DefaultLogBuilderC5Ev]+0x1b): undefined reference to `vtable for el::base::DefaultLogBuilder'
libdenseflow.a(dense_flow_gpu.cpp.o): In function `calcDenseFlowGPU(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, int, int)':
dense_flow_gpu.cpp:(.text+0x10d): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
dense_flow_gpu.cpp:(.text+0xc65): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
libdenseflow.a(dense_flow_gpu.cpp.o): In function `calcDenseFlowPureGPU(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, int, int, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&)':
dense_flow_gpu.cpp:(.text+0x1eef): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
libdenseflow.a(dense_flow_gpu.cpp.o): In function `el::base::Writer::~Writer()':
dense_flow_gpu.cpp:(.text._ZN2el4base6WriterD2Ev[_ZN2el4base6WriterD5Ev]+0x26): undefined reference to `el::base::Writer::processDispatch()'
libdenseflow.a(zip_utils.cpp.o): In function `writeZipFile(std::vector<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
zip_utils.cpp:(.text+0xce): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
zip_utils.cpp:(.text+0x2c0): undefined reference to `el::base::Writer::construct(int, char const*, ...)'
collect2: error: ld returned 1 exit status
CMakeFiles/extract_gpu.dir/build.make:150: recipe for target 'extract_gpu' failed
make[2]: *** [extract_gpu] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/extract_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_gpu.dir/all] Error 2
`

How can I fix this?

**Comment by yjxiong** [comment]
Please track your issues in #87 . Closing this.
