### ISSUE TITLE
how to set mean value

### ISSUE THREAD

**Issue by q252558242** [yjxiong/temporal-segment-networks#89]
Hi,@yjxiong. Excuse me,I want to apply this code on other videos.However,I'm not sure how to set mean value in caffe solver prototxts.I write a code to compute the mean values of rgb frames,which first compute the rgb mean values of one frame and then average all frames' mean values to get the final mean value.And I have 1117 thousands images, so I have computed 3 three days and don't finish computing.Would you tell me how you get the mean value in rgb frames and flow frames?

**Comment by yjxiong** [comment]
You can use the provided mean values in the model proto file. The init model was trained with this setting. So it should suffice unless your video are from a very distinct domain (e.g. CT scans or infra).

https://github.com/yjxiong/temporal-segment-networks/blob/master/models/ucf101/tsn_bn_inception_rgb_train_val.prototxt#L25

**Comment by q252558242** [comment]
Thanks a lot.

**Comment by yjxiong** [comment]
Closing this. Please feel free to reopen it if you meet any further problem.
