### ISSUE TITLE
The frozen parameter in BN layer

### ISSUE THREAD

**Issue by kli-nlpr** [yjxiong/temporal-segment-networks#9]
In [https://github.com/yjxiong/temporal-segment-networks/blob/master/models/ucf101/tsn_bn_inception_rgb_train_val.prototxt]

why the first frozen is false [https://github.com/yjxiong/temporal-segment-networks/blob/master/models/ucf101/tsn_bn_inception_rgb_train_val.prototxt#L59]

The following forzen are all true?

What's the purpose of this parameter?

Thanks.

**Comment by GBJim** [comment]
Hi @kli-nlpr 
It is training technique called **partial BN** on the [original paper](http://arxiv.org/abs/1608.00859)
You can find the explanation in the section3.2, Network Training part.

But I have a related question in here.
Based on the paper, Partial BN should be applied on Temporal CNN(flow), why is it also applied on Spatial CNN(RGB) as well?

**Comment by yjxiong** [comment]
@GBJim 
Basically, this can be interpreted as that RGB frames in videos are still a little different from static images on which the ImageNet models are trained. For example, consider motion blur and video compression which may affect the low-level visual features.
Using partial BN can help the model to account for these effects. This assumption is reflected in experimental results on split 1 of UCF101, which you can find in Table 1 of TSN paper.

**Comment by GBJim** [comment]
Thank you for the detailed explanation! @yjxiong
