### ISSUE TITLE
How to get classification results of sub-videos?

### ISSUE THREAD

**Issue by mangdian** [yjxiong/temporal-segment-networks#90]
Hello,
First appreciate you work very much.
I am now doing a work about temporal localization.I want to use TSN as my classification tool.However,I read the README file and find that it only tells how to test on video-level.What I want is input some consequent frames(.jpg) into TSN,not a entire video.What should I do?Or how should me organize the input list file?
Thank you very much.

**Comment by mangdian** [comment]
And in the input list
 "video_frame_path 100 10
video_2_frame_path 150 31
..."
what does the first number mean?the number of frames? or the id of the starting frame?

**Comment by mangdian** [comment]
another problem:
E0430 13:09:28.478206 28625 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
E0430 13:09:28.960337 28626 common.cpp:121] Cannot create Curand generator. Curand won't be available.
E0430 13:09:29.032064 28625 common.cpp:121] Cannot create Curand generator. Curand won't be available.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0430 13:09:29.358052 28623 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
WARNING: Logging before InitGoogleLogging() is written to STDERR

F0430 13:09:36.040047 28624 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/ucf101/tsn_bn_inception_rgb_deploy.prototxt
*** Check failure stack trace: ***
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0430 13:09:38.301300 28669 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
E0430 13:09:38.455785 28669 common.cpp:121] Cannot create Curand generator. Curand won't be available.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0430 13:09:38.470021 28666 common.cpp:121] Cannot create Curand generator. Curand won't be available.
F0430 13:09:38.485169 28669 common.cpp:158] Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal
*** Check failure stack trace: ***
F0430 13:09:38.502897 28666 common.cpp:158] Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal
*** Check failure stack trace: ***
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0430 13:09:39.342923 28676 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
F0430 13:09:40.977171 28676 common.cpp:158] Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal

**Comment by yjxiong** [comment]
You can use the standard caffe Python interfaces for classifying single frames, such as using `Classifier`.

**Comment by yjxiong** [comment]
Tracked together in #92
