### ISSUE TITLE
Classification results get accuracy:%nan

### ISSUE THREAD

**Issue by mangdian** [yjxiong/temporal-segment-networks#92]
I use the TSN to classify my own videos,I modified the code and it turn out to work when I test with a list of two videos.However,when I use it to RUN 156 videos,there are some errors:
`/home/zangxh/temporal-segment-networks/pyActionRecog/utils/metrics.py:60: RuntimeWarning: invalid value encountered in divide
  return np.mean(cls_hit/cls_cnt)
Final accuracy nan%
`
how can I fix this?
Thank you for your help.

**Comment by yjxiong** [comment]
Do you have any class id that has no instance in you dataset?

**Comment by mangdian** [comment]
I am sure that every class has instance.
'def mean_class_accuracy(scores, labels): 
    pred = np.argmax(scores, axis=1)
    cf = confusion_matrix(labels, pred).astype(float)
    cls_cnt = cf.sum(axis=1)
    cls_hit = np.diag(cf)
    return np.mean(cls_hit/cls_cnt)'
I found that there are a lot of zeros values in cls_cnt,so that cls_hit/cls_cnt turns out be of no significance.
I am confused ,why there are a lot of zeros?

**Comment by yjxiong** [comment]
What I said is that your class labels should be contiguous from 0 to N. 

Also, to test on custom datasets, always make sure that there is a registered parser in `benchmark_db.py`.

See
https://github.com/yjxiong/temporal-segment-networks/blob/master/pyActionRecog/benchmark_db.py#L42
and
https://github.com/yjxiong/temporal-segment-networks/blob/master/pyActionRecog/__init__.py#L5
on how to register it. File lists are only used in training.

The canonical way of working on custom datasets is to write a parser and use it to generate the file lists for training.

**Comment by yjxiong** [comment]
See a complete guide on custom datasets here
https://github.com/yjxiong/temporal-segment-networks/wiki/Working-on-custom-datasets.

**Comment by yjxiong** [comment]
@mangdian 

Have you solved the problem? If so, I will close this issues.
