### ISSUE TITLE
about multi-gpu and batchsize

### ISSUE THREAD

**Issue by hawklucky** [yjxiong/temporal-segment-networks#93]
If I use N multi-gpu via openmpi，each iteration， the number of data feeding into network is #batchsize or #batchsize*Ngpus？

**Comment by yjxiong** [comment]
It's `batchsize*iter_size*num_gpus`.

**Comment by Ai-is-light** [comment]
@hawklucky would you mind telling me how to use N multi-gpu via openmpi ? I mean, how to set multi-gups to train model? 
Thanks

**Comment by hawklucky** [comment]
@Ai-is-light I think you should build caffe with openmpi first, then set the GPUs which you are going to use in the solver file. I hope it will help you.

**Comment by Mohamad73** [comment]
How can I change the iter_size??
