### ISSUE TITLE
Errors when import cv2

### ISSUE THREAD

**Issue by StOnEGiggity** [yjxiong/temporal-segment-networks#95]
Hi,
         recently, I update cuda 7.5 to cuda 8.0.I met some problems when I test the TSN Network. As the file Readme, I input the code.And i get one input error,
          ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory
          It seems that the opencv version doesn't match cuda8.0.Is there any suggestions?
Thanks.

**Comment by yjxiong** [comment]
You can issue the command `ldd cv2.so | grep cuda` to check the cuda version which OpenCV links to. If you find it is still linking to cuda 7.5, you can try clean up `3rd-party/opencv-xxxxx/build` and build OpenCV again. The command can be found in `build_all.sh`
https://github.com/yjxiong/temporal-segment-networks/blob/master/build_all.sh#L39

**Comment by StOnEGiggity** [comment]
Sorry for replying too late.The reason is multi version of OpenCV. I delete all OpenCV data and install it again. It's a simple problem. Thanks.
