### ISSUE TITLE
Inception-V3 model 

### ISSUE THREAD

**Issue by bryanyzhu** [yjxiong/temporal-segment-networks#97]
Thanks for the great work. I am reading your recent papers on Arxiv, and you used Inception-V3 network for better performance. I was just wondering, for Inception-V3, the input size requirement is 299x299. So may you explain more on how did you pre-process the video frames? Thanks a lot.

Specifically, like your multi-scale cropping method. Before, you scale the image to 256x340, then scale ratio is set to [1, 0.875, 0.75, 0.66], which means the image size is [256, 224, 180, 158], then resize to 224x224. Now if the input size is 299x299, how do you do the multi-scale cropping in your experiments. Thanks a lot.

Another side question is, in data_transformer.cpp line 93 [here](https://github.com/yjxiong/caffe/blob/action_recog/src/caffe/data_transformer.cpp#L93) I don't quite get it why it is less than 3, and why 3? Thank you very much for your help.
abs(crop_h - net_input_height) < 3
crop_w - net_input_width) < 3

Thanks a lot.

**Comment by yjxiong** [comment]
Multi-scale cropping does not rely on the network input size. The cropped images will finally be resized to fit the network's input size.

That `3` used to save some corner case handling when `crop_h` is close to raw image size. You can remove it if needed.
