### ISSUE TITLE
Running the code on a completely different dataset

### ISSUE THREAD

**Issue by ycbilge** [yjxiong/temporal-segment-networks#98]
Hello, 
Is there anyway to run the code on the dataset other than ucf101, hmdb51, activitynet_1.2, activitynet_1.3?
I would be glad if anybody will help me on this issue.
Thanks for your time
Best,

**Comment by bryanyzhu** [comment]
I think they write a tutorial for how to work on your own dataset at [here](https://github.com/yjxiong/temporal-segment-networks/wiki/Working-on-custom-datasets.) .

**Comment by yjxiong** [comment]
Thank you @bryanyzhu for the information.

Yes, you can refer to that tutorial on working with your custom dataset.

**Comment by ycbilge** [comment]
Thank you very much @bryanyzhu @yjxiong
